// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: owner_connectors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearConnectorTokens = `-- name: ClearConnectorTokens :exec
UPDATE owner_connectors
SET token_enc = '\x'::bytea, token_expires_at = NULL,
    connected_at = NULL, active = false, updated_at = now()
WHERE owner_id = $1 AND connector_id = $2
`

type ClearConnectorTokensParams struct {
	OwnerID     pgtype.UUID
	ConnectorID string
}

// soft disconnect: wipe token + connected + active, keep credentials (one-click reconnect without re-entering).
func (q *Queries) ClearConnectorTokens(ctx context.Context, arg ClearConnectorTokensParams) error {
	_, err := q.db.Exec(ctx, clearConnectorTokens, arg.OwnerID, arg.ConnectorID)
	return err
}

const deleteConnector = `-- name: DeleteConnector :exec
DELETE FROM owner_connectors
WHERE owner_id = $1 AND connector_id = $2
`

type DeleteConnectorParams struct {
	OwnerID     pgtype.UUID
	ConnectorID string
}

func (q *Queries) DeleteConnector(ctx context.Context, arg DeleteConnectorParams) error {
	_, err := q.db.Exec(ctx, deleteConnector, arg.OwnerID, arg.ConnectorID)
	return err
}

const deleteUploadedConnector = `-- name: DeleteUploadedConnector :exec
DELETE FROM owner_connectors
WHERE owner_id = $1 AND connector_id = $2
`

type DeleteUploadedConnectorParams struct {
	OwnerID     pgtype.UUID
	ConnectorID string
}

// Delete an owner-authored connector (row delete). The category slot it filled goes empty (slot store reads nothing → cap re-gates).
func (q *Queries) DeleteUploadedConnector(ctx context.Context, arg DeleteUploadedConnectorParams) error {
	_, err := q.db.Exec(ctx, deleteUploadedConnector, arg.OwnerID, arg.ConnectorID)
	return err
}

const getConnector = `-- name: GetConnector :one
SELECT id, owner_id, connector_id, category, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, spec, binding, auth_scheme, protocol, expose_as_agent_tools, title, created_at, updated_at FROM owner_connectors
WHERE owner_id = $1 AND connector_id = $2
`

type GetConnectorParams struct {
	OwnerID     pgtype.UUID
	ConnectorID string
}

func (q *Queries) GetConnector(ctx context.Context, arg GetConnectorParams) (OwnerConnector, error) {
	row := q.db.QueryRow(ctx, getConnector, arg.OwnerID, arg.ConnectorID)
	var i OwnerConnector
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConnectorID,
		&i.Category,
		&i.Kind,
		&i.CredentialsEnc,
		&i.TokenEnc,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.ConnectedAt,
		&i.Active,
		&i.Spec,
		&i.Binding,
		&i.AuthScheme,
		&i.Protocol,
		&i.ExposeAsAgentTools,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorManifest = `-- name: GetConnectorManifest :one
SELECT category, kind, spec, binding, auth_scheme, protocol, expose_as_agent_tools
FROM owner_connectors
WHERE owner_id = $1 AND connector_id = $2
`

type GetConnectorManifestParams struct {
	OwnerID     pgtype.UUID
	ConnectorID string
}

type GetConnectorManifestRow struct {
	Category           string
	Kind               string
	Spec               []byte
	Binding            []byte
	AuthScheme         string
	Protocol           string
	ExposeAsAgentTools bool
}

// Fetch a connector's stored manifest fields (uploaded connectors have spec/binding; protocol connectors have protocol).
func (q *Queries) GetConnectorManifest(ctx context.Context, arg GetConnectorManifestParams) (GetConnectorManifestRow, error) {
	row := q.db.QueryRow(ctx, getConnectorManifest, arg.OwnerID, arg.ConnectorID)
	var i GetConnectorManifestRow
	err := row.Scan(
		&i.Category,
		&i.Kind,
		&i.Spec,
		&i.Binding,
		&i.AuthScheme,
		&i.Protocol,
		&i.ExposeAsAgentTools,
	)
	return i, err
}

const insertUploadedConnector = `-- name: InsertUploadedConnector :one
INSERT INTO owner_connectors (
    owner_id, connector_id, category, kind, spec, binding, auth_scheme, protocol,
    expose_as_agent_tools, title
)
VALUES (
    $1, $2, $3,
    $4, $5::bytea, $6::bytea,
    $7, $8, $9,
    $10
)
RETURNING id, owner_id, connector_id, category, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, spec, binding, auth_scheme, protocol, expose_as_agent_tools, title, created_at, updated_at
`

type InsertUploadedConnectorParams struct {
	OwnerID            pgtype.UUID
	ConnectorID        string
	Category           string
	Kind               string
	Spec               []byte
	Binding            []byte
	AuthScheme         string
	Protocol           string
	ExposeAsAgentTools bool
	Title              string
}

// Upload an openapi connector (owner pastes spec + JSONata binding in the UI): create the row and store the manifest
// (spec/binding/auth_scheme), not connected on first write. category/kind are set by the binding.
func (q *Queries) InsertUploadedConnector(ctx context.Context, arg InsertUploadedConnectorParams) (OwnerConnector, error) {
	row := q.db.QueryRow(ctx, insertUploadedConnector,
		arg.OwnerID,
		arg.ConnectorID,
		arg.Category,
		arg.Kind,
		arg.Spec,
		arg.Binding,
		arg.AuthScheme,
		arg.Protocol,
		arg.ExposeAsAgentTools,
		arg.Title,
	)
	var i OwnerConnector
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConnectorID,
		&i.Category,
		&i.Kind,
		&i.CredentialsEnc,
		&i.TokenEnc,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.ConnectedAt,
		&i.Active,
		&i.Spec,
		&i.Binding,
		&i.AuthScheme,
		&i.Protocol,
		&i.ExposeAsAgentTools,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnectorsByCategory = `-- name: ListConnectorsByCategory :many
SELECT id, owner_id, connector_id, category, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, spec, binding, auth_scheme, protocol, expose_as_agent_tools, title, created_at, updated_at FROM owner_connectors
WHERE owner_id = $1 AND category = $2
ORDER BY connector_id
`

type ListConnectorsByCategoryParams struct {
	OwnerID  pgtype.UUID
	Category string
}

func (q *Queries) ListConnectorsByCategory(ctx context.Context, arg ListConnectorsByCategoryParams) ([]OwnerConnector, error) {
	rows, err := q.db.Query(ctx, listConnectorsByCategory, arg.OwnerID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnerConnector
	for rows.Next() {
		var i OwnerConnector
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ConnectorID,
			&i.Category,
			&i.Kind,
			&i.CredentialsEnc,
			&i.TokenEnc,
			&i.TokenExpiresAt,
			&i.Scopes,
			&i.ConnectedAt,
			&i.Active,
			&i.Spec,
			&i.Binding,
			&i.AuthScheme,
			&i.Protocol,
			&i.ExposeAsAgentTools,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectorsByOwner = `-- name: ListConnectorsByOwner :many
SELECT id, owner_id, connector_id, category, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, spec, binding, auth_scheme, protocol, expose_as_agent_tools, title, created_at, updated_at FROM owner_connectors
WHERE owner_id = $1
ORDER BY category, connector_id
`

func (q *Queries) ListConnectorsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]OwnerConnector, error) {
	rows, err := q.db.Query(ctx, listConnectorsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnerConnector
	for rows.Next() {
		var i OwnerConnector
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ConnectorID,
			&i.Category,
			&i.Kind,
			&i.CredentialsEnc,
			&i.TokenEnc,
			&i.TokenExpiresAt,
			&i.Scopes,
			&i.ConnectedAt,
			&i.Active,
			&i.Spec,
			&i.Binding,
			&i.AuthScheme,
			&i.Protocol,
			&i.ExposeAsAgentTools,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadedConnectors = `-- name: ListUploadedConnectors :many
SELECT DISTINCT ON (connector_id)
    connector_id, category, kind, spec, binding, auth_scheme, protocol, expose_as_agent_tools
FROM owner_connectors
WHERE length(spec) > 0 OR kind = 'protocol'
ORDER BY connector_id, updated_at DESC
`

type ListUploadedConnectorsRow struct {
	ConnectorID        string
	Category           string
	Kind               string
	Spec               []byte
	Binding            []byte
	AuthScheme         string
	Protocol           string
	ExposeAsAgentTools bool
}

// Reload on boot: all owner-authored connectors (openapi with a spec + kind=protocol connectors), across owners
// (v1 single owner; Hub keys by connector_id). Built-in connectors have empty spec and kind!=protocol, so they are excluded.
func (q *Queries) ListUploadedConnectors(ctx context.Context) ([]ListUploadedConnectorsRow, error) {
	rows, err := q.db.Query(ctx, listUploadedConnectors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUploadedConnectorsRow
	for rows.Next() {
		var i ListUploadedConnectorsRow
		if err := rows.Scan(
			&i.ConnectorID,
			&i.Category,
			&i.Kind,
			&i.Spec,
			&i.Binding,
			&i.AuthScheme,
			&i.Protocol,
			&i.ExposeAsAgentTools,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConnectorConnected = `-- name: MarkConnectorConnected :execrows
UPDATE owner_connectors
SET connected_at = COALESCE(connected_at, now()), updated_at = now()
WHERE owner_id = $1 AND connector_id = $2
`

type MarkConnectorConnectedParams struct {
	OwnerID     pgtype.UUID
	ConnectorID string
}

// protocol connector verified (no oauth dance) → mark connected.
// **:execrows, not :exec** —— this row is created by the "store credentials" step. When the owner does not have
// it yet, this UPDATE matches 0 rows without erroring and the caller still returns connected:true —— a lie, and
// one that every fresh install hits. The row count is the only receipt this write has; the caller must read it.
func (q *Queries) MarkConnectorConnected(ctx context.Context, arg MarkConnectorConnectedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markConnectorConnected, arg.OwnerID, arg.ConnectorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setActiveConnector = `-- name: SetActiveConnector :many
UPDATE owner_connectors
SET active = (connector_id = $1::text), updated_at = now()
WHERE owner_id = $2 AND category = $3
RETURNING connector_id
`

type SetActiveConnectorParams struct {
	ConnectorID string
	OwnerID     pgtype.UUID
	Category    string
}

// Only one active per category slot at a time: set the target active, set the rest of the category inactive (§9 slot rule).
// **RETURNING is the receipt.** The row count proves nothing here: the update spans the whole category, and when the
// target row is not among them the rest are all set inactive while the count stays > 0 —— the result of "activate" is
// that **this category has no active at all**. So the receipt must be the names: the caller checks whether the target
// connector_id is in the returned set.
func (q *Queries) SetActiveConnector(ctx context.Context, arg SetActiveConnectorParams) ([]string, error) {
	rows, err := q.db.Query(ctx, setActiveConnector, arg.ConnectorID, arg.OwnerID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var connector_id string
		if err := rows.Scan(&connector_id); err != nil {
			return nil, err
		}
		items = append(items, connector_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnectorTokens = `-- name: UpdateConnectorTokens :one
UPDATE owner_connectors
SET token_enc = $1::bytea,
    token_expires_at = $2::timestamptz,
    scopes = $3::jsonb,
    connected_at = COALESCE(connected_at, now()),
    updated_at = now()
WHERE owner_id = $4 AND connector_id = $5
RETURNING id, owner_id, connector_id, category, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, spec, binding, auth_scheme, protocol, expose_as_agent_tools, title, created_at, updated_at
`

type UpdateConnectorTokensParams struct {
	TokenEnc       []byte
	TokenExpiresAt pgtype.Timestamptz
	Scopes         []byte
	OwnerID        pgtype.UUID
	ConnectorID    string
}

// OAuth gets its first token, or the refresh path gets a new access_token. First token obtained → connected.
func (q *Queries) UpdateConnectorTokens(ctx context.Context, arg UpdateConnectorTokensParams) (OwnerConnector, error) {
	row := q.db.QueryRow(ctx, updateConnectorTokens,
		arg.TokenEnc,
		arg.TokenExpiresAt,
		arg.Scopes,
		arg.OwnerID,
		arg.ConnectorID,
	)
	var i OwnerConnector
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConnectorID,
		&i.Category,
		&i.Kind,
		&i.CredentialsEnc,
		&i.TokenEnc,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.ConnectedAt,
		&i.Active,
		&i.Spec,
		&i.Binding,
		&i.AuthScheme,
		&i.Protocol,
		&i.ExposeAsAgentTools,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUploadedConnector = `-- name: UpdateUploadedConnector :exec
UPDATE owner_connectors
SET spec = $1::bytea, binding = $2::bytea,
    category = $3, auth_scheme = $4,
    expose_as_agent_tools = $5,
    title = $6,
    connected_at = NULL, updated_at = now()
WHERE owner_id = $7 AND connector_id = $8
`

type UpdateUploadedConnectorParams struct {
	Spec               []byte
	Binding            []byte
	Category           string
	AuthScheme         string
	ExposeAsAgentTools bool
	Title              string
	OwnerID            pgtype.UUID
	ConnectorID        string
}

// Edit the spec/binding/auth_scheme of an existing uploaded connector (owner edits the spec in the UI → reassemble +
// re-derive the credentials form). After changing the auth type the credentials must be re-entered, so clear
// connected_at (reconnect). category may change with it.
func (q *Queries) UpdateUploadedConnector(ctx context.Context, arg UpdateUploadedConnectorParams) error {
	_, err := q.db.Exec(ctx, updateUploadedConnector,
		arg.Spec,
		arg.Binding,
		arg.Category,
		arg.AuthScheme,
		arg.ExposeAsAgentTools,
		arg.Title,
		arg.OwnerID,
		arg.ConnectorID,
	)
	return err
}

const upsertConnectorCredentials = `-- name: UpsertConnectorCredentials :one

INSERT INTO owner_connectors (
    owner_id, connector_id, category, kind, credentials_enc
)
VALUES (
    $1, $2, $3,
    $4, $5::bytea
)
ON CONFLICT (owner_id, connector_id) DO UPDATE
SET credentials_enc = EXCLUDED.credentials_enc,
    category = EXCLUDED.category,
    kind = EXCLUDED.kind,
    connected_at = CASE
        WHEN $6::boolean THEN NULL
        ELSE owner_connectors.connected_at
    END,
    updated_at = now()
RETURNING id, owner_id, connector_id, category, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, spec, binding, auth_scheme, protocol, expose_as_agent_tools, title, created_at, updated_at
`

type UpsertConnectorCredentialsParams struct {
	OwnerID        pgtype.UUID
	ConnectorID    string
	Category       string
	Kind           string
	CredentialsEnc []byte
	ResetConnected bool
}

// owner_connectors.sql —— #155 read/write of unified connector connection state (one table for any kind/category).
// Store/overwrite one connector's credentials (owner-supplied app creds / apiKey / smtp config). category/kind
// are set on first write.
//
// connected_at is decided by `reset_connected`, **not cleared unconditionally** (F-C-30):
// §3 D-5 requires "changing identity/credentials must re-verify" —— that rule should fire only when something
// **changed**. But the first thing the panel's Connect does is POST /credentials, so "connected" is lost before
// authorization even starts; the owner only has to reopen the card and re-save once (without touching a single
// value) and a perfectly good connection shows as "not connected" while the token is still alive.
// The caller compares the merged credentials against the original: pass true only when they truly changed.
func (q *Queries) UpsertConnectorCredentials(ctx context.Context, arg UpsertConnectorCredentialsParams) (OwnerConnector, error) {
	row := q.db.QueryRow(ctx, upsertConnectorCredentials,
		arg.OwnerID,
		arg.ConnectorID,
		arg.Category,
		arg.Kind,
		arg.CredentialsEnc,
		arg.ResetConnected,
	)
	var i OwnerConnector
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConnectorID,
		&i.Category,
		&i.Kind,
		&i.CredentialsEnc,
		&i.TokenEnc,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.ConnectedAt,
		&i.Active,
		&i.Spec,
		&i.Binding,
		&i.AuthScheme,
		&i.Protocol,
		&i.ExposeAsAgentTools,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
