// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: owner_connectors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearConnectorTokens = `-- name: ClearConnectorTokens :exec
UPDATE owner_connectors
SET token_enc = '\x'::bytea, token_expires_at = NULL,
    connected_at = NULL, active = false, updated_at = now()
WHERE owner_id = $1 AND connector_id = $2
`

type ClearConnectorTokensParams struct {
	OwnerID     pgtype.UUID
	ConnectorID string
}

// soft disconnect：擦 token + connected + active，保留 credentials（一键重连不重填）。
func (q *Queries) ClearConnectorTokens(ctx context.Context, arg ClearConnectorTokensParams) error {
	_, err := q.db.Exec(ctx, clearConnectorTokens, arg.OwnerID, arg.ConnectorID)
	return err
}

const deleteConnector = `-- name: DeleteConnector :exec
DELETE FROM owner_connectors
WHERE owner_id = $1 AND connector_id = $2
`

type DeleteConnectorParams struct {
	OwnerID     pgtype.UUID
	ConnectorID string
}

func (q *Queries) DeleteConnector(ctx context.Context, arg DeleteConnectorParams) error {
	_, err := q.db.Exec(ctx, deleteConnector, arg.OwnerID, arg.ConnectorID)
	return err
}

const deleteUploadedConnector = `-- name: DeleteUploadedConnector :exec
DELETE FROM owner_connectors
WHERE owner_id = $1 AND connector_id = $2
`

type DeleteUploadedConnectorParams struct {
	OwnerID     pgtype.UUID
	ConnectorID string
}

// 删一个 owner 自建连接器（行删除）。它填的品类槽随之空（slot store 读不到 → cap 复闸）。
func (q *Queries) DeleteUploadedConnector(ctx context.Context, arg DeleteUploadedConnectorParams) error {
	_, err := q.db.Exec(ctx, deleteUploadedConnector, arg.OwnerID, arg.ConnectorID)
	return err
}

const getConnector = `-- name: GetConnector :one
SELECT id, owner_id, connector_id, category, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, spec, binding, auth_scheme, protocol, expose_as_agent_tools, title, created_at, updated_at FROM owner_connectors
WHERE owner_id = $1 AND connector_id = $2
`

type GetConnectorParams struct {
	OwnerID     pgtype.UUID
	ConnectorID string
}

func (q *Queries) GetConnector(ctx context.Context, arg GetConnectorParams) (OwnerConnector, error) {
	row := q.db.QueryRow(ctx, getConnector, arg.OwnerID, arg.ConnectorID)
	var i OwnerConnector
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConnectorID,
		&i.Category,
		&i.Kind,
		&i.CredentialsEnc,
		&i.TokenEnc,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.ConnectedAt,
		&i.Active,
		&i.Spec,
		&i.Binding,
		&i.AuthScheme,
		&i.Protocol,
		&i.ExposeAsAgentTools,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorManifest = `-- name: GetConnectorManifest :one
SELECT category, kind, spec, binding, auth_scheme, protocol, expose_as_agent_tools
FROM owner_connectors
WHERE owner_id = $1 AND connector_id = $2
`

type GetConnectorManifestParams struct {
	OwnerID     pgtype.UUID
	ConnectorID string
}

type GetConnectorManifestRow struct {
	Category           string
	Kind               string
	Spec               []byte
	Binding            []byte
	AuthScheme         string
	Protocol           string
	ExposeAsAgentTools bool
}

// 取一个连接器存档的 manifest 字段（上传连接器有 spec/binding；protocol 连接器有 protocol）。
func (q *Queries) GetConnectorManifest(ctx context.Context, arg GetConnectorManifestParams) (GetConnectorManifestRow, error) {
	row := q.db.QueryRow(ctx, getConnectorManifest, arg.OwnerID, arg.ConnectorID)
	var i GetConnectorManifestRow
	err := row.Scan(
		&i.Category,
		&i.Kind,
		&i.Spec,
		&i.Binding,
		&i.AuthScheme,
		&i.Protocol,
		&i.ExposeAsAgentTools,
	)
	return i, err
}

const insertUploadedConnector = `-- name: InsertUploadedConnector :one
INSERT INTO owner_connectors (
    owner_id, connector_id, category, kind, spec, binding, auth_scheme, protocol,
    expose_as_agent_tools, title
)
VALUES (
    $1, $2, $3,
    $4, $5::bytea, $6::bytea,
    $7, $8, $9,
    $10
)
RETURNING id, owner_id, connector_id, category, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, spec, binding, auth_scheme, protocol, expose_as_agent_tools, title, created_at, updated_at
`

type InsertUploadedConnectorParams struct {
	OwnerID            pgtype.UUID
	ConnectorID        string
	Category           string
	Kind               string
	Spec               []byte
	Binding            []byte
	AuthScheme         string
	Protocol           string
	ExposeAsAgentTools bool
	Title              string
}

// 上传一个 openapi 连接器（owner 在 UI 贴 spec + JSONata binding）：建行并存下 manifest
// （spec/binding/auth_scheme），首次未连。category/kind 由 binding 定。
func (q *Queries) InsertUploadedConnector(ctx context.Context, arg InsertUploadedConnectorParams) (OwnerConnector, error) {
	row := q.db.QueryRow(ctx, insertUploadedConnector,
		arg.OwnerID,
		arg.ConnectorID,
		arg.Category,
		arg.Kind,
		arg.Spec,
		arg.Binding,
		arg.AuthScheme,
		arg.Protocol,
		arg.ExposeAsAgentTools,
		arg.Title,
	)
	var i OwnerConnector
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConnectorID,
		&i.Category,
		&i.Kind,
		&i.CredentialsEnc,
		&i.TokenEnc,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.ConnectedAt,
		&i.Active,
		&i.Spec,
		&i.Binding,
		&i.AuthScheme,
		&i.Protocol,
		&i.ExposeAsAgentTools,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnectorsByCategory = `-- name: ListConnectorsByCategory :many
SELECT id, owner_id, connector_id, category, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, spec, binding, auth_scheme, protocol, expose_as_agent_tools, title, created_at, updated_at FROM owner_connectors
WHERE owner_id = $1 AND category = $2
ORDER BY connector_id
`

type ListConnectorsByCategoryParams struct {
	OwnerID  pgtype.UUID
	Category string
}

func (q *Queries) ListConnectorsByCategory(ctx context.Context, arg ListConnectorsByCategoryParams) ([]OwnerConnector, error) {
	rows, err := q.db.Query(ctx, listConnectorsByCategory, arg.OwnerID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnerConnector
	for rows.Next() {
		var i OwnerConnector
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ConnectorID,
			&i.Category,
			&i.Kind,
			&i.CredentialsEnc,
			&i.TokenEnc,
			&i.TokenExpiresAt,
			&i.Scopes,
			&i.ConnectedAt,
			&i.Active,
			&i.Spec,
			&i.Binding,
			&i.AuthScheme,
			&i.Protocol,
			&i.ExposeAsAgentTools,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectorsByOwner = `-- name: ListConnectorsByOwner :many
SELECT id, owner_id, connector_id, category, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, spec, binding, auth_scheme, protocol, expose_as_agent_tools, title, created_at, updated_at FROM owner_connectors
WHERE owner_id = $1
ORDER BY category, connector_id
`

func (q *Queries) ListConnectorsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]OwnerConnector, error) {
	rows, err := q.db.Query(ctx, listConnectorsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnerConnector
	for rows.Next() {
		var i OwnerConnector
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ConnectorID,
			&i.Category,
			&i.Kind,
			&i.CredentialsEnc,
			&i.TokenEnc,
			&i.TokenExpiresAt,
			&i.Scopes,
			&i.ConnectedAt,
			&i.Active,
			&i.Spec,
			&i.Binding,
			&i.AuthScheme,
			&i.Protocol,
			&i.ExposeAsAgentTools,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadedConnectors = `-- name: ListUploadedConnectors :many
SELECT DISTINCT ON (connector_id)
    connector_id, category, kind, spec, binding, auth_scheme, protocol, expose_as_agent_tools
FROM owner_connectors
WHERE length(spec) > 0 OR kind = 'protocol'
ORDER BY connector_id, updated_at DESC
`

type ListUploadedConnectorsRow struct {
	ConnectorID        string
	Category           string
	Kind               string
	Spec               []byte
	Binding            []byte
	AuthScheme         string
	Protocol           string
	ExposeAsAgentTools bool
}

// 拉起时重装：所有 owner 自建连接器（带 spec 的 openapi + kind=protocol 协议连接器），跨 owner
// （v1 单 owner；Hub 按 connector_id）。内置连接器 spec 空且 kind!=protocol，不在此列。
func (q *Queries) ListUploadedConnectors(ctx context.Context) ([]ListUploadedConnectorsRow, error) {
	rows, err := q.db.Query(ctx, listUploadedConnectors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUploadedConnectorsRow
	for rows.Next() {
		var i ListUploadedConnectorsRow
		if err := rows.Scan(
			&i.ConnectorID,
			&i.Category,
			&i.Kind,
			&i.Spec,
			&i.Binding,
			&i.AuthScheme,
			&i.Protocol,
			&i.ExposeAsAgentTools,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConnectorConnected = `-- name: MarkConnectorConnected :execrows
UPDATE owner_connectors
SET connected_at = COALESCE(connected_at, now()), updated_at = now()
WHERE owner_id = $1 AND connector_id = $2
`

type MarkConnectorConnectedParams struct {
	OwnerID     pgtype.UUID
	ConnectorID string
}

// protocol 连接器验证通过（无 oauth dance）→ 标记 connected。
// **:execrows,不是 :exec** —— 这一行是"存凭据"那步建的。owner 还没有它的时候,这条 UPDATE
// 命中 0 行、不报错,调用方照样回 connected:true —— 一句谎话,而且每一次全新安装都踩得到。
// 行数是这笔写入唯一的回执,调用方必须看它。
func (q *Queries) MarkConnectorConnected(ctx context.Context, arg MarkConnectorConnectedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markConnectorConnected, arg.OwnerID, arg.ConnectorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setActiveConnector = `-- name: SetActiveConnector :many
UPDATE owner_connectors
SET active = (connector_id = $1::text), updated_at = now()
WHERE owner_id = $2 AND category = $3
RETURNING connector_id
`

type SetActiveConnectorParams struct {
	ConnectorID string
	OwnerID     pgtype.UUID
	Category    string
}

// 一个品类槽同时只一个 active：把目标置 active、同品类其余置非 active（§9 槽位规则）。
// **RETURNING 是回执。** 行数在这里证明不了什么：更新的是整个品类，目标行不在其中时其余全被
// 置成非 active，行数照样大于 0 —— "激活"的结果是**这个品类一个 active 都没有**。所以回执
// 必须是名字：调用方要看目标 connector_id 在不在里面。
func (q *Queries) SetActiveConnector(ctx context.Context, arg SetActiveConnectorParams) ([]string, error) {
	rows, err := q.db.Query(ctx, setActiveConnector, arg.ConnectorID, arg.OwnerID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var connector_id string
		if err := rows.Scan(&connector_id); err != nil {
			return nil, err
		}
		items = append(items, connector_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnectorTokens = `-- name: UpdateConnectorTokens :one
UPDATE owner_connectors
SET token_enc = $1::bytea,
    token_expires_at = $2::timestamptz,
    scopes = $3::jsonb,
    connected_at = COALESCE(connected_at, now()),
    updated_at = now()
WHERE owner_id = $4 AND connector_id = $5
RETURNING id, owner_id, connector_id, category, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, spec, binding, auth_scheme, protocol, expose_as_agent_tools, title, created_at, updated_at
`

type UpdateConnectorTokensParams struct {
	TokenEnc       []byte
	TokenExpiresAt pgtype.Timestamptz
	Scopes         []byte
	OwnerID        pgtype.UUID
	ConnectorID    string
}

// OAuth 拿到首次 token，或 refresh 路径拿到新 access_token。首次拿到 token → connected。
func (q *Queries) UpdateConnectorTokens(ctx context.Context, arg UpdateConnectorTokensParams) (OwnerConnector, error) {
	row := q.db.QueryRow(ctx, updateConnectorTokens,
		arg.TokenEnc,
		arg.TokenExpiresAt,
		arg.Scopes,
		arg.OwnerID,
		arg.ConnectorID,
	)
	var i OwnerConnector
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConnectorID,
		&i.Category,
		&i.Kind,
		&i.CredentialsEnc,
		&i.TokenEnc,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.ConnectedAt,
		&i.Active,
		&i.Spec,
		&i.Binding,
		&i.AuthScheme,
		&i.Protocol,
		&i.ExposeAsAgentTools,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUploadedConnector = `-- name: UpdateUploadedConnector :exec
UPDATE owner_connectors
SET spec = $1::bytea, binding = $2::bytea,
    category = $3, auth_scheme = $4,
    expose_as_agent_tools = $5,
    title = $6,
    connected_at = NULL, updated_at = now()
WHERE owner_id = $7 AND connector_id = $8
`

type UpdateUploadedConnectorParams struct {
	Spec               []byte
	Binding            []byte
	Category           string
	AuthScheme         string
	ExposeAsAgentTools bool
	Title              string
	OwnerID            pgtype.UUID
	ConnectorID        string
}

// 编辑已建上传连接器的 spec/binding/auth_scheme（owner 在 UI 改 spec → 重新装配 + 重派生凭据
// 表单）。换认证 type 后凭据需重新填，清掉 connected_at（重新连）。category 可能随之变。
func (q *Queries) UpdateUploadedConnector(ctx context.Context, arg UpdateUploadedConnectorParams) error {
	_, err := q.db.Exec(ctx, updateUploadedConnector,
		arg.Spec,
		arg.Binding,
		arg.Category,
		arg.AuthScheme,
		arg.ExposeAsAgentTools,
		arg.Title,
		arg.OwnerID,
		arg.ConnectorID,
	)
	return err
}

const upsertConnectorCredentials = `-- name: UpsertConnectorCredentials :one

INSERT INTO owner_connectors (
    owner_id, connector_id, category, kind, credentials_enc
)
VALUES (
    $1, $2, $3,
    $4, $5::bytea
)
ON CONFLICT (owner_id, connector_id) DO UPDATE
SET credentials_enc = EXCLUDED.credentials_enc,
    category = EXCLUDED.category,
    kind = EXCLUDED.kind,
    connected_at = CASE
        WHEN $6::boolean THEN NULL
        ELSE owner_connectors.connected_at
    END,
    updated_at = now()
RETURNING id, owner_id, connector_id, category, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, spec, binding, auth_scheme, protocol, expose_as_agent_tools, title, created_at, updated_at
`

type UpsertConnectorCredentialsParams struct {
	OwnerID        pgtype.UUID
	ConnectorID    string
	Category       string
	Kind           string
	CredentialsEnc []byte
	ResetConnected bool
}

// owner_connectors.sql —— #155 统一连接器连接状态的读写（归一：任意 kind/品类一张表）。
// 存/覆盖一个连接器的凭据（owner 填的 app creds / apiKey / smtp config）。category/kind 随
// 首次写入定。
//
// connected_at 由 `reset_connected` 决定，**而不是无条件清掉**（F-C-30）：
// §三 D-5 要的是「改身份/凭据必须重新验证」—— 那是「**改了**」才该触发的规则。而面板点
// Connect 的第一件事就是 POST /credentials，于是「已连接」在授权还没开始之前就没了；owner
// 只要打开卡片重存一次（值一个字都没动），一条好端端的连接就显示成「没连」，而 token 还活着。
// 调用方比对合并后的凭据跟原值：真的变了才传 true。
func (q *Queries) UpsertConnectorCredentials(ctx context.Context, arg UpsertConnectorCredentialsParams) (OwnerConnector, error) {
	row := q.db.QueryRow(ctx, upsertConnectorCredentials,
		arg.OwnerID,
		arg.ConnectorID,
		arg.Category,
		arg.Kind,
		arg.CredentialsEnc,
		arg.ResetConnected,
	)
	var i OwnerConnector
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConnectorID,
		&i.Category,
		&i.Kind,
		&i.CredentialsEnc,
		&i.TokenEnc,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.ConnectedAt,
		&i.Active,
		&i.Spec,
		&i.Binding,
		&i.AuthScheme,
		&i.Protocol,
		&i.ExposeAsAgentTools,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
