// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: assets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAssetReferences = `-- name: CountAssetReferences :one
SELECT count(*) FROM asset_references
WHERE asset_id = $1
`

func (q *Queries) CountAssetReferences(ctx context.Context, assetID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAssetReferences, assetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :one

INSERT INTO assets (id, owner_id, holder_id, storage_key, content_type, size_bytes, sha256, original_filename, kind)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, owner_id, holder_id, kind, storage_key, content_type, size_bytes, sha256, original_filename, created_at
`

type CreateAssetParams struct {
	ID               pgtype.UUID
	OwnerID          pgtype.UUID
	HolderID         pgtype.UUID
	StorageKey       string
	ContentType      string
	SizeBytes        int64
	Sha256           string
	OriginalFilename string
	Kind             string
}

// Global asset pool + references (docs/design/global-assets.md).
// An asset belongs to an owner; corpus entries / microsites reference it via
// asset_references. A referenced asset can't be deleted — the referrer goes first.
func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.ID,
		arg.OwnerID,
		arg.HolderID,
		arg.StorageKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Sha256,
		arg.OriginalFilename,
		arg.Kind,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.HolderID,
		&i.Kind,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.OriginalFilename,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAssetByID = `-- name: DeleteAssetByID :one
DELETE FROM assets
WHERE id = $1 AND owner_id = $2
RETURNING storage_key
`

type DeleteAssetByIDParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

// Pool delete of a single asset the caller has already confirmed is unreferenced
// (see CountAssetReferences). Scoped to owner. Returns storage_key so the caller
// drops the MinIO blob afterward.
func (q *Queries) DeleteAssetByID(ctx context.Context, arg DeleteAssetByIDParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteAssetByID, arg.ID, arg.OwnerID)
	var storage_key string
	err := row.Scan(&storage_key)
	return storage_key, err
}

const deleteAssetReference = `-- name: DeleteAssetReference :exec
DELETE FROM asset_references
WHERE asset_id = $1 AND referrer_kind = $2 AND referrer_id = $3
`

type DeleteAssetReferenceParams struct {
	AssetID      pgtype.UUID
	ReferrerKind string
	ReferrerID   pgtype.UUID
}

// Drop one specific reference (a note stops using one image; assets survive).
func (q *Queries) DeleteAssetReference(ctx context.Context, arg DeleteAssetReferenceParams) error {
	_, err := q.db.Exec(ctx, deleteAssetReference, arg.AssetID, arg.ReferrerKind, arg.ReferrerID)
	return err
}

const deleteAssetReferencesByReferrer = `-- name: DeleteAssetReferencesByReferrer :exec
DELETE FROM asset_references
WHERE referrer_kind = $1 AND referrer_id = $2
`

type DeleteAssetReferencesByReferrerParams struct {
	ReferrerKind string
	ReferrerID   pgtype.UUID
}

// Drop every reference a single referrer holds — on referrer delete, and as the
// first half of a rewrite. Assets survive in the pool.
func (q *Queries) DeleteAssetReferencesByReferrer(ctx context.Context, arg DeleteAssetReferencesByReferrerParams) error {
	_, err := q.db.Exec(ctx, deleteAssetReferencesByReferrer, arg.ReferrerKind, arg.ReferrerID)
	return err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, owner_id, holder_id, kind, storage_key, content_type, size_bytes, sha256, original_filename, created_at FROM assets
WHERE id = $1
`

func (q *Queries) GetAssetByID(ctx context.Context, id pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.HolderID,
		&i.Kind,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.OriginalFilename,
		&i.CreatedAt,
	)
	return i, err
}

const insertAssetReference = `-- name: InsertAssetReference :exec

INSERT INTO asset_references (asset_id, referrer_kind, referrer_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertAssetReferenceParams struct {
	AssetID      pgtype.UUID
	ReferrerKind string
	ReferrerID   pgtype.UUID
}

// ── references ────────────────────────────────────────────────────────────────
func (q *Queries) InsertAssetReference(ctx context.Context, arg InsertAssetReferenceParams) error {
	_, err := q.db.Exec(ctx, insertAssetReference, arg.AssetID, arg.ReferrerKind, arg.ReferrerID)
	return err
}

const listAssetReferencesByAsset = `-- name: ListAssetReferencesByAsset :many
SELECT referrer_kind, referrer_id
FROM asset_references
WHERE asset_id = $1
ORDER BY referrer_kind, referrer_id
`

type ListAssetReferencesByAssetRow struct {
	ReferrerKind string
	ReferrerID   pgtype.UUID
}

// Who references this asset — feeds the delete-guard's "used by …" message.
func (q *Queries) ListAssetReferencesByAsset(ctx context.Context, assetID pgtype.UUID) ([]ListAssetReferencesByAssetRow, error) {
	rows, err := q.db.Query(ctx, listAssetReferencesByAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetReferencesByAssetRow
	for rows.Next() {
		var i ListAssetReferencesByAssetRow
		if err := rows.Scan(&i.ReferrerKind, &i.ReferrerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsByOwner = `-- name: ListAssetsByOwner :many
SELECT id, owner_id, holder_id, kind, storage_key, content_type, size_bytes, sha256, original_filename, created_at FROM assets
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAssetsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.HolderID,
			&i.Kind,
			&i.StorageKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
			&i.OriginalFilename,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsByReferrer = `-- name: ListAssetsByReferrer :many
SELECT a.id, a.owner_id, a.holder_id, a.kind, a.storage_key, a.content_type, a.size_bytes, a.sha256, a.original_filename, a.created_at FROM assets a
JOIN asset_references r ON r.asset_id = a.id
WHERE r.referrer_kind = $1 AND r.referrer_id = $2
ORDER BY a.created_at
`

type ListAssetsByReferrerParams struct {
	ReferrerKind string
	ReferrerID   pgtype.UUID
}

// The assets one referrer (a note / microsite) references — the "files on this
// entry" view, now expressed as references rather than holder ownership.
func (q *Queries) ListAssetsByReferrer(ctx context.Context, arg ListAssetsByReferrerParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsByReferrer, arg.ReferrerKind, arg.ReferrerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.HolderID,
			&i.Kind,
			&i.StorageKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
			&i.OriginalFilename,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
