// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: assets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (id, holder_id, storage_key, content_type, size_bytes, sha256, original_filename)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, holder_id, storage_key, content_type, size_bytes, sha256, original_filename, created_at
`

type CreateAssetParams struct {
	ID               pgtype.UUID
	HolderID         pgtype.UUID
	StorageKey       string
	ContentType      string
	SizeBytes        int64
	Sha256           string
	OriginalFilename string
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.ID,
		arg.HolderID,
		arg.StorageKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Sha256,
		arg.OriginalFilename,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.HolderID,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.OriginalFilename,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAssetsByHolder = `-- name: DeleteAssetsByHolder :many
DELETE FROM assets
WHERE holder_id = $1
RETURNING storage_key
`

// 删一个 holder 的所有 asset 行；返 storage_key 让 caller 后置批删 MinIO blob。
func (q *Queries) DeleteAssetsByHolder(ctx context.Context, holderID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteAssetsByHolder, holderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAssetsByIDs = `-- name: DeleteAssetsByIDs :many
DELETE FROM assets
WHERE id = ANY($1::uuid[])
RETURNING storage_key
`

// 按 id 集合删；caller 已经知道这些 id 是同一个 holder 的（update 时算
// removed = old_refs - new_refs）。返 storage_key 让 caller 删 blob。
func (q *Queries) DeleteAssetsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteAssetsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, holder_id, storage_key, content_type, size_bytes, sha256, original_filename, created_at
FROM assets
WHERE id = $1
`

func (q *Queries) GetAssetByID(ctx context.Context, id pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.HolderID,
		&i.StorageKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.OriginalFilename,
		&i.CreatedAt,
	)
	return i, err
}

const listAssetsByHolder = `-- name: ListAssetsByHolder :many
SELECT id, holder_id, storage_key, content_type, size_bytes, sha256, original_filename, created_at
FROM assets
WHERE holder_id = $1
`

func (q *Queries) ListAssetsByHolder(ctx context.Context, holderID pgtype.UUID) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsByHolder, holderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.HolderID,
			&i.StorageKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
			&i.OriginalFilename,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
