// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: corpus.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRawEntry = `-- name: CreateRawEntry :one

INSERT INTO corpus_notes (owner_id, genre, title, body, inbox_source, inbox_meta, tags, flagged_private)
VALUES ($1, 'raw', $2, $3, $4, $5, $6, $7)
RETURNING id, owner_id, genre, parent_id, title, body, tags, aliases, source_ids, show_as_source, excerpt, published, css_classes, lang, lang_labels, obsidian_source_path, obsidian_imported_at, obsidian_frontmatter, inbox_source, inbox_meta, flagged_private, archived, promoted_to, slug, visibility, locked_body, cover_headline, cover_hue, cover_image_asset_id, read_minutes, cross_refs, published_at, created_at, updated_at
`

type CreateRawEntryParams struct {
	OwnerID        pgtype.UUID
	Title          string
	Body           string
	InboxSource    string
	InboxMeta      []byte
	Tags           []string
	FlaggedPrivate bool
}

// corpus.sql —— raw inbox 的 query。raw 已折进统一 corpus_notes 基座（genre='raw'，#151），
// 不再是独立表。inbox 专属字段（inbox_source / inbox_meta / flagged_private / archived /
// promoted_to）只对 genre='raw' 有意义。列映射:body→body, source→inbox_source,
// source_meta→inbox_meta, tags→tags。title NOT NULL,每条 INSERT 必给。
// MCP raw_dump: title 由 caller 从 body 派生(首行 <=60 char,fallback "untitled")。
func (q *Queries) CreateRawEntry(ctx context.Context, arg CreateRawEntryParams) (CorpusNote, error) {
	row := q.db.QueryRow(ctx, createRawEntry,
		arg.OwnerID,
		arg.Title,
		arg.Body,
		arg.InboxSource,
		arg.InboxMeta,
		arg.Tags,
		arg.FlaggedPrivate,
	)
	var i CorpusNote
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Genre,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.Aliases,
		&i.SourceIds,
		&i.ShowAsSource,
		&i.Excerpt,
		&i.Published,
		&i.CssClasses,
		&i.Lang,
		&i.LangLabels,
		&i.ObsidianSourcePath,
		&i.ObsidianImportedAt,
		&i.ObsidianFrontmatter,
		&i.InboxSource,
		&i.InboxMeta,
		&i.FlaggedPrivate,
		&i.Archived,
		&i.PromotedTo,
		&i.Slug,
		&i.Visibility,
		&i.LockedBody,
		&i.CoverHeadline,
		&i.CoverHue,
		&i.CoverImageAssetID,
		&i.ReadMinutes,
		&i.CrossRefs,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRawByID = `-- name: GetRawByID :one
SELECT id, owner_id, genre, parent_id, title, body, tags, aliases, source_ids, show_as_source, excerpt, published, css_classes, lang, lang_labels, obsidian_source_path, obsidian_imported_at, obsidian_frontmatter, inbox_source, inbox_meta, flagged_private, archived, promoted_to, slug, visibility, locked_body, cover_headline, cover_hue, cover_image_asset_id, read_minutes, cross_refs, published_at, created_at, updated_at FROM corpus_notes WHERE id = $1 AND owner_id = $2 AND genre = 'raw'
`

type GetRawByIDParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetRawByID(ctx context.Context, arg GetRawByIDParams) (CorpusNote, error) {
	row := q.db.QueryRow(ctx, getRawByID, arg.ID, arg.OwnerID)
	var i CorpusNote
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Genre,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.Aliases,
		&i.SourceIds,
		&i.ShowAsSource,
		&i.Excerpt,
		&i.Published,
		&i.CssClasses,
		&i.Lang,
		&i.LangLabels,
		&i.ObsidianSourcePath,
		&i.ObsidianImportedAt,
		&i.ObsidianFrontmatter,
		&i.InboxSource,
		&i.InboxMeta,
		&i.FlaggedPrivate,
		&i.Archived,
		&i.PromotedTo,
		&i.Slug,
		&i.Visibility,
		&i.LockedBody,
		&i.CoverHeadline,
		&i.CoverHue,
		&i.CoverImageAssetID,
		&i.ReadMinutes,
		&i.CrossRefs,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRawByOwner = `-- name: ListRawByOwner :many
SELECT id, owner_id, genre, parent_id, title, body, tags, aliases, source_ids, show_as_source, excerpt, published, css_classes, lang, lang_labels, obsidian_source_path, obsidian_imported_at, obsidian_frontmatter, inbox_source, inbox_meta, flagged_private, archived, promoted_to, slug, visibility, locked_body, cover_headline, cover_hue, cover_image_asset_id, read_minutes, cross_refs, published_at, created_at, updated_at FROM corpus_notes
WHERE owner_id = $1 AND genre = 'raw' AND archived = false
ORDER BY created_at DESC
LIMIT $2
`

type ListRawByOwnerParams struct {
	OwnerID pgtype.UUID
	Limit   int32
}

// archived 这一列不再有写者:raw 的删跟 wiki / output 一样是真删(见 RawRepo.Delete)。
// 过滤留着,是因为老库里可能还有当年归档下来的行 —— 它们当时就已经从每个列表消失了,
// 现在也不该突然冒出来。
func (q *Queries) ListRawByOwner(ctx context.Context, arg ListRawByOwnerParams) ([]CorpusNote, error) {
	rows, err := q.db.Query(ctx, listRawByOwner, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CorpusNote
	for rows.Next() {
		var i CorpusNote
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Genre,
			&i.ParentID,
			&i.Title,
			&i.Body,
			&i.Tags,
			&i.Aliases,
			&i.SourceIds,
			&i.ShowAsSource,
			&i.Excerpt,
			&i.Published,
			&i.CssClasses,
			&i.Lang,
			&i.LangLabels,
			&i.ObsidianSourcePath,
			&i.ObsidianImportedAt,
			&i.ObsidianFrontmatter,
			&i.InboxSource,
			&i.InboxMeta,
			&i.FlaggedPrivate,
			&i.Archived,
			&i.PromotedTo,
			&i.Slug,
			&i.Visibility,
			&i.LockedBody,
			&i.CoverHeadline,
			&i.CoverHue,
			&i.CoverImageAssetID,
			&i.ReadMinutes,
			&i.CrossRefs,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRawPromoted = `-- name: MarkRawPromoted :exec
UPDATE corpus_notes SET promoted_to = $3 WHERE id = $1 AND owner_id = $2 AND genre = 'raw'
`

type MarkRawPromotedParams struct {
	ID         pgtype.UUID
	OwnerID    pgtype.UUID
	PromotedTo pgtype.UUID
}

func (q *Queries) MarkRawPromoted(ctx context.Context, arg MarkRawPromotedParams) error {
	_, err := q.db.Exec(ctx, markRawPromoted, arg.ID, arg.OwnerID, arg.PromotedTo)
	return err
}

const setRawTags = `-- name: SetRawTags :exec
UPDATE corpus_notes SET tags = $3 WHERE id = $1 AND owner_id = $2 AND genre = 'raw'
`

type SetRawTagsParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
	Tags    []string
}

func (q *Queries) SetRawTags(ctx context.Context, arg SetRawTagsParams) error {
	_, err := q.db.Exec(ctx, setRawTags, arg.ID, arg.OwnerID, arg.Tags)
	return err
}

const updateRawBody = `-- name: UpdateRawBody :one
UPDATE corpus_notes
SET body = $3, tags = $4, flagged_private = $5
WHERE id = $1 AND owner_id = $2 AND genre = 'raw'
RETURNING id, owner_id, genre, parent_id, title, body, tags, aliases, source_ids, show_as_source, excerpt, published, css_classes, lang, lang_labels, obsidian_source_path, obsidian_imported_at, obsidian_frontmatter, inbox_source, inbox_meta, flagged_private, archived, promoted_to, slug, visibility, locked_body, cover_headline, cover_hue, cover_image_asset_id, read_minutes, cross_refs, published_at, created_at, updated_at
`

type UpdateRawBodyParams struct {
	ID             pgtype.UUID
	OwnerID        pgtype.UUID
	Body           string
	Tags           []string
	FlaggedPrivate bool
}

// admin "edit raw" 入口：改 body + tags + flagged_private。inbox_source 不动
// （inbox_source 是 ingest 来源标签，编辑不该改）。
func (q *Queries) UpdateRawBody(ctx context.Context, arg UpdateRawBodyParams) (CorpusNote, error) {
	row := q.db.QueryRow(ctx, updateRawBody,
		arg.ID,
		arg.OwnerID,
		arg.Body,
		arg.Tags,
		arg.FlaggedPrivate,
	)
	var i CorpusNote
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Genre,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.Aliases,
		&i.SourceIds,
		&i.ShowAsSource,
		&i.Excerpt,
		&i.Published,
		&i.CssClasses,
		&i.Lang,
		&i.LangLabels,
		&i.ObsidianSourcePath,
		&i.ObsidianImportedAt,
		&i.ObsidianFrontmatter,
		&i.InboxSource,
		&i.InboxMeta,
		&i.FlaggedPrivate,
		&i.Archived,
		&i.PromotedTo,
		&i.Slug,
		&i.Visibility,
		&i.LockedBody,
		&i.CoverHeadline,
		&i.CoverHue,
		&i.CoverImageAssetID,
		&i.ReadMinutes,
		&i.CrossRefs,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
