// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: access_codes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachCodeCorpusDenial = `-- name: AttachCodeCorpusDenial :exec
INSERT INTO code_corpus_denials (code_id, uri_pattern)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AttachCodeCorpusDenialParams struct {
	CodeID     pgtype.UUID
	UriPattern string
}

func (q *Queries) AttachCodeCorpusDenial(ctx context.Context, arg AttachCodeCorpusDenialParams) error {
	_, err := q.db.Exec(ctx, attachCodeCorpusDenial, arg.CodeID, arg.UriPattern)
	return err
}

const attachCodeWaypoint = `-- name: AttachCodeWaypoint :exec
INSERT INTO code_waypoints (code_id, waypoint_id, description, weight, evidence_refs, is_terminal)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (code_id, waypoint_id) DO NOTHING
`

type AttachCodeWaypointParams struct {
	CodeID       pgtype.UUID
	WaypointID   string
	Description  string
	Weight       int32
	EvidenceRefs []byte
	IsTerminal   bool
}

// 逐条 insert(数量少 + evidence_refs 是 per-row jsonb),同 AttachRoleWaypoint。
func (q *Queries) AttachCodeWaypoint(ctx context.Context, arg AttachCodeWaypointParams) error {
	_, err := q.db.Exec(ctx, attachCodeWaypoint,
		arg.CodeID,
		arg.WaypointID,
		arg.Description,
		arg.Weight,
		arg.EvidenceRefs,
		arg.IsTerminal,
	)
	return err
}

const clearCodeCorpusDenials = `-- name: ClearCodeCorpusDenials :exec
DELETE FROM code_corpus_denials WHERE code_id = $1
`

func (q *Queries) ClearCodeCorpusDenials(ctx context.Context, codeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearCodeCorpusDenials, codeID)
	return err
}

const clearCodeWaypoints = `-- name: ClearCodeWaypoints :exec
DELETE FROM code_waypoints WHERE code_id = $1
`

func (q *Queries) ClearCodeWaypoints(ctx context.Context, codeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearCodeWaypoints, codeID)
	return err
}

const countCodeMembers = `-- name: CountCodeMembers :one
SELECT count(*) FROM code_members WHERE code_id = $1
`

// max_members 强制用:这张码已经有几个不同名字(member)。
func (q *Queries) CountCodeMembers(ctx context.Context, codeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCodeMembers, codeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccessCode = `-- name: CreateAccessCode :one
INSERT INTO access_codes (
    owner_id, code, label, purpose, ghosts,
    expires_at, max_turns_per_session,
    assumed_role_id, max_members, prompt_id, inline_prompt
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, owner_id, code, label, purpose, ghosts, expires_at, status, max_turns_per_session, max_members, require_ghost_evidence, created_at, assumed_role_id, prompt_id, inline_prompt
`

type CreateAccessCodeParams struct {
	OwnerID            pgtype.UUID
	Code               string
	Label              string
	Purpose            string
	Ghosts             []byte
	ExpiresAt          pgtype.Timestamptz
	MaxTurnsPerSession *int32
	AssumedRoleID      pgtype.UUID
	MaxMembers         *int32
	PromptID           pgtype.UUID
	InlinePrompt       string
}

// A.3-IAM-5：每张码必挂 assumed_role_id。corpus_permissions / granted_skills
// 等 legacy 字段在 commit 5 drop，ACL / capability gating 全部从 role 推断。
func (q *Queries) CreateAccessCode(ctx context.Context, arg CreateAccessCodeParams) (AccessCode, error) {
	row := q.db.QueryRow(ctx, createAccessCode,
		arg.OwnerID,
		arg.Code,
		arg.Label,
		arg.Purpose,
		arg.Ghosts,
		arg.ExpiresAt,
		arg.MaxTurnsPerSession,
		arg.AssumedRoleID,
		arg.MaxMembers,
		arg.PromptID,
		arg.InlinePrompt,
	)
	var i AccessCode
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.Label,
		&i.Purpose,
		&i.Ghosts,
		&i.ExpiresAt,
		&i.Status,
		&i.MaxTurnsPerSession,
		&i.MaxMembers,
		&i.RequireGhostEvidence,
		&i.CreatedAt,
		&i.AssumedRoleID,
		&i.PromptID,
		&i.InlinePrompt,
	)
	return i, err
}

const createCodeMember = `-- name: CreateCodeMember :one
INSERT INTO code_members (code_id, display_name, email, is_anonymous)
VALUES ($1, $2, $3, $4)
RETURNING id, code_id, display_name, email, is_anonymous, last_seen_at
`

type CreateCodeMemberParams struct {
	CodeID      pgtype.UUID
	DisplayName string
	Email       *string
	IsAnonymous bool
}

func (q *Queries) CreateCodeMember(ctx context.Context, arg CreateCodeMemberParams) (CodeMember, error) {
	row := q.db.QueryRow(ctx, createCodeMember,
		arg.CodeID,
		arg.DisplayName,
		arg.Email,
		arg.IsAnonymous,
	)
	var i CodeMember
	err := row.Scan(
		&i.ID,
		&i.CodeID,
		&i.DisplayName,
		&i.Email,
		&i.IsAnonymous,
		&i.LastSeenAt,
	)
	return i, err
}

const getAccessCode = `-- name: GetAccessCode :one
SELECT id, owner_id, code, label, purpose, ghosts, expires_at, status, max_turns_per_session, max_members, require_ghost_evidence, created_at, assumed_role_id, prompt_id, inline_prompt FROM access_codes WHERE code = $1 AND status = 'active'
`

func (q *Queries) GetAccessCode(ctx context.Context, code string) (AccessCode, error) {
	row := q.db.QueryRow(ctx, getAccessCode, code)
	var i AccessCode
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.Label,
		&i.Purpose,
		&i.Ghosts,
		&i.ExpiresAt,
		&i.Status,
		&i.MaxTurnsPerSession,
		&i.MaxMembers,
		&i.RequireGhostEvidence,
		&i.CreatedAt,
		&i.AssumedRoleID,
		&i.PromptID,
		&i.InlinePrompt,
	)
	return i, err
}

const getAccessCodeByID = `-- name: GetAccessCodeByID :one
SELECT id, owner_id, code, label, purpose, ghosts, expires_at, status, max_turns_per_session, max_members, require_ghost_evidence, created_at, assumed_role_id, prompt_id, inline_prompt FROM access_codes WHERE id = $1
`

func (q *Queries) GetAccessCodeByID(ctx context.Context, id pgtype.UUID) (AccessCode, error) {
	row := q.db.QueryRow(ctx, getAccessCodeByID, id)
	var i AccessCode
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.Label,
		&i.Purpose,
		&i.Ghosts,
		&i.ExpiresAt,
		&i.Status,
		&i.MaxTurnsPerSession,
		&i.MaxMembers,
		&i.RequireGhostEvidence,
		&i.CreatedAt,
		&i.AssumedRoleID,
		&i.PromptID,
		&i.InlinePrompt,
	)
	return i, err
}

const getCodeMemberByID = `-- name: GetCodeMemberByID :one
SELECT id, code_id, display_name, email, is_anonymous, last_seen_at FROM code_members WHERE id = $1 AND code_id = $2
`

type GetCodeMemberByIDParams struct {
	ID     pgtype.UUID
	CodeID pgtype.UUID
}

// 按 member id 取(client 存了 member_id,再来时凭 id 续会;尤其匿名者)。
// 限定 code_id 防跨码串。
func (q *Queries) GetCodeMemberByID(ctx context.Context, arg GetCodeMemberByIDParams) (CodeMember, error) {
	row := q.db.QueryRow(ctx, getCodeMemberByID, arg.ID, arg.CodeID)
	var i CodeMember
	err := row.Scan(
		&i.ID,
		&i.CodeID,
		&i.DisplayName,
		&i.Email,
		&i.IsAnonymous,
		&i.LastSeenAt,
	)
	return i, err
}

const getCodeMemberByName = `-- name: GetCodeMemberByName :one
SELECT id, code_id, display_name, email, is_anonymous, last_seen_at FROM code_members WHERE code_id = $1 AND display_name = $2
`

type GetCodeMemberByNameParams struct {
	CodeID      pgtype.UUID
	DisplayName string
}

func (q *Queries) GetCodeMemberByName(ctx context.Context, arg GetCodeMemberByNameParams) (CodeMember, error) {
	row := q.db.QueryRow(ctx, getCodeMemberByName, arg.CodeID, arg.DisplayName)
	var i CodeMember
	err := row.Scan(
		&i.ID,
		&i.CodeID,
		&i.DisplayName,
		&i.Email,
		&i.IsAnonymous,
		&i.LastSeenAt,
	)
	return i, err
}

const getOrCreateCodeMember = `-- name: GetOrCreateCodeMember :one
INSERT INTO code_members (code_id, display_name, email, is_anonymous)
VALUES ($1, $2, $3, $4)
ON CONFLICT (code_id, display_name) DO UPDATE SET last_seen_at = now()
RETURNING id, code_id, display_name, email, is_anonymous, last_seen_at
`

type GetOrCreateCodeMemberParams struct {
	CodeID      pgtype.UUID
	DisplayName string
	Email       *string
	IsAnonymous bool
}

func (q *Queries) GetOrCreateCodeMember(ctx context.Context, arg GetOrCreateCodeMemberParams) (CodeMember, error) {
	row := q.db.QueryRow(ctx, getOrCreateCodeMember,
		arg.CodeID,
		arg.DisplayName,
		arg.Email,
		arg.IsAnonymous,
	)
	var i CodeMember
	err := row.Scan(
		&i.ID,
		&i.CodeID,
		&i.DisplayName,
		&i.Email,
		&i.IsAnonymous,
		&i.LastSeenAt,
	)
	return i, err
}

const listAccessCodesByOwner = `-- name: ListAccessCodesByOwner :many
SELECT id, owner_id, code, label, purpose, ghosts, expires_at, status, max_turns_per_session, max_members, require_ghost_evidence, created_at, assumed_role_id, prompt_id, inline_prompt FROM access_codes WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAccessCodesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]AccessCode, error) {
	rows, err := q.db.Query(ctx, listAccessCodesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessCode
	for rows.Next() {
		var i AccessCode
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Code,
			&i.Label,
			&i.Purpose,
			&i.Ghosts,
			&i.ExpiresAt,
			&i.Status,
			&i.MaxTurnsPerSession,
			&i.MaxMembers,
			&i.RequireGhostEvidence,
			&i.CreatedAt,
			&i.AssumedRoleID,
			&i.PromptID,
			&i.InlinePrompt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodeCorpusDenials = `-- name: ListCodeCorpusDenials :many
SELECT uri_pattern FROM code_corpus_denials WHERE code_id = $1 ORDER BY uri_pattern ASC
`

// 这张 code 收回的 URI glob（纯减法层；role 的正列表减去它 = 本码实际可读）。
func (q *Queries) ListCodeCorpusDenials(ctx context.Context, codeID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listCodeCorpusDenials, codeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var uri_pattern string
		if err := rows.Scan(&uri_pattern); err != nil {
			return nil, err
		}
		items = append(items, uri_pattern)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodeMembers = `-- name: ListCodeMembers :many
SELECT id, code_id, display_name, email, is_anonymous, last_seen_at FROM code_members WHERE code_id = $1 ORDER BY last_seen_at DESC NULLS LAST
`

func (q *Queries) ListCodeMembers(ctx context.Context, codeID pgtype.UUID) ([]CodeMember, error) {
	rows, err := q.db.Query(ctx, listCodeMembers, codeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodeMember
	for rows.Next() {
		var i CodeMember
		if err := rows.Scan(
			&i.ID,
			&i.CodeID,
			&i.DisplayName,
			&i.Email,
			&i.IsAnonymous,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodeWaypoints = `-- name: ListCodeWaypoints :many
SELECT waypoint_id, description, weight, evidence_refs, is_terminal
FROM code_waypoints WHERE code_id = $1 ORDER BY weight DESC, waypoint_id ASC
`

type ListCodeWaypointsRow struct {
	WaypointID   string
	Description  string
	Weight       int32
	EvidenceRefs []byte
	IsTerminal   bool
}

// 这张 code 的 waypoint **覆盖层**(不含继承来的 role 的);合并在 domain.MergeWaypoints。
func (q *Queries) ListCodeWaypoints(ctx context.Context, codeID pgtype.UUID) ([]ListCodeWaypointsRow, error) {
	rows, err := q.db.Query(ctx, listCodeWaypoints, codeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCodeWaypointsRow
	for rows.Next() {
		var i ListCodeWaypointsRow
		if err := rows.Scan(
			&i.WaypointID,
			&i.Description,
			&i.Weight,
			&i.EvidenceRefs,
			&i.IsTerminal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAccessCode = `-- name: RevokeAccessCode :exec
UPDATE access_codes SET status = 'revoked' WHERE id = $1 AND owner_id = $2
`

type RevokeAccessCodeParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) RevokeAccessCode(ctx context.Context, arg RevokeAccessCodeParams) error {
	_, err := q.db.Exec(ctx, revokeAccessCode, arg.ID, arg.OwnerID)
	return err
}

const setAccessCodeGhostEvidence = `-- name: SetAccessCodeGhostEvidence :one
UPDATE access_codes
SET require_ghost_evidence = $3
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, code, label, purpose, ghosts, expires_at, status, max_turns_per_session, max_members, require_ghost_evidence, created_at, assumed_role_id, prompt_id, inline_prompt
`

type SetAccessCodeGhostEvidenceParams struct {
	ID                   pgtype.UUID
	OwnerID              pgtype.UUID
	RequireGhostEvidence *bool
}

// F-A-10 per-code 覆盖:NULL = 继承 role 的开关;true/false = 这张码显式覆盖。
func (q *Queries) SetAccessCodeGhostEvidence(ctx context.Context, arg SetAccessCodeGhostEvidenceParams) (AccessCode, error) {
	row := q.db.QueryRow(ctx, setAccessCodeGhostEvidence, arg.ID, arg.OwnerID, arg.RequireGhostEvidence)
	var i AccessCode
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.Label,
		&i.Purpose,
		&i.Ghosts,
		&i.ExpiresAt,
		&i.Status,
		&i.MaxTurnsPerSession,
		&i.MaxMembers,
		&i.RequireGhostEvidence,
		&i.CreatedAt,
		&i.AssumedRoleID,
		&i.PromptID,
		&i.InlinePrompt,
	)
	return i, err
}

const touchCodeMember = `-- name: TouchCodeMember :exec
UPDATE code_members SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchCodeMember(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchCodeMember, id)
	return err
}

const updateAccessCodeQuotas = `-- name: UpdateAccessCodeQuotas :one
UPDATE access_codes
SET max_turns_per_session = $3, max_members = $4
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, code, label, purpose, ghosts, expires_at, status, max_turns_per_session, max_members, require_ghost_evidence, created_at, assumed_role_id, prompt_id, inline_prompt
`

type UpdateAccessCodeQuotasParams struct {
	ID                 pgtype.UUID
	OwnerID            pgtype.UUID
	MaxTurnsPerSession *int32
	MaxMembers         *int32
}

func (q *Queries) UpdateAccessCodeQuotas(ctx context.Context, arg UpdateAccessCodeQuotasParams) (AccessCode, error) {
	row := q.db.QueryRow(ctx, updateAccessCodeQuotas,
		arg.ID,
		arg.OwnerID,
		arg.MaxTurnsPerSession,
		arg.MaxMembers,
	)
	var i AccessCode
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.Label,
		&i.Purpose,
		&i.Ghosts,
		&i.ExpiresAt,
		&i.Status,
		&i.MaxTurnsPerSession,
		&i.MaxMembers,
		&i.RequireGhostEvidence,
		&i.CreatedAt,
		&i.AssumedRoleID,
		&i.PromptID,
		&i.InlinePrompt,
	)
	return i, err
}

const updateAccessCodeRole = `-- name: UpdateAccessCodeRole :one
UPDATE access_codes
SET assumed_role_id = $3
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, code, label, purpose, ghosts, expires_at, status, max_turns_per_session, max_members, require_ghost_evidence, created_at, assumed_role_id, prompt_id, inline_prompt
`

type UpdateAccessCodeRoleParams struct {
	ID            pgtype.UUID
	OwnerID       pgtype.UUID
	AssumedRoleID pgtype.UUID
}

// Admin "reassign role"。新 role 必须属于同 owner（caller 校验过）。
func (q *Queries) UpdateAccessCodeRole(ctx context.Context, arg UpdateAccessCodeRoleParams) (AccessCode, error) {
	row := q.db.QueryRow(ctx, updateAccessCodeRole, arg.ID, arg.OwnerID, arg.AssumedRoleID)
	var i AccessCode
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.Label,
		&i.Purpose,
		&i.Ghosts,
		&i.ExpiresAt,
		&i.Status,
		&i.MaxTurnsPerSession,
		&i.MaxMembers,
		&i.RequireGhostEvidence,
		&i.CreatedAt,
		&i.AssumedRoleID,
		&i.PromptID,
		&i.InlinePrompt,
	)
	return i, err
}
