// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: access_requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessRequest = `-- name: CreateAccessRequest :one
INSERT INTO access_requests (owner_id, name, org, email, message)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, name, org, email, message, status, created_at, mail_job_id
`

type CreateAccessRequestParams struct {
	OwnerID pgtype.UUID
	Name    string
	Org     string
	Email   string
	Message string
}

type CreateAccessRequestRow struct {
	ID        pgtype.UUID
	OwnerID   pgtype.UUID
	Name      string
	Org       string
	Email     string
	Message   string
	Status    string
	CreatedAt pgtype.Timestamptz
	MailJobID *int64
}

func (q *Queries) CreateAccessRequest(ctx context.Context, arg CreateAccessRequestParams) (CreateAccessRequestRow, error) {
	row := q.db.QueryRow(ctx, createAccessRequest,
		arg.OwnerID,
		arg.Name,
		arg.Org,
		arg.Email,
		arg.Message,
	)
	var i CreateAccessRequestRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Org,
		&i.Email,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.MailJobID,
	)
	return i, err
}

const getAccessRequestByID = `-- name: GetAccessRequestByID :one
SELECT id, owner_id, name, org, email, message, status, created_at, mail_job_id FROM access_requests
WHERE id = $1 AND owner_id = $2
`

type GetAccessRequestByIDParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

type GetAccessRequestByIDRow struct {
	ID        pgtype.UUID
	OwnerID   pgtype.UUID
	Name      string
	Org       string
	Email     string
	Message   string
	Status    string
	CreatedAt pgtype.Timestamptz
	MailJobID *int64
}

func (q *Queries) GetAccessRequestByID(ctx context.Context, arg GetAccessRequestByIDParams) (GetAccessRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccessRequestByID, arg.ID, arg.OwnerID)
	var i GetAccessRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Org,
		&i.Email,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.MailJobID,
	)
	return i, err
}

const listAccessRequestsPage = `-- name: ListAccessRequestsPage :many
SELECT id, owner_id, name, org, email, message, status, created_at, mail_job_id,
  (SELECT COUNT(*) FROM access_requests a2 WHERE a2.owner_id = $1
    AND ($2::text IS NULL OR a2.status = $2))::int AS total
FROM access_requests
WHERE owner_id = $1
  AND ($2::text IS NULL OR status = $2)
  -- id: one request (the panel re-reads a row whose approval mail is still sending).
  AND ($3::uuid IS NULL OR id = $3)
  AND ($4::timestamptz IS NULL
    OR (created_at, id) < ($4, $5::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListAccessRequestsPageParams struct {
	OwnerID      pgtype.UUID
	StatusFilter *string
	OnlyID       pgtype.UUID
	AfterAt      pgtype.Timestamptz
	AfterID      pgtype.UUID
	Lim          int32
}

type ListAccessRequestsPageRow struct {
	ID        pgtype.UUID
	OwnerID   pgtype.UUID
	Name      string
	Org       string
	Email     string
	Message   string
	Status    string
	CreatedAt pgtype.Timestamptz
	MailJobID *int64
	Total     int32
}

// One page, newest first (docs/design/paging.md). It used to be a flat LIMIT 100: the 101st
// request was unreachable. total: how many match the filter on every page (evaluated once).
func (q *Queries) ListAccessRequestsPage(ctx context.Context, arg ListAccessRequestsPageParams) ([]ListAccessRequestsPageRow, error) {
	rows, err := q.db.Query(ctx, listAccessRequestsPage,
		arg.OwnerID,
		arg.StatusFilter,
		arg.OnlyID,
		arg.AfterAt,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccessRequestsPageRow
	for rows.Next() {
		var i ListAccessRequestsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Org,
			&i.Email,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.MailJobID,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccessRequestMailJob = `-- name: SetAccessRequestMailJob :execrows
UPDATE access_requests
SET mail_job_id = $3
WHERE id = $1 AND owner_id = $2
`

type SetAccessRequestMailJobParams struct {
	ID        pgtype.UUID
	OwnerID   pgtype.UUID
	MailJobID *int64
}

func (q *Queries) SetAccessRequestMailJob(ctx context.Context, arg SetAccessRequestMailJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccessRequestMailJob, arg.ID, arg.OwnerID, arg.MailJobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAccessRequestStatus = `-- name: UpdateAccessRequestStatus :one
UPDATE access_requests
SET status = $3
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, name, org, email, message, status, created_at, mail_job_id
`

type UpdateAccessRequestStatusParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
	Status  string
}

type UpdateAccessRequestStatusRow struct {
	ID        pgtype.UUID
	OwnerID   pgtype.UUID
	Name      string
	Org       string
	Email     string
	Message   string
	Status    string
	CreatedAt pgtype.Timestamptz
	MailJobID *int64
}

func (q *Queries) UpdateAccessRequestStatus(ctx context.Context, arg UpdateAccessRequestStatusParams) (UpdateAccessRequestStatusRow, error) {
	row := q.db.QueryRow(ctx, updateAccessRequestStatus, arg.ID, arg.OwnerID, arg.Status)
	var i UpdateAccessRequestStatusRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Org,
		&i.Email,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.MailJobID,
	)
	return i, err
}
