// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessRequest = `-- name: CreateAccessRequest :one
INSERT INTO access_requests (owner_id, name, org, email, message)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, name, org, email, message, status, created_at
`

type CreateAccessRequestParams struct {
	OwnerID pgtype.UUID
	Name    string
	Org     string
	Email   string
	Message string
}

func (q *Queries) CreateAccessRequest(ctx context.Context, arg CreateAccessRequestParams) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, createAccessRequest,
		arg.OwnerID,
		arg.Name,
		arg.Org,
		arg.Email,
		arg.Message,
	)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Org,
		&i.Email,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAccessRequestByID = `-- name: GetAccessRequestByID :one
SELECT id, owner_id, name, org, email, message, status, created_at FROM access_requests
WHERE id = $1 AND owner_id = $2
`

type GetAccessRequestByIDParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetAccessRequestByID(ctx context.Context, arg GetAccessRequestByIDParams) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, getAccessRequestByID, arg.ID, arg.OwnerID)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Org,
		&i.Email,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listAccessRequestsByOwner = `-- name: ListAccessRequestsByOwner :many
SELECT id, owner_id, name, org, email, message, status, created_at FROM access_requests
WHERE owner_id = $1
  AND ($2::text IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT 100
`

type ListAccessRequestsByOwnerParams struct {
	OwnerID      pgtype.UUID
	StatusFilter *string
}

func (q *Queries) ListAccessRequestsByOwner(ctx context.Context, arg ListAccessRequestsByOwnerParams) ([]AccessRequest, error) {
	rows, err := q.db.Query(ctx, listAccessRequestsByOwner, arg.OwnerID, arg.StatusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessRequest
	for rows.Next() {
		var i AccessRequest
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Org,
			&i.Email,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccessRequestStatus = `-- name: UpdateAccessRequestStatus :one
UPDATE access_requests
SET status = $3
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, name, org, email, message, status, created_at
`

type UpdateAccessRequestStatusParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
	Status  string
}

func (q *Queries) UpdateAccessRequestStatus(ctx context.Context, arg UpdateAccessRequestStatusParams) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, updateAccessRequestStatus, arg.ID, arg.OwnerID, arg.Status)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Org,
		&i.Email,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
