// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: capability_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCapabilitySettings = `-- name: ListCapabilitySettings :many
SELECT capability_id, enabled
FROM capability_settings
WHERE owner_id = $1
`

type ListCapabilitySettingsRow struct {
	CapabilityID string
	Enabled      bool
}

// 该 owner 所有显式偏好行（没行的 capability 走默认开）。
func (q *Queries) ListCapabilitySettings(ctx context.Context, ownerID pgtype.UUID) ([]ListCapabilitySettingsRow, error) {
	rows, err := q.db.Query(ctx, listCapabilitySettings, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCapabilitySettingsRow
	for rows.Next() {
		var i ListCapabilitySettingsRow
		if err := rows.Scan(&i.CapabilityID, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCapabilitySetting = `-- name: UpsertCapabilitySetting :exec
INSERT INTO capability_settings (owner_id, capability_id, enabled)
VALUES ($1, $2, $3)
ON CONFLICT (owner_id, capability_id) DO UPDATE
SET enabled = EXCLUDED.enabled,
    updated_at = now()
`

type UpsertCapabilitySettingParams struct {
	OwnerID      pgtype.UUID
	CapabilityID string
	Enabled      bool
}

// Phase H: owner 显式开/关一个 capability。(owner_id, capability_id) upsert，
// 并发 toggle 安全（PRIMARY KEY 冲突走 DO UPDATE，不留半行）。
func (q *Queries) UpsertCapabilitySetting(ctx context.Context, arg UpsertCapabilitySettingParams) error {
	_, err := q.db.Exec(ctx, upsertCapabilitySetting, arg.OwnerID, arg.CapabilityID, arg.Enabled)
	return err
}
