// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: code_denials.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCodeCapabilityDenial = `-- name: AddCodeCapabilityDenial :exec

INSERT INTO code_capability_denials (code_id, capability_id)
VALUES ($1, $2)
ON CONFLICT (code_id, capability_id) DO NOTHING
`

type AddCodeCapabilityDenialParams struct {
	CodeID       pgtype.UUID
	CapabilityID string
}

// code_denials —— ACL hierarchy 的 code 层（capability-acl-hierarchy.md）。
// 纯 deny 稀疏表：presence=deny，无 state；无行=完全继承 role。owner-scope 由
// handler 先 GetByID 校验 code 属本 owner，这里只按 code_id 读写。
// 幂等：重复 deny 同一 (code,cap) 走 PK 冲突 → 不报错、不双写。
func (q *Queries) AddCodeCapabilityDenial(ctx context.Context, arg AddCodeCapabilityDenialParams) error {
	_, err := q.db.Exec(ctx, addCodeCapabilityDenial, arg.CodeID, arg.CapabilityID)
	return err
}

const addCodeSkillDenial = `-- name: AddCodeSkillDenial :exec
INSERT INTO code_skill_denials (code_id, skill_id)
VALUES ($1, $2)
ON CONFLICT (code_id, skill_id) DO NOTHING
`

type AddCodeSkillDenialParams struct {
	CodeID  pgtype.UUID
	SkillID pgtype.UUID
}

func (q *Queries) AddCodeSkillDenial(ctx context.Context, arg AddCodeSkillDenialParams) error {
	_, err := q.db.Exec(ctx, addCodeSkillDenial, arg.CodeID, arg.SkillID)
	return err
}

const deleteCodeCapabilityDenial = `-- name: DeleteCodeCapabilityDenial :exec
DELETE FROM code_capability_denials WHERE code_id = $1 AND capability_id = $2
`

type DeleteCodeCapabilityDenialParams struct {
	CodeID       pgtype.UUID
	CapabilityID string
}

func (q *Queries) DeleteCodeCapabilityDenial(ctx context.Context, arg DeleteCodeCapabilityDenialParams) error {
	_, err := q.db.Exec(ctx, deleteCodeCapabilityDenial, arg.CodeID, arg.CapabilityID)
	return err
}

const deleteCodeSkillDenial = `-- name: DeleteCodeSkillDenial :exec
DELETE FROM code_skill_denials WHERE code_id = $1 AND skill_id = $2
`

type DeleteCodeSkillDenialParams struct {
	CodeID  pgtype.UUID
	SkillID pgtype.UUID
}

func (q *Queries) DeleteCodeSkillDenial(ctx context.Context, arg DeleteCodeSkillDenialParams) error {
	_, err := q.db.Exec(ctx, deleteCodeSkillDenial, arg.CodeID, arg.SkillID)
	return err
}

const listCodeCapabilityDenials = `-- name: ListCodeCapabilityDenials :many
SELECT capability_id FROM code_capability_denials WHERE code_id = $1
`

func (q *Queries) ListCodeCapabilityDenials(ctx context.Context, codeID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listCodeCapabilityDenials, codeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var capability_id string
		if err := rows.Scan(&capability_id); err != nil {
			return nil, err
		}
		items = append(items, capability_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodeSkillDenials = `-- name: ListCodeSkillDenials :many
SELECT skill_id FROM code_skill_denials WHERE code_id = $1
`

func (q *Queries) ListCodeSkillDenials(ctx context.Context, codeID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listCodeSkillDenials, codeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var skill_id pgtype.UUID
		if err := rows.Scan(&skill_id); err != nil {
			return nil, err
		}
		items = append(items, skill_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
