// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: embeds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmbed = `-- name: CreateEmbed :one
INSERT INTO embeds (owner_id, code_id, label, allowed_origins, key_id, public_key)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, code_id, label, allowed_origins, key_id, public_key, created_at, updated_at
`

type CreateEmbedParams struct {
	OwnerID        pgtype.UUID
	CodeID         pgtype.UUID
	Label          string
	AllowedOrigins []byte
	KeyID          pgtype.UUID
	PublicKey      *string
}

func (q *Queries) CreateEmbed(ctx context.Context, arg CreateEmbedParams) (Embed, error) {
	row := q.db.QueryRow(ctx, createEmbed,
		arg.OwnerID,
		arg.CodeID,
		arg.Label,
		arg.AllowedOrigins,
		arg.KeyID,
		arg.PublicKey,
	)
	var i Embed
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CodeID,
		&i.Label,
		&i.AllowedOrigins,
		&i.KeyID,
		&i.PublicKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmbed = `-- name: DeleteEmbed :exec
DELETE FROM embeds WHERE id = $1 AND owner_id = $2
`

type DeleteEmbedParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) DeleteEmbed(ctx context.Context, arg DeleteEmbedParams) error {
	_, err := q.db.Exec(ctx, deleteEmbed, arg.ID, arg.OwnerID)
	return err
}

const getEmbed = `-- name: GetEmbed :one
SELECT id, owner_id, code_id, label, allowed_origins, key_id, public_key, created_at, updated_at FROM embeds WHERE id = $1 AND owner_id = $2
`

type GetEmbedParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetEmbed(ctx context.Context, arg GetEmbedParams) (Embed, error) {
	row := q.db.QueryRow(ctx, getEmbed, arg.ID, arg.OwnerID)
	var i Embed
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CodeID,
		&i.Label,
		&i.AllowedOrigins,
		&i.KeyID,
		&i.PublicKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmbedAuthByKeyID = `-- name: GetEmbedAuthByKeyID :one
SELECT e.public_key, e.allowed_origins, ac.code
FROM embeds e
JOIN access_codes ac ON e.code_id = ac.id
WHERE e.key_id = $1
`

type GetEmbedAuthByKeyIDRow struct {
	PublicKey      *string
	AllowedOrigins []byte
	Code           string
}

// Used at session issuance to look up by the JWT's kid: this embed's public key (verify signature)
// + allow list (check origin) + the code it exposes (issue the session). The plaintext code is
// obtained only at this step, server-side.
func (q *Queries) GetEmbedAuthByKeyID(ctx context.Context, keyID pgtype.UUID) (GetEmbedAuthByKeyIDRow, error) {
	row := q.db.QueryRow(ctx, getEmbedAuthByKeyID, keyID)
	var i GetEmbedAuthByKeyIDRow
	err := row.Scan(&i.PublicKey, &i.AllowedOrigins, &i.Code)
	return i, err
}

const listEmbedsByOwner = `-- name: ListEmbedsByOwner :many
SELECT id, owner_id, code_id, label, allowed_origins, key_id, public_key, created_at, updated_at FROM embeds WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListEmbedsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Embed, error) {
	rows, err := q.db.Query(ctx, listEmbedsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Embed
	for rows.Next() {
		var i Embed
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.CodeID,
			&i.Label,
			&i.AllowedOrigins,
			&i.KeyID,
			&i.PublicKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmbed = `-- name: UpdateEmbed :one
UPDATE embeds
SET label = $3, allowed_origins = $4, updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, code_id, label, allowed_origins, key_id, public_key, created_at, updated_at
`

type UpdateEmbedParams struct {
	ID             pgtype.UUID
	OwnerID        pgtype.UUID
	Label          string
	AllowedOrigins []byte
}

func (q *Queries) UpdateEmbed(ctx context.Context, arg UpdateEmbedParams) (Embed, error) {
	row := q.db.QueryRow(ctx, updateEmbed,
		arg.ID,
		arg.OwnerID,
		arg.Label,
		arg.AllowedOrigins,
	)
	var i Embed
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CodeID,
		&i.Label,
		&i.AllowedOrigins,
		&i.KeyID,
		&i.PublicKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
