// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: embeds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmbed = `-- name: CreateEmbed :one
INSERT INTO embeds (owner_id, code_id, label, allowed_origins, key_id, public_key, sync_mode)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, owner_id, code_id, label, allowed_origins, key_id, public_key, sync_mode, created_at, updated_at
`

type CreateEmbedParams struct {
	OwnerID        pgtype.UUID
	CodeID         pgtype.UUID
	Label          string
	AllowedOrigins []byte
	KeyID          pgtype.UUID
	PublicKey      *string
	SyncMode       string
}

func (q *Queries) CreateEmbed(ctx context.Context, arg CreateEmbedParams) (Embed, error) {
	row := q.db.QueryRow(ctx, createEmbed,
		arg.OwnerID,
		arg.CodeID,
		arg.Label,
		arg.AllowedOrigins,
		arg.KeyID,
		arg.PublicKey,
		arg.SyncMode,
	)
	var i Embed
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CodeID,
		&i.Label,
		&i.AllowedOrigins,
		&i.KeyID,
		&i.PublicKey,
		&i.SyncMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmbed = `-- name: DeleteEmbed :exec
DELETE FROM embeds WHERE id = $1 AND owner_id = $2
`

type DeleteEmbedParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) DeleteEmbed(ctx context.Context, arg DeleteEmbedParams) error {
	_, err := q.db.Exec(ctx, deleteEmbed, arg.ID, arg.OwnerID)
	return err
}

const getEmbed = `-- name: GetEmbed :one
SELECT id, owner_id, code_id, label, allowed_origins, key_id, public_key, sync_mode, created_at, updated_at FROM embeds WHERE id = $1 AND owner_id = $2
`

type GetEmbedParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetEmbed(ctx context.Context, arg GetEmbedParams) (Embed, error) {
	row := q.db.QueryRow(ctx, getEmbed, arg.ID, arg.OwnerID)
	var i Embed
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CodeID,
		&i.Label,
		&i.AllowedOrigins,
		&i.KeyID,
		&i.PublicKey,
		&i.SyncMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmbedAuthByKeyID = `-- name: GetEmbedAuthByKeyID :one
SELECT e.public_key, e.allowed_origins, ac.code
FROM embeds e
JOIN access_codes ac ON e.code_id = ac.id
WHERE e.key_id = $1
`

type GetEmbedAuthByKeyIDRow struct {
	PublicKey      *string
	AllowedOrigins []byte
	Code           string
}

// Used at session issuance to look up by the JWT's kid: this embed's public key (verify signature)
// + allow list (check origin) + the code it exposes (issue the session). The plaintext code is
// obtained only at this step, server-side.
func (q *Queries) GetEmbedAuthByKeyID(ctx context.Context, keyID pgtype.UUID) (GetEmbedAuthByKeyIDRow, error) {
	row := q.db.QueryRow(ctx, getEmbedAuthByKeyID, keyID)
	var i GetEmbedAuthByKeyIDRow
	err := row.Scan(&i.PublicKey, &i.AllowedOrigins, &i.Code)
	return i, err
}

const getEmbedSyncModeByKeyID = `-- name: GetEmbedSyncModeByKeyID :one
SELECT sync_mode FROM embeds WHERE key_id = $1
`

// The public read a consuming site makes (GET /api/v1/embeds/{kid}); the kid is already public.
func (q *Queries) GetEmbedSyncModeByKeyID(ctx context.Context, keyID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getEmbedSyncModeByKeyID, keyID)
	var sync_mode string
	err := row.Scan(&sync_mode)
	return sync_mode, err
}

const listEmbedsPage = `-- name: ListEmbedsPage :many
SELECT e.id, e.owner_id, e.code_id, e.label, e.allowed_origins, e.key_id, e.public_key, e.sync_mode, e.created_at, e.updated_at, ac.code AS code_value
FROM embeds e
JOIN access_codes ac ON ac.id = e.code_id
WHERE e.owner_id = $1
  AND ($2::timestamptz IS NULL
    OR (e.created_at, e.id) < ($2, $3::uuid))
ORDER BY e.created_at DESC, e.id DESC
LIMIT $4
`

type ListEmbedsPageParams struct {
	OwnerID pgtype.UUID
	AfterAt pgtype.Timestamptz
	AfterID pgtype.UUID
	Lim     int32
}

type ListEmbedsPageRow struct {
	Embed     Embed
	CodeValue string
}

// One page of the owner's embeds, newest first (docs/design/paging.md), each with the code
// string it exposes: the paged codes list can no longer answer "which string is code_id X".
func (q *Queries) ListEmbedsPage(ctx context.Context, arg ListEmbedsPageParams) ([]ListEmbedsPageRow, error) {
	rows, err := q.db.Query(ctx, listEmbedsPage,
		arg.OwnerID,
		arg.AfterAt,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmbedsPageRow
	for rows.Next() {
		var i ListEmbedsPageRow
		if err := rows.Scan(
			&i.Embed.ID,
			&i.Embed.OwnerID,
			&i.Embed.CodeID,
			&i.Embed.Label,
			&i.Embed.AllowedOrigins,
			&i.Embed.KeyID,
			&i.Embed.PublicKey,
			&i.Embed.SyncMode,
			&i.Embed.CreatedAt,
			&i.Embed.UpdatedAt,
			&i.CodeValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEmbedSyncMode = `-- name: SetEmbedSyncMode :one
UPDATE embeds
SET sync_mode = $3, updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, code_id, label, allowed_origins, key_id, public_key, sync_mode, created_at, updated_at
`

type SetEmbedSyncModeParams struct {
	ID       pgtype.UUID
	OwnerID  pgtype.UUID
	SyncMode string
}

func (q *Queries) SetEmbedSyncMode(ctx context.Context, arg SetEmbedSyncModeParams) (Embed, error) {
	row := q.db.QueryRow(ctx, setEmbedSyncMode, arg.ID, arg.OwnerID, arg.SyncMode)
	var i Embed
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CodeID,
		&i.Label,
		&i.AllowedOrigins,
		&i.KeyID,
		&i.PublicKey,
		&i.SyncMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmbed = `-- name: UpdateEmbed :one
UPDATE embeds
SET label = $3, allowed_origins = $4, updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, code_id, label, allowed_origins, key_id, public_key, sync_mode, created_at, updated_at
`

type UpdateEmbedParams struct {
	ID             pgtype.UUID
	OwnerID        pgtype.UUID
	Label          string
	AllowedOrigins []byte
}

func (q *Queries) UpdateEmbed(ctx context.Context, arg UpdateEmbedParams) (Embed, error) {
	row := q.db.QueryRow(ctx, updateEmbed,
		arg.ID,
		arg.OwnerID,
		arg.Label,
		arg.AllowedOrigins,
	)
	var i Embed
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CodeID,
		&i.Label,
		&i.AllowedOrigins,
		&i.KeyID,
		&i.PublicKey,
		&i.SyncMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
