// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: posts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPosts = `-- name: CountPosts :one
SELECT count(*)::int FROM posts
WHERE owner_id = $1 AND deleted_at IS NULL
  AND ($2::bool OR post_visible(visibility, visible_role_ids, $3::text))
  AND ($4::text = '' OR visibility = $4::text)
  AND ($5::text = '' OR body ILIKE '%' || $5::text || '%'
       OR to_tsvector('simple', body) @@ websearch_to_tsquery('simple', $5::text))
`

type CountPostsParams struct {
	OwnerID    pgtype.UUID
	OwnerView  bool
	RoleID     string
	Visibility string
	Q          string
}

func (q *Queries) CountPosts(ctx context.Context, arg CountPostsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countPosts,
		arg.OwnerID,
		arg.OwnerView,
		arg.RoleID,
		arg.Visibility,
		arg.Q,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createPost = `-- name: CreatePost :one

INSERT INTO posts (owner_id, body, visibility, visible_role_ids)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, body, visibility, visible_role_ids, created_at, updated_at, deleted_at
`

type CreatePostParams struct {
	OwnerID        pgtype.UUID
	Body           string
	Visibility     string
	VisibleRoleIds []pgtype.UUID
}

// posts.sql — every query that touches the posts table (check-posts-one-reader keeps it here).
//
// A reader is (owner_view, role_id): the owner sees every post; anyone else sees what
// post_visible(visibility, visible_role_ids, role_id) admits — the one rule, in schema.sql.
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.OwnerID,
		arg.Body,
		arg.Visibility,
		arg.VisibleRoleIds,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Body,
		&i.Visibility,
		&i.VisibleRoleIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPost = `-- name: GetPost :one
SELECT id, owner_id, body, visibility, visible_role_ids, created_at, updated_at, deleted_at FROM posts
WHERE owner_id = $1 AND id = $2 AND deleted_at IS NULL
  AND ($3::bool OR post_visible(visibility, visible_role_ids, $4::text))
`

type GetPostParams struct {
	OwnerID   pgtype.UUID
	ID        pgtype.UUID
	OwnerView bool
	RoleID    string
}

func (q *Queries) GetPost(ctx context.Context, arg GetPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, getPost,
		arg.OwnerID,
		arg.ID,
		arg.OwnerView,
		arg.RoleID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Body,
		&i.Visibility,
		&i.VisibleRoleIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, owner_id, body, visibility, visible_role_ids, created_at, updated_at, deleted_at FROM posts
WHERE owner_id = $1 AND deleted_at IS NULL
  AND ($2::bool OR post_visible(visibility, visible_role_ids, $3::text))
  AND ($4::text = '' OR visibility = $4::text)
  AND ($5::text = '' OR body ILIKE '%' || $5::text || '%'
       OR to_tsvector('simple', body) @@ websearch_to_tsquery('simple', $5::text))
  AND ($6::timestamptz IS NULL
       OR (created_at, id) < ($6::timestamptz, $7::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $8
`

type ListPostsParams struct {
	OwnerID    pgtype.UUID
	OwnerView  bool
	RoleID     string
	Visibility string
	Q          string
	AfterAt    pgtype.Timestamptz
	AfterID    pgtype.UUID
	Lim        int32
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPosts,
		arg.OwnerID,
		arg.OwnerView,
		arg.RoleID,
		arg.Visibility,
		arg.Q,
		arg.AfterAt,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Body,
			&i.Visibility,
			&i.VisibleRoleIds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedPosts = `-- name: ListTrashedPosts :many
SELECT id, owner_id, body, visibility, visible_role_ids, created_at, updated_at, deleted_at FROM posts
WHERE owner_id = $1 AND deleted_at IS NOT NULL
ORDER BY deleted_at DESC, id DESC
`

func (q *Queries) ListTrashedPosts(ctx context.Context, ownerID pgtype.UUID) ([]Post, error) {
	rows, err := q.db.Query(ctx, listTrashedPosts, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Body,
			&i.Visibility,
			&i.VisibleRoleIds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgePosts = `-- name: PurgePosts :many
DELETE FROM posts WHERE deleted_at IS NOT NULL AND deleted_at < $1
RETURNING id
`

func (q *Queries) PurgePosts(ctx context.Context, deletedAt pgtype.Timestamptz) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, purgePosts, deletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePost = `-- name: RestorePost :one
UPDATE posts SET deleted_at = NULL
WHERE owner_id = $1 AND id = $2 AND deleted_at IS NOT NULL
RETURNING id, owner_id, body, visibility, visible_role_ids, created_at, updated_at, deleted_at
`

type RestorePostParams struct {
	OwnerID pgtype.UUID
	ID      pgtype.UUID
}

func (q *Queries) RestorePost(ctx context.Context, arg RestorePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, restorePost, arg.OwnerID, arg.ID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Body,
		&i.Visibility,
		&i.VisibleRoleIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const trashPost = `-- name: TrashPost :one
UPDATE posts SET deleted_at = now()
WHERE owner_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id, owner_id, body, visibility, visible_role_ids, created_at, updated_at, deleted_at
`

type TrashPostParams struct {
	OwnerID pgtype.UUID
	ID      pgtype.UUID
}

func (q *Queries) TrashPost(ctx context.Context, arg TrashPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, trashPost, arg.OwnerID, arg.ID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Body,
		&i.Visibility,
		&i.VisibleRoleIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts SET body = $3, visibility = $4, visible_role_ids = $5, updated_at = now()
WHERE owner_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id, owner_id, body, visibility, visible_role_ids, created_at, updated_at, deleted_at
`

type UpdatePostParams struct {
	OwnerID        pgtype.UUID
	ID             pgtype.UUID
	Body           string
	Visibility     string
	VisibleRoleIds []pgtype.UUID
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.OwnerID,
		arg.ID,
		arg.Body,
		arg.Visibility,
		arg.VisibleRoleIds,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Body,
		&i.Visibility,
		&i.VisibleRoleIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
