// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_codes.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessCode = `-- name: CreateAccessCode :one
INSERT INTO access_codes (owner_id, code, label, purpose, included_tags, excluded_tags, suggested_questions, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, owner_id, code, label, purpose, included_tags, excluded_tags, suggested_questions, expires_at, status, created_at
`

type CreateAccessCodeParams struct {
	OwnerID            pgtype.UUID
	Code               string
	Label              string
	Purpose            string
	IncludedTags       []string
	ExcludedTags       []string
	SuggestedQuestions []byte
	ExpiresAt          pgtype.Timestamptz
}

func (q *Queries) CreateAccessCode(ctx context.Context, arg CreateAccessCodeParams) (AccessCode, error) {
	row := q.db.QueryRow(ctx, createAccessCode,
		arg.OwnerID,
		arg.Code,
		arg.Label,
		arg.Purpose,
		arg.IncludedTags,
		arg.ExcludedTags,
		arg.SuggestedQuestions,
		arg.ExpiresAt,
	)
	var i AccessCode
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.Label,
		&i.Purpose,
		&i.IncludedTags,
		&i.ExcludedTags,
		&i.SuggestedQuestions,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createCodeMember = `-- name: CreateCodeMember :one
INSERT INTO code_members (code_id, display_name, email, is_anonymous)
VALUES ($1, $2, $3, $4)
RETURNING id, code_id, display_name, email, is_anonymous, last_seen_at
`

type CreateCodeMemberParams struct {
	CodeID      pgtype.UUID
	DisplayName string
	Email       *string
	IsAnonymous bool
}

func (q *Queries) CreateCodeMember(ctx context.Context, arg CreateCodeMemberParams) (CodeMember, error) {
	row := q.db.QueryRow(ctx, createCodeMember,
		arg.CodeID,
		arg.DisplayName,
		arg.Email,
		arg.IsAnonymous,
	)
	var i CodeMember
	err := row.Scan(
		&i.ID,
		&i.CodeID,
		&i.DisplayName,
		&i.Email,
		&i.IsAnonymous,
		&i.LastSeenAt,
	)
	return i, err
}

const getAccessCode = `-- name: GetAccessCode :one
SELECT id, owner_id, code, label, purpose, included_tags, excluded_tags, suggested_questions, expires_at, status, created_at FROM access_codes WHERE code = $1 AND status = 'active'
`

func (q *Queries) GetAccessCode(ctx context.Context, code string) (AccessCode, error) {
	row := q.db.QueryRow(ctx, getAccessCode, code)
	var i AccessCode
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.Label,
		&i.Purpose,
		&i.IncludedTags,
		&i.ExcludedTags,
		&i.SuggestedQuestions,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listAccessCodesByOwner = `-- name: ListAccessCodesByOwner :many
SELECT id, owner_id, code, label, purpose, included_tags, excluded_tags, suggested_questions, expires_at, status, created_at FROM access_codes WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAccessCodesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]AccessCode, error) {
	rows, err := q.db.Query(ctx, listAccessCodesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessCode
	for rows.Next() {
		var i AccessCode
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Code,
			&i.Label,
			&i.Purpose,
			&i.IncludedTags,
			&i.ExcludedTags,
			&i.SuggestedQuestions,
			&i.ExpiresAt,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodeMembers = `-- name: ListCodeMembers :many
SELECT id, code_id, display_name, email, is_anonymous, last_seen_at FROM code_members WHERE code_id = $1
`

func (q *Queries) ListCodeMembers(ctx context.Context, codeID pgtype.UUID) ([]CodeMember, error) {
	rows, err := q.db.Query(ctx, listCodeMembers, codeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodeMember
	for rows.Next() {
		var i CodeMember
		if err := rows.Scan(
			&i.ID,
			&i.CodeID,
			&i.DisplayName,
			&i.Email,
			&i.IsAnonymous,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAccessCode = `-- name: RevokeAccessCode :exec
UPDATE access_codes SET status = 'revoked' WHERE id = $1 AND owner_id = $2
`

type RevokeAccessCodeParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) RevokeAccessCode(ctx context.Context, arg RevokeAccessCodeParams) error {
	_, err := q.db.Exec(ctx, revokeAccessCode, arg.ID, arg.OwnerID)
	return err
}

const touchCodeMember = `-- name: TouchCodeMember :exec
UPDATE code_members SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchCodeMember(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchCodeMember, id)
	return err
}
