// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: api_tokens.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (owner_id, name, token_hash)
VALUES ($1, $2, $3)
RETURNING id, owner_id, name, token_hash, scopes, last_used_at, created_at
`

type CreateAPITokenParams struct {
	OwnerID   pgtype.UUID
	Name      string
	TokenHash string
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken, arg.OwnerID, arg.Name, arg.TokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens WHERE id = $1 AND owner_id = $2
`

type DeleteAPITokenParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) error {
	_, err := q.db.Exec(ctx, deleteAPIToken, arg.ID, arg.OwnerID)
	return err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, owner_id, name, token_hash, scopes, last_used_at, created_at FROM api_tokens WHERE token_hash = $1
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPITokensByOwner = `-- name: ListAPITokensByOwner :many
SELECT id, name, last_used_at, created_at FROM api_tokens
WHERE owner_id = $1
ORDER BY created_at DESC
`

type ListAPITokensByOwnerRow struct {
	ID         pgtype.UUID
	Name       string
	LastUsedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListAPITokensByOwner(ctx context.Context, ownerID pgtype.UUID) ([]ListAPITokensByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listAPITokensByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPITokensByOwnerRow
	for rows.Next() {
		var i ListAPITokensByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}
