// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: code_bookings.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearBookingConfirmationSent = `-- name: ClearBookingConfirmationSent :exec
UPDATE code_bookings
SET confirmation_sent_at = NULL
WHERE id = $1
`

// Release a confirmation claim (set back to NULL) when the send FAILED after claiming, so a retry
// can re-claim and send. Only clears our own just-set claim path.
func (q *Queries) ClearBookingConfirmationSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearBookingConfirmationSent, id)
	return err
}

const createCodeBooking = `-- name: CreateCodeBooking :one
WITH cap AS (
    SELECT max_bookings FROM access_codes WHERE id = $2 FOR UPDATE
)
INSERT INTO code_bookings (
    owner_id, code_id, conversation_id,
    google_event_id, google_html_link, summary,
    start_at, end_at, visitor_email
)
SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9
FROM cap
WHERE (SELECT COUNT(*) FROM code_bookings WHERE code_id = $2)
      < COALESCE(cap.max_bookings, 2147483647)
RETURNING id, owner_id, code_id, conversation_id, google_event_id, google_html_link, summary, start_at, end_at, visitor_email, confirmation_sent_at, created_at
`

type CreateCodeBookingParams struct {
	OwnerID        pgtype.UUID
	CodeID         pgtype.UUID
	ConversationID pgtype.UUID
	GoogleEventID  string
	GoogleHtmlLink string
	Summary        string
	StartAt        pgtype.Timestamptz
	EndAt          pgtype.Timestamptz
	VisitorEmail   *string
}

// Atomic quota enforcement: FOR UPDATE locks the code row so concurrent bookings for the same code
// serialize; the insert only happens if the current count is under the code's max_bookings cap
// (NULL = unlimited). Over cap → 0 rows → caller maps to a quota error. This is the authoritative
// gate; the assembly-time check is only an advisory hide and is bypassable (concurrent / within-turn
// book calls) without this.
func (q *Queries) CreateCodeBooking(ctx context.Context, arg CreateCodeBookingParams) (CodeBooking, error) {
	row := q.db.QueryRow(ctx, createCodeBooking,
		arg.OwnerID,
		arg.CodeID,
		arg.ConversationID,
		arg.GoogleEventID,
		arg.GoogleHtmlLink,
		arg.Summary,
		arg.StartAt,
		arg.EndAt,
		arg.VisitorEmail,
	)
	var i CodeBooking
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CodeID,
		&i.ConversationID,
		&i.GoogleEventID,
		&i.GoogleHtmlLink,
		&i.Summary,
		&i.StartAt,
		&i.EndAt,
		&i.VisitorEmail,
		&i.ConfirmationSentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getBookingForMemberByEvent = `-- name: GetBookingForMemberByEvent :one
SELECT b.id, b.owner_id, b.code_id, b.conversation_id, b.google_event_id, b.google_html_link, b.summary, b.start_at, b.end_at, b.visitor_email, b.confirmation_sent_at, b.created_at FROM code_bookings b
JOIN conversations c ON c.id = b.conversation_id
WHERE b.google_event_id = $1
  AND b.owner_id = $2
  AND b.code_id = $3
  AND c.member_id = $4
`

type GetBookingForMemberByEventParams struct {
	GoogleEventID string
	OwnerID       pgtype.UUID
	CodeID        pgtype.UUID
	MemberID      pgtype.UUID
}

// #123 访客取消的隔离门:用 google_event_id 找 booking,但只在它属于本 session
// (owner + code 都对,且其 conversation 归属同一个 member)时才返。任一不匹 → 0 行
// → caller 翻 ErrBookingNotFound(不泄露存在性)。同码跨 member / 跨 code 都被挡。
func (q *Queries) GetBookingForMemberByEvent(ctx context.Context, arg GetBookingForMemberByEventParams) (CodeBooking, error) {
	row := q.db.QueryRow(ctx, getBookingForMemberByEvent,
		arg.GoogleEventID,
		arg.OwnerID,
		arg.CodeID,
		arg.MemberID,
	)
	var i CodeBooking
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CodeID,
		&i.ConversationID,
		&i.GoogleEventID,
		&i.GoogleHtmlLink,
		&i.Summary,
		&i.StartAt,
		&i.EndAt,
		&i.VisitorEmail,
		&i.ConfirmationSentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestBookingByConversation = `-- name: GetLatestBookingByConversation :one
SELECT id, owner_id, code_id, conversation_id, google_event_id, google_html_link, summary, start_at, end_at, visitor_email, confirmation_sent_at, created_at FROM code_bookings
WHERE conversation_id = $1
ORDER BY created_at DESC
LIMIT 1
`

// 某对话最近一笔预约(#122 发确认信:前端不传 id,后端按 session→对话定位)。
func (q *Queries) GetLatestBookingByConversation(ctx context.Context, conversationID pgtype.UUID) (CodeBooking, error) {
	row := q.db.QueryRow(ctx, getLatestBookingByConversation, conversationID)
	var i CodeBooking
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CodeID,
		&i.ConversationID,
		&i.GoogleEventID,
		&i.GoogleHtmlLink,
		&i.Summary,
		&i.StartAt,
		&i.EndAt,
		&i.VisitorEmail,
		&i.ConfirmationSentAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCodeBookingsByOwner = `-- name: ListCodeBookingsByOwner :many
SELECT id, owner_id, code_id, conversation_id, google_event_id, google_html_link, summary, start_at, end_at, visitor_email, confirmation_sent_at, created_at FROM code_bookings
WHERE owner_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListCodeBookingsByOwnerParams struct {
	OwnerID pgtype.UUID
	Limit   int32
}

func (q *Queries) ListCodeBookingsByOwner(ctx context.Context, arg ListCodeBookingsByOwnerParams) ([]CodeBooking, error) {
	rows, err := q.db.Query(ctx, listCodeBookingsByOwner, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodeBooking
	for rows.Next() {
		var i CodeBooking
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.CodeID,
			&i.ConversationID,
			&i.GoogleEventID,
			&i.GoogleHtmlLink,
			&i.Summary,
			&i.StartAt,
			&i.EndAt,
			&i.VisitorEmail,
			&i.ConfirmationSentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBookingConfirmationSent = `-- name: MarkBookingConfirmationSent :execrows
UPDATE code_bookings
SET confirmation_sent_at = now()
WHERE id = $1 AND confirmation_sent_at IS NULL
`

// CLAIM this booking's confirmation atomically (idempotent + race-safe): sets sent_at only if still
// NULL and returns rows-affected. 0 rows = someone already claimed it → caller must NOT send. The
// claim happens BEFORE the email is sent so two concurrent requests can't both send (TOCTOU).
func (q *Queries) MarkBookingConfirmationSent(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markBookingConfirmationSent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
