// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: conversation_suggestions.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listSuggestionsByConversation = `-- name: ListSuggestionsByConversation :many
SELECT id, owner_id, conversation_id, turn_index, ghost_text, source, shown_at, accepted_at FROM conversation_suggestions
WHERE conversation_id = $1 AND owner_id = $2
ORDER BY shown_at ASC
`

type ListSuggestionsByConversationParams struct {
	ConversationID pgtype.UUID
	OwnerID        pgtype.UUID
}

func (q *Queries) ListSuggestionsByConversation(ctx context.Context, arg ListSuggestionsByConversationParams) ([]ConversationSuggestion, error) {
	rows, err := q.db.Query(ctx, listSuggestionsByConversation, arg.ConversationID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationSuggestion
	for rows.Next() {
		var i ConversationSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ConversationID,
			&i.TurnIndex,
			&i.GhostText,
			&i.Source,
			&i.ShownAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSuggestionAccepted = `-- name: MarkSuggestionAccepted :one
UPDATE conversation_suggestions
SET accepted_at = now()
WHERE id = $1 AND conversation_id = $2 AND owner_id = $3
RETURNING id, owner_id, conversation_id, turn_index, ghost_text, source, shown_at, accepted_at
`

type MarkSuggestionAcceptedParams struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	OwnerID        pgtype.UUID
}

func (q *Queries) MarkSuggestionAccepted(ctx context.Context, arg MarkSuggestionAcceptedParams) (ConversationSuggestion, error) {
	row := q.db.QueryRow(ctx, markSuggestionAccepted, arg.ID, arg.ConversationID, arg.OwnerID)
	var i ConversationSuggestion
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConversationID,
		&i.TurnIndex,
		&i.GhostText,
		&i.Source,
		&i.ShownAt,
		&i.AcceptedAt,
	)
	return i, err
}

const recordShownSuggestion = `-- name: RecordShownSuggestion :one
INSERT INTO conversation_suggestions (
    owner_id, conversation_id, turn_index, ghost_text, source
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, conversation_id, turn_index, ghost_text, source, shown_at, accepted_at
`

type RecordShownSuggestionParams struct {
	OwnerID        pgtype.UUID
	ConversationID pgtype.UUID
	TurnIndex      int32
	GhostText      string
	Source         string
}

func (q *Queries) RecordShownSuggestion(ctx context.Context, arg RecordShownSuggestionParams) (ConversationSuggestion, error) {
	row := q.db.QueryRow(ctx, recordShownSuggestion,
		arg.OwnerID,
		arg.ConversationID,
		arg.TurnIndex,
		arg.GhostText,
		arg.Source,
	)
	var i ConversationSuggestion
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConversationID,
		&i.TurnIndex,
		&i.GhostText,
		&i.Source,
		&i.ShownAt,
		&i.AcceptedAt,
	)
	return i, err
}
