// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: conversation_ghosts.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listGhostsByConversation = `-- name: ListGhostsByConversation :many
SELECT id, owner_id, conversation_id, turn_index, ghost_text, source, target_waypoint, follows_from, shown_at, accepted_at FROM conversation_ghosts
WHERE conversation_id = $1 AND owner_id = $2
ORDER BY shown_at ASC
`

type ListGhostsByConversationParams struct {
	ConversationID pgtype.UUID
	OwnerID        pgtype.UUID
}

func (q *Queries) ListGhostsByConversation(ctx context.Context, arg ListGhostsByConversationParams) ([]ConversationGhost, error) {
	rows, err := q.db.Query(ctx, listGhostsByConversation, arg.ConversationID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationGhost
	for rows.Next() {
		var i ConversationGhost
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ConversationID,
			&i.TurnIndex,
			&i.GhostText,
			&i.Source,
			&i.TargetWaypoint,
			&i.FollowsFrom,
			&i.ShownAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGhostAccepted = `-- name: MarkGhostAccepted :one
UPDATE conversation_ghosts
SET accepted_at = now()
WHERE id = $1 AND conversation_id = $2 AND owner_id = $3
RETURNING id, owner_id, conversation_id, turn_index, ghost_text, source, target_waypoint, follows_from, shown_at, accepted_at
`

type MarkGhostAcceptedParams struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	OwnerID        pgtype.UUID
}

func (q *Queries) MarkGhostAccepted(ctx context.Context, arg MarkGhostAcceptedParams) (ConversationGhost, error) {
	row := q.db.QueryRow(ctx, markGhostAccepted, arg.ID, arg.ConversationID, arg.OwnerID)
	var i ConversationGhost
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConversationID,
		&i.TurnIndex,
		&i.GhostText,
		&i.Source,
		&i.TargetWaypoint,
		&i.FollowsFrom,
		&i.ShownAt,
		&i.AcceptedAt,
	)
	return i, err
}

const recordShownGhost = `-- name: RecordShownGhost :one
INSERT INTO conversation_ghosts (
    owner_id, conversation_id, turn_index, ghost_text, source
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, conversation_id, turn_index, ghost_text, source, target_waypoint, follows_from, shown_at, accepted_at
`

type RecordShownGhostParams struct {
	OwnerID        pgtype.UUID
	ConversationID pgtype.UUID
	TurnIndex      int32
	GhostText      string
	Source         string
}

func (q *Queries) RecordShownGhost(ctx context.Context, arg RecordShownGhostParams) (ConversationGhost, error) {
	row := q.db.QueryRow(ctx, recordShownGhost,
		arg.OwnerID,
		arg.ConversationID,
		arg.TurnIndex,
		arg.GhostText,
		arg.Source,
	)
	var i ConversationGhost
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConversationID,
		&i.TurnIndex,
		&i.GhostText,
		&i.Source,
		&i.TargetWaypoint,
		&i.FollowsFrom,
		&i.ShownAt,
		&i.AcceptedAt,
	)
	return i, err
}
