// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: conversations.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendMessage = `-- name: AppendMessage :one
INSERT INTO messages (
    conversation_id, dialog_id, role, body, tool_calls,
    cited_wiki_ids, cited_output_ids, cited_subjectivity_ids
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, conversation_id, dialog_id, role, body, tool_calls, cited_wiki_ids, cited_output_ids, cited_subjectivity_ids, created_at
`

type AppendMessageParams struct {
	ConversationID       pgtype.UUID
	DialogID             pgtype.UUID
	Role                 string
	Body                 string
	ToolCalls            []byte
	CitedWikiIds         []pgtype.UUID
	CitedOutputIds       []pgtype.UUID
	CitedSubjectivityIds []pgtype.UUID
}

func (q *Queries) AppendMessage(ctx context.Context, arg AppendMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, appendMessage,
		arg.ConversationID,
		arg.DialogID,
		arg.Role,
		arg.Body,
		arg.ToolCalls,
		arg.CitedWikiIds,
		arg.CitedOutputIds,
		arg.CitedSubjectivityIds,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.DialogID,
		&i.Role,
		&i.Body,
		&i.ToolCalls,
		&i.CitedWikiIds,
		&i.CitedOutputIds,
		&i.CitedSubjectivityIds,
		&i.CreatedAt,
	)
	return i, err
}

const bumpConversation = `-- name: BumpConversation :exec
UPDATE conversations
SET last_at = now()
WHERE id = $1
`

// 只更 last_at(给列表排序);turn 数不再存,读时从 messages 派生。
func (q *Queries) BumpConversation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, bumpConversation, id)
	return err
}

const countVisitorTurnsForMember = `-- name: CountVisitorTurnsForMember :one
SELECT COUNT(*)::int FROM messages m
JOIN conversations c ON c.id = m.conversation_id
WHERE c.member_id = $1 AND m.role = 'visitor'
`

// member 级 turn 配额:该 member 名下**全部对话**的访客发言合计。多段对话共享
// 一个预算,不按单段对话各算。
func (q *Queries) CountVisitorTurnsForMember(ctx context.Context, memberID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countVisitorTurnsForMember, memberID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (
    owner_id, mode, code_id, member_id, visitor_name, client_ip, doc_key
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, owner_id, mode, code_id, member_id, visitor_name, started_at, last_at, client_ip, doc_key
`

type CreateConversationParams struct {
	OwnerID     pgtype.UUID
	Mode        string
	CodeID      pgtype.UUID
	MemberID    pgtype.UUID
	VisitorName string
	ClientIp    string
	DocKey      string
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.OwnerID,
		arg.Mode,
		arg.CodeID,
		arg.MemberID,
		arg.VisitorName,
		arg.ClientIp,
		arg.DocKey,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Mode,
		&i.CodeID,
		&i.MemberID,
		&i.VisitorName,
		&i.StartedAt,
		&i.LastAt,
		&i.ClientIp,
		&i.DocKey,
	)
	return i, err
}

const createDialog = `-- name: CreateDialog :one
INSERT INTO dialogs (conversation_id)
VALUES ($1)
RETURNING id
`

// 一轮 Q-A 先建一个 dialog 行,两条 message 挂它的 id。返回真 dialog id。
func (q *Queries) CreateDialog(ctx context.Context, conversationID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createDialog, conversationID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, owner_id, mode, code_id, member_id, visitor_name, started_at, last_at, client_ip, doc_key FROM conversations WHERE id = $1 AND owner_id = $2
`

type GetConversationParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.ID, arg.OwnerID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Mode,
		&i.CodeID,
		&i.MemberID,
		&i.VisitorName,
		&i.StartedAt,
		&i.LastAt,
		&i.ClientIp,
		&i.DocKey,
	)
	return i, err
}

const getOpenConversationByMember = `-- name: GetOpenConversationByMember :one
SELECT id, owner_id, mode, code_id, member_id, visitor_name, started_at, last_at, client_ip, doc_key FROM conversations
WHERE member_id = $1 AND doc_key = ''
ORDER BY last_at DESC
LIMIT 1
`

// 「一个名字=一段续聊的会」(主对话):同名 member 的**主**对话(doc_key=”)续上;
// 没有 → caller 新建。对话不结束,同名永远续同一段主对话。
func (q *Queries) GetOpenConversationByMember(ctx context.Context, memberID pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getOpenConversationByMember, memberID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Mode,
		&i.CodeID,
		&i.MemberID,
		&i.VisitorName,
		&i.StartedAt,
		&i.LastAt,
		&i.ClientIp,
		&i.DocKey,
	)
	return i, err
}

const getOpenConversationByMemberAndDoc = `-- name: GetOpenConversationByMemberAndDoc :one
SELECT id, owner_id, mode, code_id, member_id, visitor_name, started_at, last_at, client_ip, doc_key FROM conversations
WHERE member_id = $1 AND doc_key = $2
ORDER BY last_at DESC
LIMIT 1
`

type GetOpenConversationByMemberAndDocParams struct {
	MemberID pgtype.UUID
	DocKey   string
}

// 浮窗用:该 member 在某个 surface(doc_key)上的那段对话。没有 → caller 新建。
func (q *Queries) GetOpenConversationByMemberAndDoc(ctx context.Context, arg GetOpenConversationByMemberAndDocParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getOpenConversationByMemberAndDoc, arg.MemberID, arg.DocKey)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Mode,
		&i.CodeID,
		&i.MemberID,
		&i.VisitorName,
		&i.StartedAt,
		&i.LastAt,
		&i.ClientIp,
		&i.DocKey,
	)
	return i, err
}

const listConversationsByOwner = `-- name: ListConversationsByOwner :many
SELECT c.id, c.mode, c.code_id, c.visitor_name, c.started_at,
       c.last_at, c.client_ip,
       (SELECT COUNT(*) FROM messages m
        WHERE m.conversation_id = c.id AND m.role = 'visitor')::int AS turn_count,
       ac.label AS code_label, ac.code AS code_value
FROM conversations c
LEFT JOIN access_codes ac ON ac.id = c.code_id
WHERE c.owner_id = $1
ORDER BY c.last_at DESC
LIMIT $2
`

type ListConversationsByOwnerParams struct {
	OwnerID pgtype.UUID
	Limit   int32
}

type ListConversationsByOwnerRow struct {
	ID          pgtype.UUID
	Mode        string
	CodeID      pgtype.UUID
	VisitorName string
	StartedAt   pgtype.Timestamptz
	LastAt      pgtype.Timestamptz
	ClientIp    string
	TurnCount   int32
	CodeLabel   *string
	CodeValue   *string
}

// turn_count 从 dialog 派生:数 visitor-role messages(一个 dialog 一条 visitor 消息),
// 不存计数字段。
func (q *Queries) ListConversationsByOwner(ctx context.Context, arg ListConversationsByOwnerParams) ([]ListConversationsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listConversationsByOwner, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsByOwnerRow
	for rows.Next() {
		var i ListConversationsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.CodeID,
			&i.VisitorName,
			&i.StartedAt,
			&i.LastAt,
			&i.ClientIp,
			&i.TurnCount,
			&i.CodeLabel,
			&i.CodeValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberOtherConversationMessages = `-- name: ListMemberOtherConversationMessages :many
SELECT c.doc_key, c.started_at, m.role, m.body, m.created_at
FROM messages m
JOIN conversations c ON c.id = m.conversation_id
WHERE c.member_id = $1 AND c.id <> $2
ORDER BY m.created_at
`

type ListMemberOtherConversationMessagesParams struct {
	MemberID pgtype.UUID
	ID       pgtype.UUID
}

type ListMemberOtherConversationMessagesRow struct {
	DocKey    string
	StartedAt pgtype.Timestamptz
	Role      string
	Body      string
	CreatedAt pgtype.Timestamptz
}

// 「互通」:拉该 member **其他**对话(排除当前这段)的近期消息,拼进 instruction
// 让 AI 跨对话连贯。按时间正序,caller 自己截断/汇总。
func (q *Queries) ListMemberOtherConversationMessages(ctx context.Context, arg ListMemberOtherConversationMessagesParams) ([]ListMemberOtherConversationMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMemberOtherConversationMessages, arg.MemberID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemberOtherConversationMessagesRow
	for rows.Next() {
		var i ListMemberOtherConversationMessagesRow
		if err := rows.Scan(
			&i.DocKey,
			&i.StartedAt,
			&i.Role,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, dialog_id, role, body, tool_calls, cited_wiki_ids, cited_output_ids, cited_subjectivity_ids, created_at FROM messages WHERE conversation_id = $1 ORDER BY created_at
`

func (q *Queries) ListMessages(ctx context.Context, conversationID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.DialogID,
			&i.Role,
			&i.Body,
			&i.ToolCalls,
			&i.CitedWikiIds,
			&i.CitedOutputIds,
			&i.CitedSubjectivityIds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
