// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: conversations.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendMessage = `-- name: AppendMessage :one
INSERT INTO messages (conversation_id, role, body, tool_calls, cited_wiki_ids)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, conversation_id, role, body, tool_calls, cited_wiki_ids, created_at
`

type AppendMessageParams struct {
	ConversationID pgtype.UUID
	Role           string
	Body           string
	ToolCalls      []byte
	CitedWikiIds   []pgtype.UUID
}

func (q *Queries) AppendMessage(ctx context.Context, arg AppendMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, appendMessage,
		arg.ConversationID,
		arg.Role,
		arg.Body,
		arg.ToolCalls,
		arg.CitedWikiIds,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Body,
		&i.ToolCalls,
		&i.CitedWikiIds,
		&i.CreatedAt,
	)
	return i, err
}

const bumpConversation = `-- name: BumpConversation :exec
UPDATE conversations
SET last_at = now(),
    message_count = message_count + 1,
    hit_private = hit_private OR $2
WHERE id = $1
`

type BumpConversationParams struct {
	ID         pgtype.UUID
	HitPrivate bool
}

func (q *Queries) BumpConversation(ctx context.Context, arg BumpConversationParams) error {
	_, err := q.db.Exec(ctx, bumpConversation, arg.ID, arg.HitPrivate)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (owner_id, tier, code_id, member_id, visitor_name, byoai_provider)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, tier, code_id, member_id, visitor_name, byoai_provider, started_at, last_at, message_count, hit_private
`

type CreateConversationParams struct {
	OwnerID       pgtype.UUID
	Tier          string
	CodeID        pgtype.UUID
	MemberID      pgtype.UUID
	VisitorName   string
	ByoaiProvider *string
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.OwnerID,
		arg.Tier,
		arg.CodeID,
		arg.MemberID,
		arg.VisitorName,
		arg.ByoaiProvider,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Tier,
		&i.CodeID,
		&i.MemberID,
		&i.VisitorName,
		&i.ByoaiProvider,
		&i.StartedAt,
		&i.LastAt,
		&i.MessageCount,
		&i.HitPrivate,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, owner_id, tier, code_id, member_id, visitor_name, byoai_provider, started_at, last_at, message_count, hit_private FROM conversations WHERE id = $1 AND owner_id = $2
`

type GetConversationParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.ID, arg.OwnerID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Tier,
		&i.CodeID,
		&i.MemberID,
		&i.VisitorName,
		&i.ByoaiProvider,
		&i.StartedAt,
		&i.LastAt,
		&i.MessageCount,
		&i.HitPrivate,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, role, body, tool_calls, cited_wiki_ids, created_at FROM messages WHERE conversation_id = $1 ORDER BY created_at
`

func (q *Queries) ListMessages(ctx context.Context, conversationID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Body,
			&i.ToolCalls,
			&i.CitedWikiIds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
