// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: corpus.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveRaw = `-- name: ArchiveRaw :exec
UPDATE raw_entries SET archived = true WHERE id = $1 AND owner_id = $2
`

type ArchiveRawParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) ArchiveRaw(ctx context.Context, arg ArchiveRawParams) error {
	_, err := q.db.Exec(ctx, archiveRaw, arg.ID, arg.OwnerID)
	return err
}

const createRawEntry = `-- name: CreateRawEntry :one

INSERT INTO raw_entries (owner_id, body, source, source_meta, tags, flagged_private)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, body, source, source_meta, tags, flagged_private, promoted_to, archived, created_at
`

type CreateRawEntryParams struct {
	OwnerID        pgtype.UUID
	Body           string
	Source         string
	SourceMeta     []byte
	Tags           []string
	FlaggedPrivate bool
}

// corpus.sql —— raw_entries（未整理的摄入 inbox）的 query。raw 是独立表、不进统一 note 基座。
// wiki / output 的 query 已归一到 corpus_notes.sql（genre 参数化）。
func (q *Queries) CreateRawEntry(ctx context.Context, arg CreateRawEntryParams) (RawEntry, error) {
	row := q.db.QueryRow(ctx, createRawEntry,
		arg.OwnerID,
		arg.Body,
		arg.Source,
		arg.SourceMeta,
		arg.Tags,
		arg.FlaggedPrivate,
	)
	var i RawEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Body,
		&i.Source,
		&i.SourceMeta,
		&i.Tags,
		&i.FlaggedPrivate,
		&i.PromotedTo,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const getRawByID = `-- name: GetRawByID :one
SELECT id, owner_id, body, source, source_meta, tags, flagged_private, promoted_to, archived, created_at FROM raw_entries WHERE id = $1 AND owner_id = $2
`

type GetRawByIDParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetRawByID(ctx context.Context, arg GetRawByIDParams) (RawEntry, error) {
	row := q.db.QueryRow(ctx, getRawByID, arg.ID, arg.OwnerID)
	var i RawEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Body,
		&i.Source,
		&i.SourceMeta,
		&i.Tags,
		&i.FlaggedPrivate,
		&i.PromotedTo,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const listRawByOwner = `-- name: ListRawByOwner :many
SELECT id, owner_id, body, source, source_meta, tags, flagged_private, promoted_to, archived, created_at FROM raw_entries
WHERE owner_id = $1 AND archived = false
ORDER BY created_at DESC
LIMIT $2
`

type ListRawByOwnerParams struct {
	OwnerID pgtype.UUID
	Limit   int32
}

func (q *Queries) ListRawByOwner(ctx context.Context, arg ListRawByOwnerParams) ([]RawEntry, error) {
	rows, err := q.db.Query(ctx, listRawByOwner, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RawEntry
	for rows.Next() {
		var i RawEntry
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Body,
			&i.Source,
			&i.SourceMeta,
			&i.Tags,
			&i.FlaggedPrivate,
			&i.PromotedTo,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRawPromoted = `-- name: MarkRawPromoted :exec
UPDATE raw_entries SET promoted_to = $3 WHERE id = $1 AND owner_id = $2
`

type MarkRawPromotedParams struct {
	ID         pgtype.UUID
	OwnerID    pgtype.UUID
	PromotedTo pgtype.UUID
}

func (q *Queries) MarkRawPromoted(ctx context.Context, arg MarkRawPromotedParams) error {
	_, err := q.db.Exec(ctx, markRawPromoted, arg.ID, arg.OwnerID, arg.PromotedTo)
	return err
}

const setRawTags = `-- name: SetRawTags :exec
UPDATE raw_entries SET tags = $3 WHERE id = $1 AND owner_id = $2
`

type SetRawTagsParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
	Tags    []string
}

func (q *Queries) SetRawTags(ctx context.Context, arg SetRawTagsParams) error {
	_, err := q.db.Exec(ctx, setRawTags, arg.ID, arg.OwnerID, arg.Tags)
	return err
}

const updateRawBody = `-- name: UpdateRawBody :one
UPDATE raw_entries
SET body = $3, tags = $4, flagged_private = $5
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, body, source, source_meta, tags, flagged_private, promoted_to, archived, created_at
`

type UpdateRawBodyParams struct {
	ID             pgtype.UUID
	OwnerID        pgtype.UUID
	Body           string
	Tags           []string
	FlaggedPrivate bool
}

// admin "edit raw" 入口：改 body + tags + flagged_private。source 不动
// （source 是 ingest 来源标签，编辑不该改）。
func (q *Queries) UpdateRawBody(ctx context.Context, arg UpdateRawBodyParams) (RawEntry, error) {
	row := q.db.QueryRow(ctx, updateRawBody,
		arg.ID,
		arg.OwnerID,
		arg.Body,
		arg.Tags,
		arg.FlaggedPrivate,
	)
	var i RawEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Body,
		&i.Source,
		&i.SourceMeta,
		&i.Tags,
		&i.FlaggedPrivate,
		&i.PromotedTo,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const upsertRawFromVault = `-- name: UpsertRawFromVault :one
INSERT INTO raw_entries (owner_id, body, source, source_meta, tags, flagged_private)
VALUES ($1, $2, $3, '{}'::jsonb, $4, false)
ON CONFLICT (owner_id, source) WHERE source LIKE 'obsidian:%'
DO UPDATE SET body = EXCLUDED.body, tags = EXCLUDED.tags
RETURNING id, owner_id, body, source, source_meta, tags, flagged_private, promoted_to, archived, created_at
`

type UpsertRawFromVaultParams struct {
	OwnerID pgtype.UUID
	Body    string
	Source  string
	Tags    []string
}

// vault sync 幂等:同一 obsidian source 重传 → upsert(更新 body/tags),不 append 成重复行。
// 靠 raw_entries_obsidian_source_uniq (partial: source LIKE 'obsidian:%') 做 conflict 推断。
func (q *Queries) UpsertRawFromVault(ctx context.Context, arg UpsertRawFromVaultParams) (RawEntry, error) {
	row := q.db.QueryRow(ctx, upsertRawFromVault,
		arg.OwnerID,
		arg.Body,
		arg.Source,
		arg.Tags,
	)
	var i RawEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Body,
		&i.Source,
		&i.SourceMeta,
		&i.Tags,
		&i.FlaggedPrivate,
		&i.PromotedTo,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}
