// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: corpus.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveRaw = `-- name: ArchiveRaw :exec
UPDATE raw_entries SET archived = true WHERE id = $1 AND owner_id = $2
`

type ArchiveRawParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) ArchiveRaw(ctx context.Context, arg ArchiveRawParams) error {
	_, err := q.db.Exec(ctx, archiveRaw, arg.ID, arg.OwnerID)
	return err
}

const createRawEntry = `-- name: CreateRawEntry :one
INSERT INTO raw_entries (owner_id, body, source, source_meta, tags, flagged_private)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, body, source, source_meta, tags, flagged_private, promoted_to, archived, created_at
`

type CreateRawEntryParams struct {
	OwnerID        pgtype.UUID
	Body           string
	Source         string
	SourceMeta     []byte
	Tags           []string
	FlaggedPrivate bool
}

func (q *Queries) CreateRawEntry(ctx context.Context, arg CreateRawEntryParams) (RawEntry, error) {
	row := q.db.QueryRow(ctx, createRawEntry,
		arg.OwnerID,
		arg.Body,
		arg.Source,
		arg.SourceMeta,
		arg.Tags,
		arg.FlaggedPrivate,
	)
	var i RawEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Body,
		&i.Source,
		&i.SourceMeta,
		&i.Tags,
		&i.FlaggedPrivate,
		&i.PromotedTo,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const createWikiEntry = `-- name: CreateWikiEntry :one
INSERT INTO wiki_entries (owner_id, parent_id, title, body, tags, visibility, source_raw_ids)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, owner_id, parent_id, title, body, tags, visibility, source_raw_ids, created_at, updated_at
`

type CreateWikiEntryParams struct {
	OwnerID      pgtype.UUID
	ParentID     pgtype.UUID
	Title        string
	Body         string
	Tags         []string
	Visibility   string
	SourceRawIds []pgtype.UUID
}

func (q *Queries) CreateWikiEntry(ctx context.Context, arg CreateWikiEntryParams) (WikiEntry, error) {
	row := q.db.QueryRow(ctx, createWikiEntry,
		arg.OwnerID,
		arg.ParentID,
		arg.Title,
		arg.Body,
		arg.Tags,
		arg.Visibility,
		arg.SourceRawIds,
	)
	var i WikiEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.Visibility,
		&i.SourceRawIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWiki = `-- name: DeleteWiki :exec
DELETE FROM wiki_entries WHERE id = $1 AND owner_id = $2
`

type DeleteWikiParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) DeleteWiki(ctx context.Context, arg DeleteWikiParams) error {
	_, err := q.db.Exec(ctx, deleteWiki, arg.ID, arg.OwnerID)
	return err
}

const getRawByID = `-- name: GetRawByID :one
SELECT id, owner_id, body, source, source_meta, tags, flagged_private, promoted_to, archived, created_at FROM raw_entries WHERE id = $1 AND owner_id = $2
`

type GetRawByIDParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetRawByID(ctx context.Context, arg GetRawByIDParams) (RawEntry, error) {
	row := q.db.QueryRow(ctx, getRawByID, arg.ID, arg.OwnerID)
	var i RawEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Body,
		&i.Source,
		&i.SourceMeta,
		&i.Tags,
		&i.FlaggedPrivate,
		&i.PromotedTo,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const getWikiByID = `-- name: GetWikiByID :one
SELECT id, owner_id, parent_id, title, body, tags, visibility, source_raw_ids, created_at, updated_at FROM wiki_entries WHERE id = $1 AND owner_id = $2
`

type GetWikiByIDParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetWikiByID(ctx context.Context, arg GetWikiByIDParams) (WikiEntry, error) {
	row := q.db.QueryRow(ctx, getWikiByID, arg.ID, arg.OwnerID)
	var i WikiEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.Visibility,
		&i.SourceRawIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRawByOwner = `-- name: ListRawByOwner :many
SELECT id, owner_id, body, source, source_meta, tags, flagged_private, promoted_to, archived, created_at FROM raw_entries
WHERE owner_id = $1 AND archived = false
ORDER BY created_at DESC
LIMIT $2
`

type ListRawByOwnerParams struct {
	OwnerID pgtype.UUID
	Limit   int32
}

func (q *Queries) ListRawByOwner(ctx context.Context, arg ListRawByOwnerParams) ([]RawEntry, error) {
	rows, err := q.db.Query(ctx, listRawByOwner, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RawEntry
	for rows.Next() {
		var i RawEntry
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Body,
			&i.Source,
			&i.SourceMeta,
			&i.Tags,
			&i.FlaggedPrivate,
			&i.PromotedTo,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWikiByOwner = `-- name: ListWikiByOwner :many
SELECT id, owner_id, parent_id, title, body, tags, visibility, source_raw_ids, created_at, updated_at FROM wiki_entries
WHERE owner_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListWikiByOwnerParams struct {
	OwnerID pgtype.UUID
	Limit   int32
}

func (q *Queries) ListWikiByOwner(ctx context.Context, arg ListWikiByOwnerParams) ([]WikiEntry, error) {
	rows, err := q.db.Query(ctx, listWikiByOwner, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WikiEntry
	for rows.Next() {
		var i WikiEntry
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Title,
			&i.Body,
			&i.Tags,
			&i.Visibility,
			&i.SourceRawIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRawPromoted = `-- name: MarkRawPromoted :exec
UPDATE raw_entries SET promoted_to = $3 WHERE id = $1 AND owner_id = $2
`

type MarkRawPromotedParams struct {
	ID         pgtype.UUID
	OwnerID    pgtype.UUID
	PromotedTo pgtype.UUID
}

func (q *Queries) MarkRawPromoted(ctx context.Context, arg MarkRawPromotedParams) error {
	_, err := q.db.Exec(ctx, markRawPromoted, arg.ID, arg.OwnerID, arg.PromotedTo)
	return err
}

const setRawTags = `-- name: SetRawTags :exec
UPDATE raw_entries SET tags = $3 WHERE id = $1 AND owner_id = $2
`

type SetRawTagsParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
	Tags    []string
}

func (q *Queries) SetRawTags(ctx context.Context, arg SetRawTagsParams) error {
	_, err := q.db.Exec(ctx, setRawTags, arg.ID, arg.OwnerID, arg.Tags)
	return err
}

const setWikiTags = `-- name: SetWikiTags :exec
UPDATE wiki_entries SET tags = $3, updated_at = now() WHERE id = $1 AND owner_id = $2
`

type SetWikiTagsParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
	Tags    []string
}

func (q *Queries) SetWikiTags(ctx context.Context, arg SetWikiTagsParams) error {
	_, err := q.db.Exec(ctx, setWikiTags, arg.ID, arg.OwnerID, arg.Tags)
	return err
}
