// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: handle_aliases.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// SelectOwnerForAlias —— alias lookup 返回的 owner 子集（少 password_hash /
// custom_domain，跟 toDomainOwner 用得到的字段对齐）。这个结构跟主 Owner
// 不完全一样，所以单独定一个类型。
type SelectOwnerForAlias struct {
	ID               pgtype.UUID
	Email            string
	Handle           string
	FullName         string
	Location         string
	ByoaiEnabled     bool
	ByoaiProviders   []byte
	ByoaiPublicBlurb string
	CreatedAt        pgtype.Timestamptz
}

const getOwnerByHandleAlias = `-- name: GetOwnerByHandleAlias :one
SELECT o.id, o.email, o.handle, o.full_name, o.location,
       o.byoai_enabled, o.byoai_providers, o.byoai_public_blurb, o.created_at
FROM owners o
JOIN handle_aliases a ON a.owner_id = o.id
WHERE a.handle = $1
`

func (q *Queries) GetOwnerByHandleAlias(
	ctx context.Context, handle string,
) (SelectOwnerForAlias, error) {
	row := q.db.QueryRow(ctx, getOwnerByHandleAlias, handle)
	var i SelectOwnerForAlias
	err := row.Scan(
		&i.ID, &i.Email, &i.Handle, &i.FullName, &i.Location,
		&i.ByoaiEnabled, &i.ByoaiProviders, &i.ByoaiPublicBlurb, &i.CreatedAt,
	)
	return i, err
}

const addHandleAlias = `-- name: AddHandleAlias :exec
INSERT INTO handle_aliases (handle, owner_id)
VALUES ($1, $2)
ON CONFLICT (handle) DO NOTHING
`

type AddHandleAliasParams struct {
	Handle  string
	OwnerID pgtype.UUID
}

func (q *Queries) AddHandleAlias(ctx context.Context, arg AddHandleAliasParams) error {
	_, err := q.db.Exec(ctx, addHandleAlias, arg.Handle, arg.OwnerID)
	return err
}

const updateOwnerHandle = `-- name: UpdateOwnerHandle :one
UPDATE owners
SET handle = $2
WHERE id = $1
RETURNING id, email, handle, full_name, location,
          byoai_enabled, byoai_providers, byoai_public_blurb, created_at
`

type UpdateOwnerHandleParams struct {
	ID     pgtype.UUID
	Handle string
}

func (q *Queries) UpdateOwnerHandle(
	ctx context.Context, arg UpdateOwnerHandleParams,
) (SelectOwnerForAlias, error) {
	row := q.db.QueryRow(ctx, updateOwnerHandle, arg.ID, arg.Handle)
	var i SelectOwnerForAlias
	err := row.Scan(
		&i.ID, &i.Email, &i.Handle, &i.FullName, &i.Location,
		&i.ByoaiEnabled, &i.ByoaiProviders, &i.ByoaiPublicBlurb, &i.CreatedAt,
	)
	return i, err
}
