// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: instance_settings.sql

package dbq

import (
	"context"
)

const getInstanceSettings = `-- name: GetInstanceSettings :one
SELECT id, is_claimed, setup_token_hash, multi_tenant, deployed_at, allowed_domains FROM instance_settings WHERE id = 1
`

func (q *Queries) GetInstanceSettings(ctx context.Context) (InstanceSetting, error) {
	row := q.db.QueryRow(ctx, getInstanceSettings)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.IsClaimed,
		&i.SetupTokenHash,
		&i.MultiTenant,
		&i.DeployedAt,
		&i.AllowedDomains,
	)
	return i, err
}

const setSetupTokenHash = `-- name: SetSetupTokenHash :exec
UPDATE instance_settings
SET setup_token_hash = $1
WHERE id = 1
`

// 把当前 setup_token_hash 写进 instance_settings；启动时调一次，让 setup
// token 真生效。
func (q *Queries) SetSetupTokenHash(ctx context.Context, setupTokenHash *string) error {
	_, err := q.db.Exec(ctx, setSetupTokenHash, setupTokenHash)
	return err
}

const tryClaimInstance = `-- name: TryClaimInstance :one
UPDATE instance_settings
SET is_claimed = true,
    setup_token_hash = NULL
WHERE id = 1
  AND is_claimed = false
  AND setup_token_hash = $1
RETURNING id, is_claimed, setup_token_hash, multi_tenant, deployed_at, allowed_domains
`

// 原子 claim：当且仅当 is_claimed=false 且 setup_token_hash 匹配时 mark
// claimed + 清 token。返回更新后的行；调用方据此判断是否成功（受影响 0
// 行即 token 错或已 claimed）。
func (q *Queries) TryClaimInstance(ctx context.Context, setupTokenHash *string) (InstanceSetting, error) {
	row := q.db.QueryRow(ctx, tryClaimInstance, setupTokenHash)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.IsClaimed,
		&i.SetupTokenHash,
		&i.MultiTenant,
		&i.DeployedAt,
		&i.AllowedDomains,
	)
	return i, err
}
