// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: job_sources.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJobSource = `-- name: CreateJobSource :one
INSERT INTO job_sources (owner_id, kind, config, label)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, kind, config, label, last_fetched_at, created_at
`

type CreateJobSourceParams struct {
	OwnerID pgtype.UUID
	Kind    string
	Config  []byte
	Label   string
}

func (q *Queries) CreateJobSource(ctx context.Context, arg CreateJobSourceParams) (JobSource, error) {
	row := q.db.QueryRow(ctx, createJobSource,
		arg.OwnerID,
		arg.Kind,
		arg.Config,
		arg.Label,
	)
	var i JobSource
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Kind,
		&i.Config,
		&i.Label,
		&i.LastFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteJobSource = `-- name: DeleteJobSource :exec
DELETE FROM job_sources WHERE id = $1 AND owner_id = $2
`

type DeleteJobSourceParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) DeleteJobSource(ctx context.Context, arg DeleteJobSourceParams) error {
	_, err := q.db.Exec(ctx, deleteJobSource, arg.ID, arg.OwnerID)
	return err
}

const getExistingFingerprints = `-- name: GetExistingFingerprints :many
SELECT external_id FROM job_fingerprints
WHERE source_id = $1 AND external_id = ANY($2::text[])
`

type GetExistingFingerprintsParams struct {
	SourceID pgtype.UUID
	Column2  []string
}

func (q *Queries) GetExistingFingerprints(ctx context.Context, arg GetExistingFingerprintsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getExistingFingerprints, arg.SourceID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var external_id string
		if err := rows.Scan(&external_id); err != nil {
			return nil, err
		}
		items = append(items, external_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobSource = `-- name: GetJobSource :one
SELECT id, owner_id, kind, config, label, last_fetched_at, created_at
FROM job_sources
WHERE id = $1 AND owner_id = $2
`

type GetJobSourceParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetJobSource(ctx context.Context, arg GetJobSourceParams) (JobSource, error) {
	row := q.db.QueryRow(ctx, getJobSource, arg.ID, arg.OwnerID)
	var i JobSource
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Kind,
		&i.Config,
		&i.Label,
		&i.LastFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertJobFingerprint = `-- name: InsertJobFingerprint :exec
INSERT INTO job_fingerprints (source_id, external_id)
VALUES ($1, $2)
ON CONFLICT (source_id, external_id) DO NOTHING
`

type InsertJobFingerprintParams struct {
	SourceID   pgtype.UUID
	ExternalID string
}

func (q *Queries) InsertJobFingerprint(ctx context.Context, arg InsertJobFingerprintParams) error {
	_, err := q.db.Exec(ctx, insertJobFingerprint, arg.SourceID, arg.ExternalID)
	return err
}

const listJobSourcesByOwner = `-- name: ListJobSourcesByOwner :many
SELECT id, owner_id, kind, config, label, last_fetched_at, created_at
FROM job_sources
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListJobSourcesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]JobSource, error) {
	rows, err := q.db.Query(ctx, listJobSourcesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobSource
	for rows.Next() {
		var i JobSource
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Kind,
			&i.Config,
			&i.Label,
			&i.LastFetchedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchJobSourceFetched = `-- name: TouchJobSourceFetched :exec
UPDATE job_sources SET last_fetched_at = now() WHERE id = $1
`

func (q *Queries) TouchJobSourceFetched(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchJobSourceFetched, id)
	return err
}
