// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package dbq

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessCode struct {
	ID                   pgtype.UUID
	OwnerID              pgtype.UUID
	Code                 string
	Label                string
	Purpose              string
	CorpusPermissions    []byte
	SuggestedQuestions   []byte
	ExpiresAt            pgtype.Timestamptz
	Status               string
	MaxSessionsPerMember *int32
	MaxTurnsPerSession   *int32
	CreatedAt            pgtype.Timestamptz
}

type AccessRequest struct {
	ID        pgtype.UUID
	OwnerID   pgtype.UUID
	Name      string
	Org       string
	Email     string
	Message   string
	Status    string
	CreatedAt pgtype.Timestamptz
}

type ApiToken struct {
	ID         pgtype.UUID
	OwnerID    pgtype.UUID
	Name       string
	TokenHash  string
	Scopes     []string
	LastUsedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Application struct {
	ID            pgtype.UUID
	OwnerID       pgtype.UUID
	AccessCodeID  pgtype.UUID
	JobSnapshot   []byte
	ResumeContent []byte
	Status        string
	SubmittedAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type CodeMember struct {
	ID          pgtype.UUID
	CodeID      pgtype.UUID
	DisplayName string
	Email       *string
	IsAnonymous bool
	LastSeenAt  pgtype.Timestamptz
}

type CodeSkill struct {
	CodeID  pgtype.UUID
	SkillID pgtype.UUID
}

type Conversation struct {
	ID            pgtype.UUID
	OwnerID       pgtype.UUID
	Tier          string
	CodeID        pgtype.UUID
	MemberID      pgtype.UUID
	VisitorName   string
	ByoaiProvider *string
	StartedAt     pgtype.Timestamptz
	LastAt        pgtype.Timestamptz
	MessageCount  int32
	EndedAt       pgtype.Timestamptz
	SummaryMd     string
}

type CustomPage struct {
	ID                  pgtype.UUID
	OwnerID             pgtype.UUID
	Slug                string
	Title               string
	Status              string
	LiveBuildID         pgtype.UUID
	StagingBuildID      pgtype.UUID
	PreviousLiveBuildID pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type CustomPageBuild struct {
	ID           pgtype.UUID
	PageID       pgtype.UUID
	Status       string
	SourceFiles  []byte
	OutputPath   string
	ErrorMessage string
	CreatedAt    pgtype.Timestamptz
	BuiltAt      pgtype.Timestamptz
}

type HandleAlias struct {
	Handle    string
	OwnerID   pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type InstanceSetting struct {
	ID             int32
	IsClaimed      bool
	SetupTokenHash *string
	MultiTenant    bool
	DeployedAt     pgtype.Timestamptz
	AllowedDomains []byte
}

type JobFingerprint struct {
	SourceID    pgtype.UUID
	ExternalID  string
	FirstSeenAt pgtype.Timestamptz
}

type JobSource struct {
	ID            pgtype.UUID
	OwnerID       pgtype.UUID
	Kind          string
	Config        []byte
	Label         string
	LastFetchedAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type MediaAsset struct {
	ID            pgtype.UUID
	OwnerID       pgtype.UUID
	Kind          string
	Filename      string
	MimeType      string
	SizeBytes     int64
	StorageKey    string
	RawEntryID    pgtype.UUID
	WikiEntryID   pgtype.UUID
	OutputEntryID pgtype.UUID
	CreatedAt     pgtype.Timestamptz
}

type Message struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Role           string
	Body           string
	ToolCalls      []byte
	CitedWikiIds   []pgtype.UUID
	CitedOutputIds []pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type OutputEntry struct {
	ID             pgtype.UUID
	OwnerID        pgtype.UUID
	ParentID       pgtype.UUID
	Title          string
	Body           string
	Tags           []string
	SourceWikiIds  []pgtype.UUID
	Path           *string
	ShowAsSource   bool
	SeoDescription string
	SeoIndexed     bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Owner struct {
	ID                pgtype.UUID
	Email             string
	PasswordHash      string
	Handle            string
	FullName          string
	Location          string
	PublicUrl         string
	ByoaiEnabled      bool
	ByoaiProviders    []byte
	ByoaiPublicBlurb  string
	AiProvider        string
	AiProviderKeyEnc  []byte
	PasswordResetHash []byte
	PasswordResetAt   pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

type PageContent struct {
	OwnerID      pgtype.UUID
	HeroProse    string
	HeroExamples []byte
	Insights     []byte
	Projects     []byte
	WhereSection []byte
	Contact      []byte
	UpdatedAt    pgtype.Timestamptz
}

type RawEntry struct {
	ID             pgtype.UUID
	OwnerID        pgtype.UUID
	Body           string
	Source         string
	SourceMeta     []byte
	Tags           []string
	FlaggedPrivate bool
	PromotedTo     pgtype.UUID
	Archived       bool
	CreatedAt      pgtype.Timestamptz
}

type ResumeDraft struct {
	ID            pgtype.UUID
	OwnerID       pgtype.UUID
	JobCacheID    string
	JobSnapshot   []byte
	ResumeContent []byte
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type SeoSetting struct {
	OwnerID       pgtype.UUID
	IndexRobots   bool
	SitemapExtras []byte
	OgTemplate    string
	UpdatedAt     pgtype.Timestamptz
}

type Skill struct {
	ID           pgtype.UUID
	OwnerID      pgtype.UUID
	Name         string
	Description  string
	Prompt       string
	Scripts      []byte
	Metadata     []byte
	AllowedTools []string
	IsBuiltin    bool
	Version      string
	License      string
	Source       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type WikiEntry struct {
	ID             pgtype.UUID
	OwnerID        pgtype.UUID
	ParentID       pgtype.UUID
	Title          string
	Body           string
	Tags           []string
	SourceRawIds   []pgtype.UUID
	Path           *string
	ShowAsSource   bool
	SeoDescription string
	SeoIndexed     bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
