// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package dbq

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessCode struct {
	ID                 pgtype.UUID
	OwnerID            pgtype.UUID
	Code               string
	Label              string
	Purpose            string
	Ghosts             []byte
	ExpiresAt          pgtype.Timestamptz
	Status             string
	MaxTurnsPerSession *int32
	MaxMembers         *int32
	MaxBookings        *int32
	CreatedAt          pgtype.Timestamptz
	AssumedRoleID      pgtype.UUID
	PromptID           pgtype.UUID
}

type AccessRequest struct {
	ID        pgtype.UUID
	OwnerID   pgtype.UUID
	Name      string
	Org       string
	Email     string
	Message   string
	Status    string
	CreatedAt pgtype.Timestamptz
}

type Application struct {
	ID            pgtype.UUID
	OwnerID       pgtype.UUID
	AccessCodeID  pgtype.UUID
	JobSnapshot   []byte
	ResumeContent []byte
	Status        string
	SubmittedAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type Asset struct {
	ID               pgtype.UUID
	HolderID         pgtype.UUID
	StorageKey       string
	ContentType      string
	SizeBytes        int64
	Sha256           string
	OriginalFilename string
	CreatedAt        pgtype.Timestamptz
}

type BannedIp struct {
	ID        pgtype.UUID
	OwnerID   pgtype.UUID
	Ip        string
	Reason    string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type CapabilitySetting struct {
	OwnerID      pgtype.UUID
	CapabilityID string
	Enabled      bool
	UpdatedAt    pgtype.Timestamptz
}

type ChatReport struct {
	ID             pgtype.UUID
	OwnerID        pgtype.UUID
	ConversationID pgtype.UUID
	Html           string
	CreatedAt      pgtype.Timestamptz
}

type CodeBooking struct {
	ID                 pgtype.UUID
	OwnerID            pgtype.UUID
	CodeID             pgtype.UUID
	ConversationID     pgtype.UUID
	GoogleEventID      string
	GoogleHtmlLink     string
	Summary            string
	StartAt            pgtype.Timestamptz
	EndAt              pgtype.Timestamptz
	VisitorEmail       *string
	ConfirmationSentAt pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
}

type CodeCapabilityDenial struct {
	CodeID       pgtype.UUID
	CapabilityID string
}

type CodeMember struct {
	ID          pgtype.UUID
	CodeID      pgtype.UUID
	DisplayName string
	Email       *string
	IsAnonymous bool
	LastSeenAt  pgtype.Timestamptz
}

type CodeSkillDenial struct {
	CodeID  pgtype.UUID
	SkillID pgtype.UUID
}

type Conversation struct {
	ID          pgtype.UUID
	OwnerID     pgtype.UUID
	Mode        string
	CodeID      pgtype.UUID
	MemberID    pgtype.UUID
	VisitorName string
	StartedAt   pgtype.Timestamptz
	LastAt      pgtype.Timestamptz
	ClientIp    string
	DocKey      string
}

type ConversationGhost struct {
	ID             pgtype.UUID
	OwnerID        pgtype.UUID
	ConversationID pgtype.UUID
	TurnIndex      int32
	GhostText      string
	Source         string
	ShownAt        pgtype.Timestamptz
	AcceptedAt     pgtype.Timestamptz
}

type CustomPage struct {
	ID                  pgtype.UUID
	OwnerID             pgtype.UUID
	Slug                string
	Title               string
	Status              string
	LiveBuildID         pgtype.UUID
	StagingBuildID      pgtype.UUID
	PreviousLiveBuildID pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type CustomPageBuild struct {
	ID           pgtype.UUID
	PageID       pgtype.UUID
	Status       string
	SourceFiles  []byte
	OutputPath   string
	ErrorMessage string
	CreatedAt    pgtype.Timestamptz
	BuiltAt      pgtype.Timestamptz
}

type HandleAlias struct {
	Handle    string
	OwnerID   pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type InstanceSetting struct {
	ID             int32
	IsClaimed      bool
	SetupTokenHash *string
	MultiTenant    bool
	DeployedAt     pgtype.Timestamptz
	AllowedDomains []byte
}

type JobFingerprint struct {
	SourceID    pgtype.UUID
	ExternalID  string
	FirstSeenAt pgtype.Timestamptz
}

type JobSource struct {
	ID            pgtype.UUID
	OwnerID       pgtype.UUID
	Kind          string
	Config        []byte
	Label         string
	LastFetchedAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type McpAppState struct {
	OwnerID   pgtype.UUID
	MemberID  pgtype.UUID
	McpID     string
	StateKey  string
	Value     []byte
	UpdatedAt pgtype.Timestamptz
}

type McpServer struct {
	ID                 pgtype.UUID
	OwnerID            pgtype.UUID
	Name               string
	Url                string
	AuthHeaderName     string
	AuthHeaderValueEnc []byte
	GrantedDeps        []string
	CreatedAt          pgtype.Timestamptz
}

type MediaAsset struct {
	ID            pgtype.UUID
	OwnerID       pgtype.UUID
	Kind          string
	Filename      string
	MimeType      string
	SizeBytes     int64
	StorageKey    string
	RawEntryID    pgtype.UUID
	WikiEntryID   pgtype.UUID
	OutputEntryID pgtype.UUID
	CreatedAt     pgtype.Timestamptz
}

type Message struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Role           string
	Body           string
	ToolCalls      []byte
	CitedWikiIds   []pgtype.UUID
	CitedOutputIds []pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type OutputEntry struct {
	ID            pgtype.UUID
	OwnerID       pgtype.UUID
	ParentID      pgtype.UUID
	Title         string
	Body          string
	Tags          []string
	SourceWikiIds []pgtype.UUID
	ShowAsSource  bool
	Excerpt       string
	Published     bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Owner struct {
	ID                pgtype.UUID
	Email             string
	PasswordHash      string
	Handle            string
	FullName          string
	Location          string
	PublicUrl         string
	ByoaiEnabled      bool
	ByoaiProviders    []byte
	ByoaiPublicBlurb  string
	AiProvider        string
	AiProviderKeyEnc  []byte
	AiEndpoint        string
	AiModel           string
	PasswordResetHash []byte
	PasswordResetAt   pgtype.Timestamptz
	ProfileTimezone   string
	CreatedAt         pgtype.Timestamptz
}

type OwnerBookingPolicy struct {
	OwnerID           pgtype.UUID
	MinLeadDays       int32
	AllowedWeekdays   []string
	WorkingHoursStart string
	WorkingHoursEnd   string
	BufferMin         int32
	UpdatedAt         pgtype.Timestamptz
}

type OwnerCalendarConnector struct {
	ID                   pgtype.UUID
	OwnerID              pgtype.UUID
	Provider             string
	ClientIDEnc          []byte
	ClientSecretEnc      []byte
	AccessTokenEnc       []byte
	RefreshTokenEnc      []byte
	AccessTokenExpiresAt pgtype.Timestamptz
	Scopes               []byte
	ConnectedAt          pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type OwnerConnector struct {
	ID                 pgtype.UUID
	OwnerID            pgtype.UUID
	ConnectorID        string
	Category           string
	Kind               string
	CredentialsEnc     []byte
	TokenEnc           []byte
	TokenExpiresAt     pgtype.Timestamptz
	Scopes             []byte
	ConnectedAt        pgtype.Timestamptz
	Active             bool
	Spec               []byte
	Binding            []byte
	AuthScheme         string
	Protocol           string
	ExposeAsAgentTools bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type OwnerKeypair struct {
	ID           pgtype.UUID
	OwnerID      pgtype.UUID
	KeyID        string
	PublicKeyPem string
	Label        string
	LastUsedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type OwnerMailConnector struct {
	ID           pgtype.UUID
	OwnerID      pgtype.UUID
	Provider     string
	Host         string
	Port         int32
	UsernameEnc  []byte
	PasswordEnc  []byte
	FromAddress  string
	FromName     string
	ConnectedAt  pgtype.Timestamptz
	OtpHash      []byte
	OtpExpiresAt pgtype.Timestamptz
	OtpAttempts  int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type PageContent struct {
	OwnerID      pgtype.UUID
	HeroProse    string
	HeroExamples []byte
	Insights     []byte
	Projects     []byte
	WhereSection []byte
	Contact      []byte
	UpdatedAt    pgtype.Timestamptz
}

type Prompt struct {
	ID          pgtype.UUID
	OwnerID     pgtype.UUID
	Name        string
	Body        string
	Description string
	IsBuiltin   bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RawEntry struct {
	ID             pgtype.UUID
	OwnerID        pgtype.UUID
	Body           string
	Source         string
	SourceMeta     []byte
	Tags           []string
	FlaggedPrivate bool
	PromotedTo     pgtype.UUID
	Archived       bool
	CreatedAt      pgtype.Timestamptz
}

type ResumeDraft struct {
	ID            pgtype.UUID
	OwnerID       pgtype.UUID
	JobCacheID    string
	JobSnapshot   []byte
	ResumeContent []byte
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type Role struct {
	ID                   pgtype.UUID
	OwnerID              pgtype.UUID
	Name                 string
	Description          string
	Greeting             string
	PromptID             pgtype.UUID
	IsBuiltin            bool
	NotifyOwnerOnBooking bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type RoleCorpusUri struct {
	RoleID     pgtype.UUID
	UriPattern string
}

type RoleMcpServer struct {
	RoleID      pgtype.UUID
	McpServerID pgtype.UUID
}

type RoleSkill struct {
	RoleID  pgtype.UUID
	SkillID pgtype.UUID
}

type SeoSetting struct {
	OwnerID       pgtype.UUID
	SiteTitle     string
	IndexRobots   bool
	SitemapExtras []byte
	OgTemplate    string
	UpdatedAt     pgtype.Timestamptz
}

type Skill struct {
	ID           pgtype.UUID
	OwnerID      pgtype.UUID
	Name         string
	Description  string
	Prompt       string
	Scripts      []byte
	Metadata     []byte
	AllowedTools []string
	IsBuiltin    bool
	Enabled      bool
	Version      string
	License      string
	Source       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type WikiEntry struct {
	ID           pgtype.UUID
	OwnerID      pgtype.UUID
	ParentID     pgtype.UUID
	Title        string
	Body         string
	Tags         []string
	SourceRawIds []pgtype.UUID
	ShowAsSource bool
	Excerpt      string
	Published    bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type WikiRef struct {
	SrcWikiID pgtype.UUID
	DstWikiID pgtype.UUID
	OwnerID   pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Writing struct {
	ID                 pgtype.UUID
	OwnerID            pgtype.UUID
	Slug               string
	Title              string
	Excerpt            string
	BodyMd             string
	CoverHeadline      string
	CoverHue           string
	CoverImageAssetID  pgtype.UUID
	Tags               []string
	Visibility         string
	CrossRefs          []string
	Path               string
	ReadMinutes        int32
	LockedBody         string
	ObsidianSourcePath string
	ObsidianImportedAt pgtype.Timestamptz
	PublishedAt        pgtype.Timestamptz
	ParentID           pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type WritingRef struct {
	SrcWritingID pgtype.UUID
	DstWritingID pgtype.UUID
	OwnerID      pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}
