// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID         pgtype.UUID
	OwnerID    pgtype.UUID
	Name       string
	TokenHash  string
	Scopes     []string
	LastUsedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type InstanceSetting struct {
	ID             int32
	IsClaimed      bool
	SetupTokenHash *string
	MultiTenant    bool
	DeployedAt     pgtype.Timestamptz
}

type MediaAsset struct {
	ID          pgtype.UUID
	OwnerID     pgtype.UUID
	Kind        string
	Filename    string
	MimeType    string
	SizeBytes   int64
	StorageKey  string
	RawEntryID  pgtype.UUID
	WikiEntryID pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type Owner struct {
	ID                 pgtype.UUID
	Email              string
	PasswordHash       string
	Handle             string
	FullName           string
	Location           string
	CustomDomain       *string
	CustomDomainStatus string
	ByoaiEnabled       bool
	ByoaiProviders     []byte
	ByoaiPublicBlurb   string
	CreatedAt          pgtype.Timestamptz
}

type RawEntry struct {
	ID             pgtype.UUID
	OwnerID        pgtype.UUID
	Body           string
	Source         string
	SourceMeta     []byte
	Tags           []string
	FlaggedPrivate bool
	PromotedTo     pgtype.UUID
	Archived       bool
	CreatedAt      pgtype.Timestamptz
}

type WikiEntry struct {
	ID           pgtype.UUID
	OwnerID      pgtype.UUID
	ParentID     pgtype.UUID
	Title        string
	Body         string
	Tags         []string
	Visibility   string
	SourceRawIds []pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
