// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: output.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutputEntry = `-- name: CreateOutputEntry :one

INSERT INTO output_entries (
    owner_id, parent_id, title, body, tags, source_wiki_ids
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, parent_id, title, body, tags, source_wiki_ids, show_as_source, seo_description, seo_indexed, created_at, updated_at
`

type CreateOutputEntryParams struct {
	OwnerID       pgtype.UUID
	ParentID      pgtype.UUID
	Title         string
	Body          string
	Tags          []string
	SourceWikiIds []pgtype.UUID
}

// output_entries —— wiki 的最精炼版镜像。query 命名跟 wiki 对齐让代码生成
// 的方法名易认（CreateOutputEntry / ListOutputByOwner / ...）。
func (q *Queries) CreateOutputEntry(ctx context.Context, arg CreateOutputEntryParams) (OutputEntry, error) {
	row := q.db.QueryRow(ctx, createOutputEntry,
		arg.OwnerID,
		arg.ParentID,
		arg.Title,
		arg.Body,
		arg.Tags,
		arg.SourceWikiIds,
	)
	var i OutputEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.SourceWikiIds,
		&i.ShowAsSource,
		&i.SeoDescription,
		&i.SeoIndexed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOutput = `-- name: DeleteOutput :exec
DELETE FROM output_entries WHERE id = $1 AND owner_id = $2
`

type DeleteOutputParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) DeleteOutput(ctx context.Context, arg DeleteOutputParams) error {
	_, err := q.db.Exec(ctx, deleteOutput, arg.ID, arg.OwnerID)
	return err
}

const getOutputByID = `-- name: GetOutputByID :one
SELECT id, owner_id, parent_id, title, body, tags, source_wiki_ids, show_as_source, seo_description, seo_indexed, created_at, updated_at FROM output_entries WHERE id = $1 AND owner_id = $2
`

type GetOutputByIDParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetOutputByID(ctx context.Context, arg GetOutputByIDParams) (OutputEntry, error) {
	row := q.db.QueryRow(ctx, getOutputByID, arg.ID, arg.OwnerID)
	var i OutputEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.SourceWikiIds,
		&i.ShowAsSource,
		&i.SeoDescription,
		&i.SeoIndexed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutputMetaByID = `-- name: GetOutputMetaByID :one
SELECT id, parent_id, title, seo_indexed
FROM output_entries
WHERE id = $1 AND owner_id = $2
`

type GetOutputMetaByIDParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

type GetOutputMetaByIDRow struct {
	ID         pgtype.UUID
	ParentID   pgtype.UUID
	Title      string
	SeoIndexed bool
}

// meta only(无 body):上溯算树派生 path / 判 ACL 用,不为读正文。镜像 GetWikiMetaByID。
func (q *Queries) GetOutputMetaByID(ctx context.Context, arg GetOutputMetaByIDParams) (GetOutputMetaByIDRow, error) {
	row := q.db.QueryRow(ctx, getOutputMetaByID, arg.ID, arg.OwnerID)
	var i GetOutputMetaByIDRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Title,
		&i.SeoIndexed,
	)
	return i, err
}

const listAllOutputMeta = `-- name: ListAllOutputMeta :many
SELECT id, parent_id, title, seo_indexed, updated_at
FROM output_entries
WHERE owner_id = $1
ORDER BY created_at DESC
`

type ListAllOutputMetaRow struct {
	ID         pgtype.UUID
	ParentID   pgtype.UUID
	Title      string
	SeoIndexed bool
	UpdatedAt  pgtype.Timestamptz
}

// 全量 meta(无 body、无 limit):sitemap 枚举所有 indexed output + landing 的树路径
// 派生用。不带 newest-N cap —— sitemap 必须列全,漏一条就是 SEO bug。带 updated_at
// 给 sitemap <lastmod>。
func (q *Queries) ListAllOutputMeta(ctx context.Context, ownerID pgtype.UUID) ([]ListAllOutputMetaRow, error) {
	rows, err := q.db.Query(ctx, listAllOutputMeta, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllOutputMetaRow
	for rows.Next() {
		var i ListAllOutputMetaRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Title,
			&i.SeoIndexed,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutputByOwner = `-- name: ListOutputByOwner :many
SELECT id, owner_id, parent_id, title, body, tags, source_wiki_ids, show_as_source, seo_description, seo_indexed, created_at, updated_at FROM output_entries
WHERE owner_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListOutputByOwnerParams struct {
	OwnerID pgtype.UUID
	Limit   int32
}

func (q *Queries) ListOutputByOwner(ctx context.Context, arg ListOutputByOwnerParams) ([]OutputEntry, error) {
	rows, err := q.db.Query(ctx, listOutputByOwner, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutputEntry
	for rows.Next() {
		var i OutputEntry
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Title,
			&i.Body,
			&i.Tags,
			&i.SourceWikiIds,
			&i.ShowAsSource,
			&i.SeoDescription,
			&i.SeoIndexed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutputChildren = `-- name: ListOutputChildren :many
SELECT o.id, o.parent_id, o.title, o.seo_indexed,
       EXISTS(SELECT 1 FROM output_entries c WHERE c.parent_id = o.id) AS has_children
FROM output_entries o
WHERE o.owner_id = $1
  AND (($2::uuid IS NULL AND o.parent_id IS NULL) OR o.parent_id = $2)
ORDER BY o.title ASC
LIMIT $3 OFFSET $4
`

type ListOutputChildrenParams struct {
	OwnerID pgtype.UUID
	Column2 pgtype.UUID
	Limit   int32
	Offset  int32
}

type ListOutputChildrenRow struct {
	ID          pgtype.UUID
	ParentID    pgtype.UUID
	Title       string
	SeoIndexed  bool
	HasChildren bool
}

// 懒加载一层:某 output 节点的直接子(meta only,不带 body);$2 NULL = 根层。翻页用
// limit/offset。镜像 ListWikiChildren —— output 跟 wiki 同构(都是带 parent_id 的树),
// 检索按 path 下钻解析靠它,不再特例 output。
func (q *Queries) ListOutputChildren(ctx context.Context, arg ListOutputChildrenParams) ([]ListOutputChildrenRow, error) {
	rows, err := q.db.Query(ctx, listOutputChildren,
		arg.OwnerID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutputChildrenRow
	for rows.Next() {
		var i ListOutputChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Title,
			&i.SeoIndexed,
			&i.HasChildren,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchOutputByOwner = `-- name: SearchOutputByOwner :many
SELECT id, parent_id, title, seo_indexed, left(body, 200) AS snippet
FROM output_entries
WHERE owner_id = $1
  AND to_tsvector('english',
        title || ' ' || body || ' ' || array_to_string(tags, ' '))
      @@ replace(plainto_tsquery('english', $2)::text, ' & ', ' | ')::tsquery
ORDER BY ts_rank(
        to_tsvector('english',
          title || ' ' || body || ' ' || array_to_string(tags, ' ')),
        replace(plainto_tsquery('english', $2)::text, ' & ', ' | ')::tsquery
      ) DESC, updated_at DESC
LIMIT $3 OFFSET $4
`

type SearchOutputByOwnerParams struct {
	OwnerID        pgtype.UUID
	PlaintoTsquery string
	Limit          int32
	Offset         int32
}

type SearchOutputByOwnerRow struct {
	ID         pgtype.UUID
	ParentID   pgtype.UUID
	Title      string
	SeoIndexed bool
	Snippet    string
}

// 全量关键词搜(DB 端 full-text);返 meta + snippet(**不返完整 body**),翻页。
// 镜像 SearchWikiByOwner:自然语言问句按 OR 命中任一词项(' & '→' | '),ts_rank 排序。
func (q *Queries) SearchOutputByOwner(ctx context.Context, arg SearchOutputByOwnerParams) ([]SearchOutputByOwnerRow, error) {
	rows, err := q.db.Query(ctx, searchOutputByOwner,
		arg.OwnerID,
		arg.PlaintoTsquery,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchOutputByOwnerRow
	for rows.Next() {
		var i SearchOutputByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Title,
			&i.SeoIndexed,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOutputTags = `-- name: SetOutputTags :exec
UPDATE output_entries SET tags = $3, updated_at = now() WHERE id = $1 AND owner_id = $2
`

type SetOutputTagsParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
	Tags    []string
}

func (q *Queries) SetOutputTags(ctx context.Context, arg SetOutputTagsParams) error {
	_, err := q.db.Exec(ctx, setOutputTags, arg.ID, arg.OwnerID, arg.Tags)
	return err
}

const updateOutputBody = `-- name: UpdateOutputBody :one
UPDATE output_entries
SET title = $3, body = $4, tags = $5, parent_id = $6, show_as_source = $7,
    updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, parent_id, title, body, tags, source_wiki_ids, show_as_source, seo_description, seo_indexed, created_at, updated_at
`

type UpdateOutputBodyParams struct {
	ID           pgtype.UUID
	OwnerID      pgtype.UUID
	Title        string
	Body         string
	Tags         []string
	ParentID     pgtype.UUID
	ShowAsSource bool
}

// admin "edit output" 入口；跟 UpdateWikiBody 同构。
func (q *Queries) UpdateOutputBody(ctx context.Context, arg UpdateOutputBodyParams) (OutputEntry, error) {
	row := q.db.QueryRow(ctx, updateOutputBody,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Body,
		arg.Tags,
		arg.ParentID,
		arg.ShowAsSource,
	)
	var i OutputEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.SourceWikiIds,
		&i.ShowAsSource,
		&i.SeoDescription,
		&i.SeoIndexed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOutputSEO = `-- name: UpdateOutputSEO :one
UPDATE output_entries
SET seo_description = $2, seo_indexed = $3, updated_at = now()
WHERE id = $1
RETURNING id, owner_id, parent_id, title, body, tags, source_wiki_ids, show_as_source, seo_description, seo_indexed, created_at, updated_at
`

type UpdateOutputSEOParams struct {
	ID             pgtype.UUID
	SeoDescription string
	SeoIndexed     bool
}

// admin / MCP 编辑 SEO 描述 + indexed 开关（地址树派生,无 path 列）。
func (q *Queries) UpdateOutputSEO(ctx context.Context, arg UpdateOutputSEOParams) (OutputEntry, error) {
	row := q.db.QueryRow(ctx, updateOutputSEO, arg.ID, arg.SeoDescription, arg.SeoIndexed)
	var i OutputEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.SourceWikiIds,
		&i.ShowAsSource,
		&i.SeoDescription,
		&i.SeoIndexed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
