// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: output.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutputEntry = `-- name: CreateOutputEntry :one

INSERT INTO output_entries (
    owner_id, parent_id, title, body, tags, source_wiki_ids
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, parent_id, title, body, tags, source_wiki_ids, show_as_source, seo_description, seo_indexed, created_at, updated_at
`

type CreateOutputEntryParams struct {
	OwnerID       pgtype.UUID
	ParentID      pgtype.UUID
	Title         string
	Body          string
	Tags          []string
	SourceWikiIds []pgtype.UUID
}

// output_entries —— wiki 的最精炼版镜像。query 命名跟 wiki 对齐让代码生成
// 的方法名易认（CreateOutputEntry / ListOutputByOwner / ...）。
func (q *Queries) CreateOutputEntry(ctx context.Context, arg CreateOutputEntryParams) (OutputEntry, error) {
	row := q.db.QueryRow(ctx, createOutputEntry,
		arg.OwnerID,
		arg.ParentID,
		arg.Title,
		arg.Body,
		arg.Tags,
		arg.SourceWikiIds,
	)
	var i OutputEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.SourceWikiIds,
		&i.ShowAsSource,
		&i.SeoDescription,
		&i.SeoIndexed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOutput = `-- name: DeleteOutput :exec
DELETE FROM output_entries WHERE id = $1 AND owner_id = $2
`

type DeleteOutputParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) DeleteOutput(ctx context.Context, arg DeleteOutputParams) error {
	_, err := q.db.Exec(ctx, deleteOutput, arg.ID, arg.OwnerID)
	return err
}

const getOutputByID = `-- name: GetOutputByID :one
SELECT id, owner_id, parent_id, title, body, tags, source_wiki_ids, show_as_source, seo_description, seo_indexed, created_at, updated_at FROM output_entries WHERE id = $1 AND owner_id = $2
`

type GetOutputByIDParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetOutputByID(ctx context.Context, arg GetOutputByIDParams) (OutputEntry, error) {
	row := q.db.QueryRow(ctx, getOutputByID, arg.ID, arg.OwnerID)
	var i OutputEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.SourceWikiIds,
		&i.ShowAsSource,
		&i.SeoDescription,
		&i.SeoIndexed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOutputByOwner = `-- name: ListOutputByOwner :many
SELECT id, owner_id, parent_id, title, body, tags, source_wiki_ids, show_as_source, seo_description, seo_indexed, created_at, updated_at FROM output_entries
WHERE owner_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListOutputByOwnerParams struct {
	OwnerID pgtype.UUID
	Limit   int32
}

func (q *Queries) ListOutputByOwner(ctx context.Context, arg ListOutputByOwnerParams) ([]OutputEntry, error) {
	rows, err := q.db.Query(ctx, listOutputByOwner, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutputEntry
	for rows.Next() {
		var i OutputEntry
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ParentID,
			&i.Title,
			&i.Body,
			&i.Tags,
			&i.SourceWikiIds,
			&i.ShowAsSource,
			&i.SeoDescription,
			&i.SeoIndexed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOutputTags = `-- name: SetOutputTags :exec
UPDATE output_entries SET tags = $3, updated_at = now() WHERE id = $1 AND owner_id = $2
`

type SetOutputTagsParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
	Tags    []string
}

func (q *Queries) SetOutputTags(ctx context.Context, arg SetOutputTagsParams) error {
	_, err := q.db.Exec(ctx, setOutputTags, arg.ID, arg.OwnerID, arg.Tags)
	return err
}

const updateOutputBody = `-- name: UpdateOutputBody :one
UPDATE output_entries
SET title = $3, body = $4, tags = $5, parent_id = $6, show_as_source = $7,
    updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, parent_id, title, body, tags, source_wiki_ids, show_as_source, seo_description, seo_indexed, created_at, updated_at
`

type UpdateOutputBodyParams struct {
	ID           pgtype.UUID
	OwnerID      pgtype.UUID
	Title        string
	Body         string
	Tags         []string
	ParentID     pgtype.UUID
	ShowAsSource bool
}

// admin "edit output" 入口；跟 UpdateWikiBody 同构。
func (q *Queries) UpdateOutputBody(ctx context.Context, arg UpdateOutputBodyParams) (OutputEntry, error) {
	row := q.db.QueryRow(ctx, updateOutputBody,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Body,
		arg.Tags,
		arg.ParentID,
		arg.ShowAsSource,
	)
	var i OutputEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.SourceWikiIds,
		&i.ShowAsSource,
		&i.SeoDescription,
		&i.SeoIndexed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOutputSEO = `-- name: UpdateOutputSEO :one
UPDATE output_entries
SET seo_description = $2, seo_indexed = $3, updated_at = now()
WHERE id = $1
RETURNING id, owner_id, parent_id, title, body, tags, source_wiki_ids, show_as_source, seo_description, seo_indexed, created_at, updated_at
`

type UpdateOutputSEOParams struct {
	ID             pgtype.UUID
	SeoDescription string
	SeoIndexed     bool
}

// admin / MCP 编辑 SEO 描述 + indexed 开关（地址树派生,无 path 列）。
func (q *Queries) UpdateOutputSEO(ctx context.Context, arg UpdateOutputSEOParams) (OutputEntry, error) {
	row := q.db.QueryRow(ctx, updateOutputSEO, arg.ID, arg.SeoDescription, arg.SeoIndexed)
	var i OutputEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.SourceWikiIds,
		&i.ShowAsSource,
		&i.SeoDescription,
		&i.SeoIndexed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
