// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: owners.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOwners = `-- name: CountOwners :one
SELECT COUNT(*) FROM owners
`

func (q *Queries) CountOwners(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOwner = `-- name: CreateOwner :one
INSERT INTO owners (email, password_hash, handle, full_name)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, handle, full_name, location, custom_domain, custom_domain_status, byoai_enabled, byoai_providers, byoai_public_blurb, created_at
`

type CreateOwnerParams struct {
	Email        string
	PasswordHash string
	Handle       string
	FullName     string
}

func (q *Queries) CreateOwner(ctx context.Context, arg CreateOwnerParams) (Owner, error) {
	row := q.db.QueryRow(ctx, createOwner,
		arg.Email,
		arg.PasswordHash,
		arg.Handle,
		arg.FullName,
	)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.CustomDomain,
		&i.CustomDomainStatus,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.CreatedAt,
	)
	return i, err
}

const getFirstOwnerHandle = `-- name: GetFirstOwnerHandle :one
SELECT handle FROM owners ORDER BY created_at ASC LIMIT 1
`

// v1 单 owner instance：返回最早创建那位的 handle；app 根路径用来跳转。
func (q *Queries) GetFirstOwnerHandle(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getFirstOwnerHandle)
	var handle string
	err := row.Scan(&handle)
	return handle, err
}

const getOwnerByEmail = `-- name: GetOwnerByEmail :one
SELECT id, email, password_hash, handle, full_name, location, custom_domain, custom_domain_status, byoai_enabled, byoai_providers, byoai_public_blurb, created_at FROM owners WHERE email = $1
`

func (q *Queries) GetOwnerByEmail(ctx context.Context, email string) (Owner, error) {
	row := q.db.QueryRow(ctx, getOwnerByEmail, email)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.CustomDomain,
		&i.CustomDomainStatus,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.CreatedAt,
	)
	return i, err
}

const getOwnerByHandle = `-- name: GetOwnerByHandle :one
SELECT id, email, password_hash, handle, full_name, location, custom_domain, custom_domain_status, byoai_enabled, byoai_providers, byoai_public_blurb, created_at FROM owners WHERE handle = $1
`

func (q *Queries) GetOwnerByHandle(ctx context.Context, handle string) (Owner, error) {
	row := q.db.QueryRow(ctx, getOwnerByHandle, handle)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.CustomDomain,
		&i.CustomDomainStatus,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.CreatedAt,
	)
	return i, err
}

const getOwnerByID = `-- name: GetOwnerByID :one
SELECT id, email, password_hash, handle, full_name, location, custom_domain, custom_domain_status, byoai_enabled, byoai_providers, byoai_public_blurb, created_at FROM owners WHERE id = $1
`

func (q *Queries) GetOwnerByID(ctx context.Context, id pgtype.UUID) (Owner, error) {
	row := q.db.QueryRow(ctx, getOwnerByID, id)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.CustomDomain,
		&i.CustomDomainStatus,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.CreatedAt,
	)
	return i, err
}

const updateOwnerBYOAI = `-- name: UpdateOwnerBYOAI :one
UPDATE owners
SET byoai_enabled = $2,
    byoai_providers = $3,
    byoai_public_blurb = $4
WHERE id = $1
RETURNING id, email, password_hash, handle, full_name, location, custom_domain, custom_domain_status, byoai_enabled, byoai_providers, byoai_public_blurb, created_at
`

type UpdateOwnerBYOAIParams struct {
	ID               pgtype.UUID
	ByoaiEnabled     bool
	ByoaiProviders   []byte
	ByoaiPublicBlurb string
}

func (q *Queries) UpdateOwnerBYOAI(ctx context.Context, arg UpdateOwnerBYOAIParams) (Owner, error) {
	row := q.db.QueryRow(ctx, updateOwnerBYOAI,
		arg.ID,
		arg.ByoaiEnabled,
		arg.ByoaiProviders,
		arg.ByoaiPublicBlurb,
	)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.CustomDomain,
		&i.CustomDomainStatus,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.CreatedAt,
	)
	return i, err
}
