// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: owner_connectors.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearConnectorTokens = `-- name: ClearConnectorTokens :exec
UPDATE owner_connectors
SET token_enc = '\x'::bytea, token_expires_at = NULL,
    connected_at = NULL, active = false, updated_at = now()
WHERE owner_id = $1 AND connector_id = $2
`

type ClearConnectorTokensParams struct {
	OwnerID     pgtype.UUID
	ConnectorID string
}

// soft disconnect：擦 token + connected + active，保留 credentials（一键重连不重填）。
func (q *Queries) ClearConnectorTokens(ctx context.Context, arg ClearConnectorTokensParams) error {
	_, err := q.db.Exec(ctx, clearConnectorTokens, arg.OwnerID, arg.ConnectorID)
	return err
}

const deleteConnector = `-- name: DeleteConnector :exec
DELETE FROM owner_connectors
WHERE owner_id = $1 AND connector_id = $2
`

type DeleteConnectorParams struct {
	OwnerID     pgtype.UUID
	ConnectorID string
}

func (q *Queries) DeleteConnector(ctx context.Context, arg DeleteConnectorParams) error {
	_, err := q.db.Exec(ctx, deleteConnector, arg.OwnerID, arg.ConnectorID)
	return err
}

const getConnector = `-- name: GetConnector :one
SELECT id, owner_id, connector_id, category, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, created_at, updated_at FROM owner_connectors
WHERE owner_id = $1 AND connector_id = $2
`

type GetConnectorParams struct {
	OwnerID     pgtype.UUID
	ConnectorID string
}

func (q *Queries) GetConnector(ctx context.Context, arg GetConnectorParams) (OwnerConnector, error) {
	row := q.db.QueryRow(ctx, getConnector, arg.OwnerID, arg.ConnectorID)
	var i OwnerConnector
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConnectorID,
		&i.Category,
		&i.Kind,
		&i.CredentialsEnc,
		&i.TokenEnc,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.ConnectedAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnectorsByCategory = `-- name: ListConnectorsByCategory :many
SELECT id, owner_id, connector_id, category, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, created_at, updated_at FROM owner_connectors
WHERE owner_id = $1 AND category = $2
ORDER BY connector_id
`

type ListConnectorsByCategoryParams struct {
	OwnerID  pgtype.UUID
	Category string
}

func (q *Queries) ListConnectorsByCategory(ctx context.Context, arg ListConnectorsByCategoryParams) ([]OwnerConnector, error) {
	rows, err := q.db.Query(ctx, listConnectorsByCategory, arg.OwnerID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnerConnector
	for rows.Next() {
		var i OwnerConnector
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ConnectorID,
			&i.Category,
			&i.Kind,
			&i.CredentialsEnc,
			&i.TokenEnc,
			&i.TokenExpiresAt,
			&i.Scopes,
			&i.ConnectedAt,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectorsByOwner = `-- name: ListConnectorsByOwner :many
SELECT id, owner_id, connector_id, category, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, created_at, updated_at FROM owner_connectors
WHERE owner_id = $1
ORDER BY category, connector_id
`

func (q *Queries) ListConnectorsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]OwnerConnector, error) {
	rows, err := q.db.Query(ctx, listConnectorsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnerConnector
	for rows.Next() {
		var i OwnerConnector
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ConnectorID,
			&i.Category,
			&i.Kind,
			&i.CredentialsEnc,
			&i.TokenEnc,
			&i.TokenExpiresAt,
			&i.Scopes,
			&i.ConnectedAt,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConnectorConnected = `-- name: MarkConnectorConnected :exec
UPDATE owner_connectors
SET connected_at = COALESCE(connected_at, now()), updated_at = now()
WHERE owner_id = $1 AND connector_id = $2
`

type MarkConnectorConnectedParams struct {
	OwnerID     pgtype.UUID
	ConnectorID string
}

// protocol 连接器验证通过（无 oauth dance）→ 标记 connected。
func (q *Queries) MarkConnectorConnected(ctx context.Context, arg MarkConnectorConnectedParams) error {
	_, err := q.db.Exec(ctx, markConnectorConnected, arg.OwnerID, arg.ConnectorID)
	return err
}

const setActiveConnector = `-- name: SetActiveConnector :exec
UPDATE owner_connectors
SET active = (connector_id = $1::text), updated_at = now()
WHERE owner_id = $2 AND category = $3
`

type SetActiveConnectorParams struct {
	ConnectorID string
	OwnerID     pgtype.UUID
	Category    string
}

// 一个品类槽同时只一个 active：把目标置 active、同品类其余置非 active（§9 槽位规则）。
func (q *Queries) SetActiveConnector(ctx context.Context, arg SetActiveConnectorParams) error {
	_, err := q.db.Exec(ctx, setActiveConnector, arg.ConnectorID, arg.OwnerID, arg.Category)
	return err
}

const updateConnectorTokens = `-- name: UpdateConnectorTokens :one
UPDATE owner_connectors
SET token_enc = $1::bytea,
    token_expires_at = $2::timestamptz,
    scopes = $3::jsonb,
    connected_at = COALESCE(connected_at, now()),
    updated_at = now()
WHERE owner_id = $4 AND connector_id = $5
RETURNING id, owner_id, connector_id, category, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, created_at, updated_at
`

type UpdateConnectorTokensParams struct {
	TokenEnc       []byte
	TokenExpiresAt pgtype.Timestamptz
	Scopes         []byte
	OwnerID        pgtype.UUID
	ConnectorID    string
}

// OAuth 拿到首次 token，或 refresh 路径拿到新 access_token。首次拿到 token → connected。
func (q *Queries) UpdateConnectorTokens(ctx context.Context, arg UpdateConnectorTokensParams) (OwnerConnector, error) {
	row := q.db.QueryRow(ctx, updateConnectorTokens,
		arg.TokenEnc,
		arg.TokenExpiresAt,
		arg.Scopes,
		arg.OwnerID,
		arg.ConnectorID,
	)
	var i OwnerConnector
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConnectorID,
		&i.Category,
		&i.Kind,
		&i.CredentialsEnc,
		&i.TokenEnc,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.ConnectedAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConnectorCredentials = `-- name: UpsertConnectorCredentials :one

INSERT INTO owner_connectors (
    owner_id, connector_id, category, kind, credentials_enc
)
VALUES (
    $1, $2, $3,
    $4, $5::bytea
)
ON CONFLICT (owner_id, connector_id) DO UPDATE
SET credentials_enc = EXCLUDED.credentials_enc,
    category = EXCLUDED.category,
    kind = EXCLUDED.kind,
    updated_at = now()
RETURNING id, owner_id, connector_id, category, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, created_at, updated_at
`

type UpsertConnectorCredentialsParams struct {
	OwnerID        pgtype.UUID
	ConnectorID    string
	Category       string
	Kind           string
	CredentialsEnc []byte
}

// owner_connectors.sql —— #155 统一连接器连接状态的读写（归一：任意 kind/品类一张表）。
// 存/覆盖一个连接器的凭据（owner 填的 app creds / apiKey / smtp config）。改 creds 不动
// 已有 token（owner 要 reset 走 Disconnect）。category/kind 随首次写入定。
func (q *Queries) UpsertConnectorCredentials(ctx context.Context, arg UpsertConnectorCredentialsParams) (OwnerConnector, error) {
	row := q.db.QueryRow(ctx, upsertConnectorCredentials,
		arg.OwnerID,
		arg.ConnectorID,
		arg.Category,
		arg.Kind,
		arg.CredentialsEnc,
	)
	var i OwnerConnector
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConnectorID,
		&i.Category,
		&i.Kind,
		&i.CredentialsEnc,
		&i.TokenEnc,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.ConnectedAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
