// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: posts.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    owner_id, slug, title, excerpt, body_md,
    cover_headline, cover_sub, cover_hue, cover_image_asset_id,
    tags, visibility, cross_refs, path, read_minutes, locked_body,
    published_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15,
    $16
)
RETURNING id, owner_id, slug, title, excerpt, body_md,
          cover_headline, cover_sub, cover_hue, cover_image_asset_id,
          tags, visibility, cross_refs, path, read_minutes, locked_body,
          obsidian_source_path, obsidian_imported_at,
          published_at, created_at, updated_at
`

type CreatePostParams struct {
	OwnerID           pgtype.UUID
	Slug              string
	Title             string
	Excerpt           string
	BodyMd            string
	CoverHeadline     string
	CoverSub          string
	CoverHue          string
	CoverImageAssetID pgtype.UUID
	Tags              []string
	Visibility        string
	CrossRefs         []string
	Path              string
	ReadMinutes       int32
	LockedBody        string
	PublishedAt       pgtype.Timestamptz
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.OwnerID,
		arg.Slug,
		arg.Title,
		arg.Excerpt,
		arg.BodyMd,
		arg.CoverHeadline,
		arg.CoverSub,
		arg.CoverHue,
		arg.CoverImageAssetID,
		arg.Tags,
		arg.Visibility,
		arg.CrossRefs,
		arg.Path,
		arg.ReadMinutes,
		arg.LockedBody,
		arg.PublishedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.BodyMd,
		&i.CoverHeadline,
		&i.CoverSub,
		&i.CoverHue,
		&i.CoverImageAssetID,
		&i.Tags,
		&i.Visibility,
		&i.CrossRefs,
		&i.Path,
		&i.ReadMinutes,
		&i.LockedBody,
		&i.ObsidianSourcePath,
		&i.ObsidianImportedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1 AND owner_id = $2
`

type DeletePostParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) error {
	_, err := q.db.Exec(ctx, deletePost, arg.ID, arg.OwnerID)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, owner_id, slug, title, excerpt, body_md,
       cover_headline, cover_sub, cover_hue, cover_image_asset_id,
       tags, visibility, cross_refs, path, read_minutes, locked_body,
       obsidian_source_path, obsidian_imported_at,
       published_at, created_at, updated_at
FROM posts WHERE id = $1 AND owner_id = $2
`

type GetPostByIDParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetPostByID(ctx context.Context, arg GetPostByIDParams) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, arg.ID, arg.OwnerID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.BodyMd,
		&i.CoverHeadline,
		&i.CoverSub,
		&i.CoverHue,
		&i.CoverImageAssetID,
		&i.Tags,
		&i.Visibility,
		&i.CrossRefs,
		&i.Path,
		&i.ReadMinutes,
		&i.LockedBody,
		&i.ObsidianSourcePath,
		&i.ObsidianImportedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostByObsidianSourcePath = `-- name: GetPostByObsidianSourcePath :one
SELECT id, owner_id, slug, title, excerpt, body_md,
       cover_headline, cover_sub, cover_hue, cover_image_asset_id,
       tags, visibility, cross_refs, path, read_minutes, locked_body,
       obsidian_source_path, obsidian_imported_at,
       published_at, created_at, updated_at
FROM posts WHERE owner_id = $1 AND obsidian_source_path = $2
`

type GetPostByObsidianSourcePathParams struct {
	OwnerID            pgtype.UUID
	ObsidianSourcePath string
}

func (q *Queries) GetPostByObsidianSourcePath(ctx context.Context, arg GetPostByObsidianSourcePathParams) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByObsidianSourcePath, arg.OwnerID, arg.ObsidianSourcePath)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.BodyMd,
		&i.CoverHeadline,
		&i.CoverSub,
		&i.CoverHue,
		&i.CoverImageAssetID,
		&i.Tags,
		&i.Visibility,
		&i.CrossRefs,
		&i.Path,
		&i.ReadMinutes,
		&i.LockedBody,
		&i.ObsidianSourcePath,
		&i.ObsidianImportedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostBySlug = `-- name: GetPostBySlug :one
SELECT id, owner_id, slug, title, excerpt, body_md,
       cover_headline, cover_sub, cover_hue, cover_image_asset_id,
       tags, visibility, cross_refs, path, read_minutes, locked_body,
       obsidian_source_path, obsidian_imported_at,
       published_at, created_at, updated_at
FROM posts WHERE owner_id = $1 AND slug = $2
`

type GetPostBySlugParams struct {
	OwnerID pgtype.UUID
	Slug    string
}

func (q *Queries) GetPostBySlug(ctx context.Context, arg GetPostBySlugParams) (Post, error) {
	row := q.db.QueryRow(ctx, getPostBySlug, arg.OwnerID, arg.Slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.BodyMd,
		&i.CoverHeadline,
		&i.CoverSub,
		&i.CoverHue,
		&i.CoverImageAssetID,
		&i.Tags,
		&i.Visibility,
		&i.CrossRefs,
		&i.Path,
		&i.ReadMinutes,
		&i.LockedBody,
		&i.ObsidianSourcePath,
		&i.ObsidianImportedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPostsByOwner = `-- name: ListPostsByOwner :many
SELECT id, owner_id, slug, title, excerpt, body_md,
       cover_headline, cover_sub, cover_hue, cover_image_asset_id,
       tags, visibility, cross_refs, path, read_minutes, locked_body,
       obsidian_source_path, obsidian_imported_at,
       published_at, created_at, updated_at
FROM posts
WHERE owner_id = $1
ORDER BY COALESCE(published_at, created_at) DESC
`

func (q *Queries) ListPostsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPostsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.BodyMd,
			&i.CoverHeadline,
			&i.CoverSub,
			&i.CoverHue,
			&i.CoverImageAssetID,
			&i.Tags,
			&i.Visibility,
			&i.CrossRefs,
			&i.Path,
			&i.ReadMinutes,
			&i.LockedBody,
			&i.ObsidianSourcePath,
			&i.ObsidianImportedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPostsByOwner = `-- name: ListPublishedPostsByOwner :many
SELECT id, owner_id, slug, title, excerpt, body_md,
       cover_headline, cover_sub, cover_hue, cover_image_asset_id,
       tags, visibility, cross_refs, path, read_minutes, locked_body,
       obsidian_source_path, obsidian_imported_at,
       published_at, created_at, updated_at
FROM posts
WHERE owner_id = $1 AND published_at IS NOT NULL
ORDER BY published_at DESC
`

func (q *Queries) ListPublishedPostsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPublishedPostsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.BodyMd,
			&i.CoverHeadline,
			&i.CoverSub,
			&i.CoverHue,
			&i.CoverImageAssetID,
			&i.Tags,
			&i.Visibility,
			&i.CrossRefs,
			&i.Path,
			&i.ReadMinutes,
			&i.LockedBody,
			&i.ObsidianSourcePath,
			&i.ObsidianImportedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPostsByOwnerPage = `-- name: ListPublishedPostsByOwnerPage :many
SELECT id, owner_id, slug, title, excerpt, body_md,
       cover_headline, cover_sub, cover_hue, cover_image_asset_id,
       tags, visibility, cross_refs, path, read_minutes, locked_body,
       obsidian_source_path, obsidian_imported_at,
       published_at, created_at, updated_at
FROM posts
WHERE owner_id = $1
  AND published_at IS NOT NULL
  AND ($2::timestamptz IS NULL OR published_at < $2::timestamptz)
ORDER BY published_at DESC
LIMIT $3
`

type ListPublishedPostsByOwnerPageParams struct {
	OwnerID pgtype.UUID
	Column2 pgtype.Timestamptz
	Limit   int32
}

// 分页 infinite scroll：cursor = 上一页最末 post.published_at (RFC3339)，
// 第一页 cursor 传 NULL 拿最新 N 条。返 LIMIT+1 让 caller 判断 has_more。
func (q *Queries) ListPublishedPostsByOwnerPage(ctx context.Context, arg ListPublishedPostsByOwnerPageParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPublishedPostsByOwnerPage, arg.OwnerID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.BodyMd,
			&i.CoverHeadline,
			&i.CoverSub,
			&i.CoverHue,
			&i.CoverImageAssetID,
			&i.Tags,
			&i.Visibility,
			&i.CrossRefs,
			&i.Path,
			&i.ReadMinutes,
			&i.LockedBody,
			&i.ObsidianSourcePath,
			&i.ObsidianImportedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedSlugAndTitle = `-- name: ListPublishedSlugAndTitle :many
SELECT slug, title
FROM posts
WHERE owner_id = $1 AND published_at IS NOT NULL
ORDER BY slug ASC
`

type ListPublishedSlugAndTitleRow struct {
	Slug  string
	Title string
}

// /blog 渲染 [[wikilink]] 时用：拉 owner 所有 published post 的 slug + title
// 当 resolution index，不带 body_md（避免 N+1 那种全 body 重传开销）。
func (q *Queries) ListPublishedSlugAndTitle(ctx context.Context, ownerID pgtype.UUID) ([]ListPublishedSlugAndTitleRow, error) {
	rows, err := q.db.Query(ctx, listPublishedSlugAndTitle, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedSlugAndTitleRow
	for rows.Next() {
		var i ListPublishedSlugAndTitleRow
		if err := rows.Scan(&i.Slug, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishPost = `-- name: PublishPost :one
UPDATE posts SET published_at = now(), updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, slug, title, excerpt, body_md,
          cover_headline, cover_sub, cover_hue, cover_image_asset_id,
          tags, visibility, cross_refs, path, read_minutes, locked_body,
          obsidian_source_path, obsidian_imported_at,
          published_at, created_at, updated_at
`

type PublishPostParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) PublishPost(ctx context.Context, arg PublishPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, publishPost, arg.ID, arg.OwnerID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.BodyMd,
		&i.CoverHeadline,
		&i.CoverSub,
		&i.CoverHue,
		&i.CoverImageAssetID,
		&i.Tags,
		&i.Visibility,
		&i.CrossRefs,
		&i.Path,
		&i.ReadMinutes,
		&i.LockedBody,
		&i.ObsidianSourcePath,
		&i.ObsidianImportedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPostObsidianMeta = `-- name: SetPostObsidianMeta :exec
UPDATE posts
SET obsidian_source_path = $3,
    obsidian_imported_at = now(),
    updated_at = now()
WHERE id = $1 AND owner_id = $2
`

type SetPostObsidianMetaParams struct {
	ID                 pgtype.UUID
	OwnerID            pgtype.UUID
	ObsidianSourcePath string
}

// Obsidian import 走完 SavePost 之后调用：标记这行 post 是从 vault 来的，
// 顺便记 imported_at = now()。re-import 时根据 updated_at vs imported_at 决
// 定 skip / overwrite（owner 在 web 改过了 updated_at 会跳过 imported_at）。
func (q *Queries) SetPostObsidianMeta(ctx context.Context, arg SetPostObsidianMetaParams) error {
	_, err := q.db.Exec(ctx, setPostObsidianMeta, arg.ID, arg.OwnerID, arg.ObsidianSourcePath)
	return err
}

const unpublishPost = `-- name: UnpublishPost :one
UPDATE posts SET published_at = NULL, updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, slug, title, excerpt, body_md,
          cover_headline, cover_sub, cover_hue, cover_image_asset_id,
          tags, visibility, cross_refs, path, read_minutes, locked_body,
          obsidian_source_path, obsidian_imported_at,
          published_at, created_at, updated_at
`

type UnpublishPostParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) UnpublishPost(ctx context.Context, arg UnpublishPostParams) (Post, error) {
	row := q.db.QueryRow(ctx, unpublishPost, arg.ID, arg.OwnerID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.BodyMd,
		&i.CoverHeadline,
		&i.CoverSub,
		&i.CoverHue,
		&i.CoverImageAssetID,
		&i.Tags,
		&i.Visibility,
		&i.CrossRefs,
		&i.Path,
		&i.ReadMinutes,
		&i.LockedBody,
		&i.ObsidianSourcePath,
		&i.ObsidianImportedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts SET
    title = $3, excerpt = $4, body_md = $5,
    cover_headline = $6, cover_sub = $7, cover_hue = $8, cover_image_asset_id = $9,
    tags = $10, visibility = $11, cross_refs = $12, path = $13,
    read_minutes = $14, locked_body = $15,
    updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, slug, title, excerpt, body_md,
          cover_headline, cover_sub, cover_hue, cover_image_asset_id,
          tags, visibility, cross_refs, path, read_minutes, locked_body,
          obsidian_source_path, obsidian_imported_at,
          published_at, created_at, updated_at
`

type UpdatePostParams struct {
	ID                pgtype.UUID
	OwnerID           pgtype.UUID
	Title             string
	Excerpt           string
	BodyMd            string
	CoverHeadline     string
	CoverSub          string
	CoverHue          string
	CoverImageAssetID pgtype.UUID
	Tags              []string
	Visibility        string
	CrossRefs         []string
	Path              string
	ReadMinutes       int32
	LockedBody        string
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Excerpt,
		arg.BodyMd,
		arg.CoverHeadline,
		arg.CoverSub,
		arg.CoverHue,
		arg.CoverImageAssetID,
		arg.Tags,
		arg.Visibility,
		arg.CrossRefs,
		arg.Path,
		arg.ReadMinutes,
		arg.LockedBody,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.BodyMd,
		&i.CoverHeadline,
		&i.CoverSub,
		&i.CoverHue,
		&i.CoverImageAssetID,
		&i.Tags,
		&i.Visibility,
		&i.CrossRefs,
		&i.Path,
		&i.ReadMinutes,
		&i.LockedBody,
		&i.ObsidianSourcePath,
		&i.ObsidianImportedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
