// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: seo.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSEOSettings = `-- name: GetSEOSettings :one
SELECT owner_id, index_robots, sitemap_extras, og_template, updated_at
FROM seo_settings
WHERE owner_id = $1
`

func (q *Queries) GetSEOSettings(ctx context.Context, ownerID pgtype.UUID) (SeoSetting, error) {
	row := q.db.QueryRow(ctx, getSEOSettings, ownerID)
	var i SeoSetting
	err := row.Scan(
		&i.OwnerID,
		&i.IndexRobots,
		&i.SitemapExtras,
		&i.OgTemplate,
		&i.UpdatedAt,
	)
	return i, err
}

const getWikiBySlug = `-- name: GetWikiBySlug :one
SELECT id, owner_id, parent_id, title, body, tags, visibility,
       source_raw_ids, seo_slug, seo_description, seo_indexed,
       created_at, updated_at
FROM wiki_entries
WHERE owner_id = $1 AND seo_slug = $2 AND visibility = 'public'
`

type GetWikiBySlugParams struct {
	OwnerID pgtype.UUID
	SeoSlug *string
}

// 用 owner_id + seo_slug 反查 wiki entry（public-facing wiki landing）。
func (q *Queries) GetWikiBySlug(ctx context.Context, arg GetWikiBySlugParams) (WikiEntry, error) {
	row := q.db.QueryRow(ctx, getWikiBySlug, arg.OwnerID, arg.SeoSlug)
	var i WikiEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.Visibility,
		&i.SourceRawIds,
		&i.SeoSlug,
		&i.SeoDescription,
		&i.SeoIndexed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIndexedWikiSlugs = `-- name: ListIndexedWikiSlugs :many
SELECT seo_slug, updated_at
FROM wiki_entries
WHERE owner_id = $1
  AND seo_slug IS NOT NULL
  AND seo_indexed = true
  AND visibility = 'public'
ORDER BY updated_at DESC
`

type ListIndexedWikiSlugsRow struct {
	SeoSlug   *string
	UpdatedAt pgtype.Timestamptz
}

// sitemap.xml 用：取该 owner 所有 indexed + public 的 wiki landing slug。
func (q *Queries) ListIndexedWikiSlugs(ctx context.Context, ownerID pgtype.UUID) ([]ListIndexedWikiSlugsRow, error) {
	rows, err := q.db.Query(ctx, listIndexedWikiSlugs, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIndexedWikiSlugsRow
	for rows.Next() {
		var i ListIndexedWikiSlugsRow
		if err := rows.Scan(&i.SeoSlug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWikiSEO = `-- name: UpdateWikiSEO :one
UPDATE wiki_entries
SET seo_slug        = $2,
    seo_description = $3,
    seo_indexed     = $4,
    updated_at      = now()
WHERE id = $1
RETURNING id, owner_id, parent_id, title, body, tags, visibility,
          source_raw_ids, seo_slug, seo_description, seo_indexed,
          created_at, updated_at
`

type UpdateWikiSEOParams struct {
	ID             pgtype.UUID
	SeoSlug        *string
	SeoDescription string
	SeoIndexed     bool
}

// admin / MCP 设 wiki 的 seo_slug / seo_description / seo_indexed。
func (q *Queries) UpdateWikiSEO(ctx context.Context, arg UpdateWikiSEOParams) (WikiEntry, error) {
	row := q.db.QueryRow(ctx, updateWikiSEO,
		arg.ID,
		arg.SeoSlug,
		arg.SeoDescription,
		arg.SeoIndexed,
	)
	var i WikiEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.Visibility,
		&i.SourceRawIds,
		&i.SeoSlug,
		&i.SeoDescription,
		&i.SeoIndexed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSEOSettings = `-- name: UpsertSEOSettings :one
INSERT INTO seo_settings (owner_id, index_robots, sitemap_extras, og_template, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (owner_id) DO UPDATE SET
    index_robots   = EXCLUDED.index_robots,
    sitemap_extras = EXCLUDED.sitemap_extras,
    og_template    = EXCLUDED.og_template,
    updated_at     = now()
RETURNING owner_id, index_robots, sitemap_extras, og_template, updated_at
`

type UpsertSEOSettingsParams struct {
	OwnerID       pgtype.UUID
	IndexRobots   bool
	SitemapExtras []byte
	OgTemplate    string
}

func (q *Queries) UpsertSEOSettings(ctx context.Context, arg UpsertSEOSettingsParams) (SeoSetting, error) {
	row := q.db.QueryRow(ctx, upsertSEOSettings,
		arg.OwnerID,
		arg.IndexRobots,
		arg.SitemapExtras,
		arg.OgTemplate,
	)
	var i SeoSetting
	err := row.Scan(
		&i.OwnerID,
		&i.IndexRobots,
		&i.SitemapExtras,
		&i.OgTemplate,
		&i.UpdatedAt,
	)
	return i, err
}
