// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: seo.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSEOSettings = `-- name: GetSEOSettings :one
SELECT owner_id, index_robots, sitemap_extras, og_template, updated_at
FROM seo_settings
WHERE owner_id = $1
`

func (q *Queries) GetSEOSettings(ctx context.Context, ownerID pgtype.UUID) (SeoSetting, error) {
	row := q.db.QueryRow(ctx, getSEOSettings, ownerID)
	var i SeoSetting
	err := row.Scan(
		&i.OwnerID,
		&i.IndexRobots,
		&i.SitemapExtras,
		&i.OgTemplate,
		&i.UpdatedAt,
	)
	return i, err
}

const getWikiByPath = `-- name: GetWikiByPath :one
SELECT id, owner_id, parent_id, title, body, tags, source_raw_ids, path, show_as_source, seo_description, seo_indexed, created_at, updated_at
FROM wiki_entries
WHERE owner_id = $1 AND path = $2 AND seo_indexed = true
`

type GetWikiByPathParams struct {
	OwnerID pgtype.UUID
	Path    *string
}

// 用 owner_id + path 反查 wiki entry（公开 landing /<handle>/wiki/<path>）。
// 公开 landing 只暴露 seo_indexed=true 的 entry（crawler 友好可见）；
// 准入靠 retrieval ACL，跟公开 landing 是两个面。
func (q *Queries) GetWikiByPath(ctx context.Context, arg GetWikiByPathParams) (WikiEntry, error) {
	row := q.db.QueryRow(ctx, getWikiByPath, arg.OwnerID, arg.Path)
	var i WikiEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.SourceRawIds,
		&i.Path,
		&i.ShowAsSource,
		&i.SeoDescription,
		&i.SeoIndexed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIndexedWikiPaths = `-- name: ListIndexedWikiPaths :many
SELECT path, updated_at
FROM wiki_entries
WHERE owner_id = $1
  AND path IS NOT NULL
  AND seo_indexed = true
ORDER BY updated_at DESC
`

type ListIndexedWikiPathsRow struct {
	Path      *string
	UpdatedAt pgtype.Timestamptz
}

// sitemap.xml 用：取该 owner 所有 indexed wiki landing path。
func (q *Queries) ListIndexedWikiPaths(ctx context.Context, ownerID pgtype.UUID) ([]ListIndexedWikiPathsRow, error) {
	rows, err := q.db.Query(ctx, listIndexedWikiPaths, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIndexedWikiPathsRow
	for rows.Next() {
		var i ListIndexedWikiPathsRow
		if err := rows.Scan(&i.Path, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWikiPath = `-- name: UpdateWikiPath :one
UPDATE wiki_entries
SET path            = $2,
    seo_description = $3,
    seo_indexed     = $4,
    updated_at      = now()
WHERE id = $1
RETURNING id, owner_id, parent_id, title, body, tags, source_raw_ids, path, show_as_source, seo_description, seo_indexed, created_at, updated_at
`

type UpdateWikiPathParams struct {
	ID             pgtype.UUID
	Path           *string
	SeoDescription string
	SeoIndexed     bool
}

// admin / MCP 编辑 path + SEO 描述 + indexed 开关。
func (q *Queries) UpdateWikiPath(ctx context.Context, arg UpdateWikiPathParams) (WikiEntry, error) {
	row := q.db.QueryRow(ctx, updateWikiPath,
		arg.ID,
		arg.Path,
		arg.SeoDescription,
		arg.SeoIndexed,
	)
	var i WikiEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ParentID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.SourceRawIds,
		&i.Path,
		&i.ShowAsSource,
		&i.SeoDescription,
		&i.SeoIndexed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSEOSettings = `-- name: UpsertSEOSettings :one
INSERT INTO seo_settings (owner_id, index_robots, sitemap_extras, og_template, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (owner_id) DO UPDATE SET
    index_robots   = EXCLUDED.index_robots,
    sitemap_extras = EXCLUDED.sitemap_extras,
    og_template    = EXCLUDED.og_template,
    updated_at     = now()
RETURNING owner_id, index_robots, sitemap_extras, og_template, updated_at
`

type UpsertSEOSettingsParams struct {
	OwnerID       pgtype.UUID
	IndexRobots   bool
	SitemapExtras []byte
	OgTemplate    string
}

func (q *Queries) UpsertSEOSettings(ctx context.Context, arg UpsertSEOSettingsParams) (SeoSetting, error) {
	row := q.db.QueryRow(ctx, upsertSEOSettings,
		arg.OwnerID,
		arg.IndexRobots,
		arg.SitemapExtras,
		arg.OgTemplate,
	)
	var i SeoSetting
	err := row.Scan(
		&i.OwnerID,
		&i.IndexRobots,
		&i.SitemapExtras,
		&i.OgTemplate,
		&i.UpdatedAt,
	)
	return i, err
}
