// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: writings.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWriting = `-- name: CreateWriting :one
INSERT INTO writings (
    owner_id, slug, title, excerpt, body_md,
    cover_headline, cover_hue, cover_image_asset_id,
    tags, visibility, cross_refs, path, read_minutes, locked_body,
    published_at, parent_id
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12, $13, $14,
    $15, $16
)
RETURNING id, owner_id, slug, title, excerpt, body_md,
          cover_headline, cover_hue, cover_image_asset_id,
          tags, visibility, cross_refs, path, read_minutes, locked_body,
          obsidian_source_path, obsidian_imported_at,
          published_at, parent_id, created_at, updated_at
`

type CreateWritingParams struct {
	OwnerID           pgtype.UUID
	Slug              string
	Title             string
	Excerpt           string
	BodyMd            string
	CoverHeadline     string
	CoverHue          string
	CoverImageAssetID pgtype.UUID
	Tags              []string
	Visibility        string
	CrossRefs         []string
	Path              string
	ReadMinutes       int32
	LockedBody        string
	PublishedAt       pgtype.Timestamptz
	ParentID          pgtype.UUID
}

func (q *Queries) CreateWriting(ctx context.Context, arg CreateWritingParams) (Writing, error) {
	row := q.db.QueryRow(ctx, createWriting,
		arg.OwnerID,
		arg.Slug,
		arg.Title,
		arg.Excerpt,
		arg.BodyMd,
		arg.CoverHeadline,
		arg.CoverHue,
		arg.CoverImageAssetID,
		arg.Tags,
		arg.Visibility,
		arg.CrossRefs,
		arg.Path,
		arg.ReadMinutes,
		arg.LockedBody,
		arg.PublishedAt,
		arg.ParentID,
	)
	var i Writing
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.BodyMd,
		&i.CoverHeadline,
		&i.CoverHue,
		&i.CoverImageAssetID,
		&i.Tags,
		&i.Visibility,
		&i.CrossRefs,
		&i.Path,
		&i.ReadMinutes,
		&i.LockedBody,
		&i.ObsidianSourcePath,
		&i.ObsidianImportedAt,
		&i.PublishedAt,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWriting = `-- name: DeleteWriting :exec
DELETE FROM writings WHERE id = $1 AND owner_id = $2
`

type DeleteWritingParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) DeleteWriting(ctx context.Context, arg DeleteWritingParams) error {
	_, err := q.db.Exec(ctx, deleteWriting, arg.ID, arg.OwnerID)
	return err
}

const getPublishedWritingByPath = `-- name: GetPublishedWritingByPath :one
SELECT id, owner_id, slug, title, excerpt, body_md,
       cover_headline, cover_hue, cover_image_asset_id,
       tags, visibility, cross_refs, path, read_minutes, locked_body,
       obsidian_source_path, obsidian_imported_at,
       published_at, parent_id, created_at, updated_at
FROM writings WHERE owner_id = $1 AND path = $2 AND published_at IS NOT NULL
`

type GetPublishedWritingByPathParams struct {
	OwnerID pgtype.UUID
	Path    string
}

// retriever corpus_read 按树派生 path 读 published writing(DB,不走内存窗口)。
func (q *Queries) GetPublishedWritingByPath(ctx context.Context, arg GetPublishedWritingByPathParams) (Writing, error) {
	row := q.db.QueryRow(ctx, getPublishedWritingByPath, arg.OwnerID, arg.Path)
	var i Writing
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.BodyMd,
		&i.CoverHeadline,
		&i.CoverHue,
		&i.CoverImageAssetID,
		&i.Tags,
		&i.Visibility,
		&i.CrossRefs,
		&i.Path,
		&i.ReadMinutes,
		&i.LockedBody,
		&i.ObsidianSourcePath,
		&i.ObsidianImportedAt,
		&i.PublishedAt,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWritingByID = `-- name: GetWritingByID :one
SELECT id, owner_id, slug, title, excerpt, body_md,
       cover_headline, cover_hue, cover_image_asset_id,
       tags, visibility, cross_refs, path, read_minutes, locked_body,
       obsidian_source_path, obsidian_imported_at,
       published_at, parent_id, created_at, updated_at
FROM writings WHERE id = $1 AND owner_id = $2
`

type GetWritingByIDParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetWritingByID(ctx context.Context, arg GetWritingByIDParams) (Writing, error) {
	row := q.db.QueryRow(ctx, getWritingByID, arg.ID, arg.OwnerID)
	var i Writing
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.BodyMd,
		&i.CoverHeadline,
		&i.CoverHue,
		&i.CoverImageAssetID,
		&i.Tags,
		&i.Visibility,
		&i.CrossRefs,
		&i.Path,
		&i.ReadMinutes,
		&i.LockedBody,
		&i.ObsidianSourcePath,
		&i.ObsidianImportedAt,
		&i.PublishedAt,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWritingByObsidianSourcePath = `-- name: GetWritingByObsidianSourcePath :one
SELECT id, owner_id, slug, title, excerpt, body_md,
       cover_headline, cover_hue, cover_image_asset_id,
       tags, visibility, cross_refs, path, read_minutes, locked_body,
       obsidian_source_path, obsidian_imported_at,
       published_at, parent_id, created_at, updated_at
FROM writings WHERE owner_id = $1 AND obsidian_source_path = $2
`

type GetWritingByObsidianSourcePathParams struct {
	OwnerID            pgtype.UUID
	ObsidianSourcePath string
}

func (q *Queries) GetWritingByObsidianSourcePath(ctx context.Context, arg GetWritingByObsidianSourcePathParams) (Writing, error) {
	row := q.db.QueryRow(ctx, getWritingByObsidianSourcePath, arg.OwnerID, arg.ObsidianSourcePath)
	var i Writing
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.BodyMd,
		&i.CoverHeadline,
		&i.CoverHue,
		&i.CoverImageAssetID,
		&i.Tags,
		&i.Visibility,
		&i.CrossRefs,
		&i.Path,
		&i.ReadMinutes,
		&i.LockedBody,
		&i.ObsidianSourcePath,
		&i.ObsidianImportedAt,
		&i.PublishedAt,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWritingBySlug = `-- name: GetWritingBySlug :one
SELECT id, owner_id, slug, title, excerpt, body_md,
       cover_headline, cover_hue, cover_image_asset_id,
       tags, visibility, cross_refs, path, read_minutes, locked_body,
       obsidian_source_path, obsidian_imported_at,
       published_at, parent_id, created_at, updated_at
FROM writings WHERE owner_id = $1 AND slug = $2
`

type GetWritingBySlugParams struct {
	OwnerID pgtype.UUID
	Slug    string
}

func (q *Queries) GetWritingBySlug(ctx context.Context, arg GetWritingBySlugParams) (Writing, error) {
	row := q.db.QueryRow(ctx, getWritingBySlug, arg.OwnerID, arg.Slug)
	var i Writing
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.BodyMd,
		&i.CoverHeadline,
		&i.CoverHue,
		&i.CoverImageAssetID,
		&i.Tags,
		&i.Visibility,
		&i.CrossRefs,
		&i.Path,
		&i.ReadMinutes,
		&i.LockedBody,
		&i.ObsidianSourcePath,
		&i.ObsidianImportedAt,
		&i.PublishedAt,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublishedWritingSlugAndTitle = `-- name: ListPublishedWritingSlugAndTitle :many
SELECT slug, title
FROM writings
WHERE owner_id = $1 AND published_at IS NOT NULL
ORDER BY slug ASC
`

type ListPublishedWritingSlugAndTitleRow struct {
	Slug  string
	Title string
}

// /writings 渲染 [[crosslink]] 时用：拉 owner 所有 published writing 的
// slug + title 当 resolution index，不带 body_md（避免 N+1 那种全 body 重
// 传开销）。
func (q *Queries) ListPublishedWritingSlugAndTitle(ctx context.Context, ownerID pgtype.UUID) ([]ListPublishedWritingSlugAndTitleRow, error) {
	rows, err := q.db.Query(ctx, listPublishedWritingSlugAndTitle, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedWritingSlugAndTitleRow
	for rows.Next() {
		var i ListPublishedWritingSlugAndTitleRow
		if err := rows.Scan(&i.Slug, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedWritingsByOwner = `-- name: ListPublishedWritingsByOwner :many
SELECT id, owner_id, slug, title, excerpt, body_md,
       cover_headline, cover_hue, cover_image_asset_id,
       tags, visibility, cross_refs, path, read_minutes, locked_body,
       obsidian_source_path, obsidian_imported_at,
       published_at, parent_id, created_at, updated_at
FROM writings
WHERE owner_id = $1 AND published_at IS NOT NULL
ORDER BY published_at DESC
`

func (q *Queries) ListPublishedWritingsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Writing, error) {
	rows, err := q.db.Query(ctx, listPublishedWritingsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Writing
	for rows.Next() {
		var i Writing
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.BodyMd,
			&i.CoverHeadline,
			&i.CoverHue,
			&i.CoverImageAssetID,
			&i.Tags,
			&i.Visibility,
			&i.CrossRefs,
			&i.Path,
			&i.ReadMinutes,
			&i.LockedBody,
			&i.ObsidianSourcePath,
			&i.ObsidianImportedAt,
			&i.PublishedAt,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedWritingsByOwnerPage = `-- name: ListPublishedWritingsByOwnerPage :many
SELECT id, owner_id, slug, title, excerpt, body_md,
       cover_headline, cover_hue, cover_image_asset_id,
       tags, visibility, cross_refs, path, read_minutes, locked_body,
       obsidian_source_path, obsidian_imported_at,
       published_at, parent_id, created_at, updated_at
FROM writings
WHERE owner_id = $1
  AND published_at IS NOT NULL
  AND ($2::timestamptz IS NULL OR published_at < $2::timestamptz)
ORDER BY published_at DESC
LIMIT $3
`

type ListPublishedWritingsByOwnerPageParams struct {
	OwnerID pgtype.UUID
	Column2 pgtype.Timestamptz
	Limit   int32
}

// 分页 infinite scroll：cursor = 上一页最末 writing.published_at (RFC3339)，
// 第一页 cursor 传 NULL 拿最新 N 条。返 LIMIT+1 让 caller 判断 has_more。
func (q *Queries) ListPublishedWritingsByOwnerPage(ctx context.Context, arg ListPublishedWritingsByOwnerPageParams) ([]Writing, error) {
	rows, err := q.db.Query(ctx, listPublishedWritingsByOwnerPage, arg.OwnerID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Writing
	for rows.Next() {
		var i Writing
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.BodyMd,
			&i.CoverHeadline,
			&i.CoverHue,
			&i.CoverImageAssetID,
			&i.Tags,
			&i.Visibility,
			&i.CrossRefs,
			&i.Path,
			&i.ReadMinutes,
			&i.LockedBody,
			&i.ObsidianSourcePath,
			&i.ObsidianImportedAt,
			&i.PublishedAt,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWritingsByOwner = `-- name: ListWritingsByOwner :many
SELECT id, owner_id, slug, title, excerpt, body_md,
       cover_headline, cover_hue, cover_image_asset_id,
       tags, visibility, cross_refs, path, read_minutes, locked_body,
       obsidian_source_path, obsidian_imported_at,
       published_at, parent_id, created_at, updated_at
FROM writings
WHERE owner_id = $1
ORDER BY COALESCE(published_at, created_at) DESC
`

func (q *Queries) ListWritingsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Writing, error) {
	rows, err := q.db.Query(ctx, listWritingsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Writing
	for rows.Next() {
		var i Writing
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.BodyMd,
			&i.CoverHeadline,
			&i.CoverHue,
			&i.CoverImageAssetID,
			&i.Tags,
			&i.Visibility,
			&i.CrossRefs,
			&i.Path,
			&i.ReadMinutes,
			&i.LockedBody,
			&i.ObsidianSourcePath,
			&i.ObsidianImportedAt,
			&i.PublishedAt,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishWriting = `-- name: PublishWriting :one
UPDATE writings SET published_at = now(), updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, slug, title, excerpt, body_md,
          cover_headline, cover_hue, cover_image_asset_id,
          tags, visibility, cross_refs, path, read_minutes, locked_body,
          obsidian_source_path, obsidian_imported_at,
          published_at, parent_id, created_at, updated_at
`

type PublishWritingParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) PublishWriting(ctx context.Context, arg PublishWritingParams) (Writing, error) {
	row := q.db.QueryRow(ctx, publishWriting, arg.ID, arg.OwnerID)
	var i Writing
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.BodyMd,
		&i.CoverHeadline,
		&i.CoverHue,
		&i.CoverImageAssetID,
		&i.Tags,
		&i.Visibility,
		&i.CrossRefs,
		&i.Path,
		&i.ReadMinutes,
		&i.LockedBody,
		&i.ObsidianSourcePath,
		&i.ObsidianImportedAt,
		&i.PublishedAt,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchPublishedWritings = `-- name: SearchPublishedWritings :many
SELECT id, owner_id, slug, title, excerpt, body_md,
       cover_headline, cover_hue, cover_image_asset_id,
       tags, visibility, cross_refs, path, read_minutes, locked_body,
       obsidian_source_path, obsidian_imported_at,
       published_at, parent_id, created_at, updated_at
FROM writings
WHERE owner_id = $1 AND published_at IS NOT NULL
  AND to_tsvector('english', title || ' ' || body_md || ' ' || array_to_string(tags, ' '))
      @@ replace(plainto_tsquery('english', $2)::text, ' & ', ' | ')::tsquery
ORDER BY ts_rank(
        to_tsvector('english', title || ' ' || body_md || ' ' || array_to_string(tags, ' ')),
        replace(plainto_tsquery('english', $2)::text, ' & ', ' | ')::tsquery
      ) DESC, published_at DESC
LIMIT $3 OFFSET $4
`

type SearchPublishedWritingsParams struct {
	OwnerID        pgtype.UUID
	PlaintoTsquery string
	Limit          int32
	Offset         int32
}

// retriever corpus_search 全量搜 published writing(DB full-text,镜像 wiki/output:
// 自然语言问句按 OR 命中任一词项,ts_rank 排序),不吃内存窗口。
func (q *Queries) SearchPublishedWritings(ctx context.Context, arg SearchPublishedWritingsParams) ([]Writing, error) {
	rows, err := q.db.Query(ctx, searchPublishedWritings,
		arg.OwnerID,
		arg.PlaintoTsquery,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Writing
	for rows.Next() {
		var i Writing
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.BodyMd,
			&i.CoverHeadline,
			&i.CoverHue,
			&i.CoverImageAssetID,
			&i.Tags,
			&i.Visibility,
			&i.CrossRefs,
			&i.Path,
			&i.ReadMinutes,
			&i.LockedBody,
			&i.ObsidianSourcePath,
			&i.ObsidianImportedAt,
			&i.PublishedAt,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWritingObsidianMeta = `-- name: SetWritingObsidianMeta :exec
UPDATE writings
SET obsidian_source_path = $3,
    obsidian_imported_at = now(),
    updated_at = now()
WHERE id = $1 AND owner_id = $2
`

type SetWritingObsidianMetaParams struct {
	ID                 pgtype.UUID
	OwnerID            pgtype.UUID
	ObsidianSourcePath string
}

// Obsidian import 走完 SaveWriting 之后调用：标记这行 writing 是从 vault
// 来的，顺便记 imported_at = now()。re-import 时根据 updated_at vs imported_at
// 决定 skip / overwrite（owner 在 web 改过了 updated_at 会跳过 imported_at）。
func (q *Queries) SetWritingObsidianMeta(ctx context.Context, arg SetWritingObsidianMetaParams) error {
	_, err := q.db.Exec(ctx, setWritingObsidianMeta, arg.ID, arg.OwnerID, arg.ObsidianSourcePath)
	return err
}

const unpublishWriting = `-- name: UnpublishWriting :one
UPDATE writings SET published_at = NULL, updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, slug, title, excerpt, body_md,
          cover_headline, cover_hue, cover_image_asset_id,
          tags, visibility, cross_refs, path, read_minutes, locked_body,
          obsidian_source_path, obsidian_imported_at,
          published_at, parent_id, created_at, updated_at
`

type UnpublishWritingParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) UnpublishWriting(ctx context.Context, arg UnpublishWritingParams) (Writing, error) {
	row := q.db.QueryRow(ctx, unpublishWriting, arg.ID, arg.OwnerID)
	var i Writing
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.BodyMd,
		&i.CoverHeadline,
		&i.CoverHue,
		&i.CoverImageAssetID,
		&i.Tags,
		&i.Visibility,
		&i.CrossRefs,
		&i.Path,
		&i.ReadMinutes,
		&i.LockedBody,
		&i.ObsidianSourcePath,
		&i.ObsidianImportedAt,
		&i.PublishedAt,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWriting = `-- name: UpdateWriting :one
UPDATE writings SET
    title = $3, excerpt = $4, body_md = $5,
    cover_headline = $6, cover_hue = $7, cover_image_asset_id = $8,
    tags = $9, visibility = $10, cross_refs = $11, path = $12,
    read_minutes = $13, locked_body = $14, parent_id = $15,
    updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, slug, title, excerpt, body_md,
          cover_headline, cover_hue, cover_image_asset_id,
          tags, visibility, cross_refs, path, read_minutes, locked_body,
          obsidian_source_path, obsidian_imported_at,
          published_at, parent_id, created_at, updated_at
`

type UpdateWritingParams struct {
	ID                pgtype.UUID
	OwnerID           pgtype.UUID
	Title             string
	Excerpt           string
	BodyMd            string
	CoverHeadline     string
	CoverHue          string
	CoverImageAssetID pgtype.UUID
	Tags              []string
	Visibility        string
	CrossRefs         []string
	Path              string
	ReadMinutes       int32
	LockedBody        string
	ParentID          pgtype.UUID
}

func (q *Queries) UpdateWriting(ctx context.Context, arg UpdateWritingParams) (Writing, error) {
	row := q.db.QueryRow(ctx, updateWriting,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Excerpt,
		arg.BodyMd,
		arg.CoverHeadline,
		arg.CoverHue,
		arg.CoverImageAssetID,
		arg.Tags,
		arg.Visibility,
		arg.CrossRefs,
		arg.Path,
		arg.ReadMinutes,
		arg.LockedBody,
		arg.ParentID,
	)
	var i Writing
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.BodyMd,
		&i.CoverHeadline,
		&i.CoverHue,
		&i.CoverImageAssetID,
		&i.Tags,
		&i.Visibility,
		&i.CrossRefs,
		&i.Path,
		&i.ReadMinutes,
		&i.LockedBody,
		&i.ObsidianSourcePath,
		&i.ObsidianImportedAt,
		&i.PublishedAt,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
