# Generated by Django 6.0.2 on 2026-02-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettingsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_access", models.BooleanField(default=False)),
                ("ai_provider", models.CharField(default="anthropic", max_length=50)),
                (
                    "ai_model",
                    models.CharField(
                        default="claude-sonnet-4-20250514", max_length=100
                    ),
                ),
                (
                    "ai_api_key",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("ai_system_prompt", models.TextField(blank=True, default="")),
                ("extra", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
                "db_table": "site_settings",
            },
        ),
    ]
