# Generated by Django 6.0.2 on 2026-03-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standmeet_settings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettingsmodel",
            name="ai_api_key",
        ),
        migrations.RemoveField(
            model_name="sitesettingsmodel",
            name="ai_model",
        ),
        migrations.RemoveField(
            model_name="sitesettingsmodel",
            name="ai_provider",
        ),
    ]
