// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: mcp_servers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMCPServer = `-- name: CreateMCPServer :one
INSERT INTO mcp_servers (owner_id, name, url, auth_header_name, auth_header_value_enc)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, name, url, auth_header_name, auth_header_value_enc, granted_deps, created_at
`

type CreateMCPServerParams struct {
	OwnerID            pgtype.UUID
	Name               string
	Url                string
	AuthHeaderName     string
	AuthHeaderValueEnc []byte
}

func (q *Queries) CreateMCPServer(ctx context.Context, arg CreateMCPServerParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, createMCPServer,
		arg.OwnerID,
		arg.Name,
		arg.Url,
		arg.AuthHeaderName,
		arg.AuthHeaderValueEnc,
	)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Url,
		&i.AuthHeaderName,
		&i.AuthHeaderValueEnc,
		&i.GrantedDeps,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMCPServer = `-- name: DeleteMCPServer :exec
DELETE FROM mcp_servers
WHERE id = $1 AND owner_id = $2
`

type DeleteMCPServerParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) DeleteMCPServer(ctx context.Context, arg DeleteMCPServerParams) error {
	_, err := q.db.Exec(ctx, deleteMCPServer, arg.ID, arg.OwnerID)
	return err
}

const getMCPServerByID = `-- name: GetMCPServerByID :one
SELECT id, owner_id, name, url, auth_header_name, auth_header_value_enc, granted_deps, created_at
FROM mcp_servers
WHERE id = $1 AND owner_id = $2
`

type GetMCPServerByIDParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetMCPServerByID(ctx context.Context, arg GetMCPServerByIDParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, getMCPServerByID, arg.ID, arg.OwnerID)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Url,
		&i.AuthHeaderName,
		&i.AuthHeaderValueEnc,
		&i.GrantedDeps,
		&i.CreatedAt,
	)
	return i, err
}

const grantMCPServerDep = `-- name: GrantMCPServerDep :exec
UPDATE mcp_servers
SET granted_deps = array_append(granted_deps, $3)
WHERE id = $1 AND owner_id = $2 AND NOT ($3 = ANY(granted_deps))
`

type GrantMCPServerDepParams struct {
	ID          pgtype.UUID
	OwnerID     pgtype.UUID
	ArrayAppend interface{}
}

// GrantMCPServerDep —— owner 显式授权这个 server 接某个 connector 依赖（dep 名）。
// 幂等：已在 granted_deps 里就不重复 append。
func (q *Queries) GrantMCPServerDep(ctx context.Context, arg GrantMCPServerDepParams) error {
	_, err := q.db.Exec(ctx, grantMCPServerDep, arg.ID, arg.OwnerID, arg.ArrayAppend)
	return err
}

const listMCPServersByOwner = `-- name: ListMCPServersByOwner :many
SELECT id, owner_id, name, url, auth_header_name, auth_header_value_enc, granted_deps, created_at
FROM mcp_servers
WHERE owner_id = $1
ORDER BY name ASC
`

func (q *Queries) ListMCPServersByOwner(ctx context.Context, ownerID pgtype.UUID) ([]McpServer, error) {
	rows, err := q.db.Query(ctx, listMCPServersByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpServer
	for rows.Next() {
		var i McpServer
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Url,
			&i.AuthHeaderName,
			&i.AuthHeaderValueEnc,
			&i.GrantedDeps,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
