// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: inference_usage.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteInferenceUsageOlderThan7Days = `-- name: DeleteInferenceUsageOlderThan7Days :exec
DELETE FROM inference_usage u
WHERE u.created_at < now() - interval '7 days'
  AND NOT (
      u.metered
      AND EXISTS (
          SELECT 1 FROM owner_providers p
          WHERE p.id = u.provider_id
            AND p.gas_tokens IS NOT NULL
            AND u.created_at >= COALESCE(p.gas_filled_at, 'epoch'::timestamptz)
      )
  )
`

// 7-day small table: purge old rows (the queries only look back 7 days anyway; cleanup only keeps the table from growing forever).
//
// **But metered rows cannot be purged together**: the dashboard only looks at 7 days, yet gas usage is the cumulative total
// "from the last fill to now". Deleting metered rows older than 7 days lets the gas grow back on its own —— a tank that never
// needs filling. So keep only those still within the current tank's billing period: metered rows before the last fill no longer
// participate in any sum, so delete them like ordinary old rows.
func (q *Queries) DeleteInferenceUsageOlderThan7Days(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteInferenceUsageOlderThan7Days)
	return err
}

const recordInferenceUsage = `-- name: RecordInferenceUsage :exec
INSERT INTO inference_usage (
    owner_id, model, input_tokens, output_tokens, cached_tokens, provider_id, metered
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type RecordInferenceUsageParams struct {
	OwnerID      pgtype.UUID
	Model        string
	InputTokens  int32
	OutputTokens int32
	CachedTokens int32
	ProviderID   pgtype.UUID
	Metered      bool
}

// #106 record one row per owner-key LLM call. metered = this call counts against a gas tank's ledger (#7):
// a metered role + a resolvable provider, true only when both hold, decided by the caller.
func (q *Queries) RecordInferenceUsage(ctx context.Context, arg RecordInferenceUsageParams) error {
	_, err := q.db.Exec(ctx, recordInferenceUsage,
		arg.OwnerID,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
		arg.ProviderID,
		arg.Metered,
	)
	return err
}

const sumMeteredUsageSince = `-- name: SumMeteredUsageSince :one
SELECT COALESCE(sum(input_tokens + output_tokens), 0)::bigint
FROM inference_usage
WHERE provider_id = $1 AND metered AND created_at >= $2
`

type SumMeteredUsageSinceParams struct {
	ProviderID pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

// How much a gas tank has spent since the moment it was filled. No counter column —— summed at read time, like the turn quota.
func (q *Queries) SumMeteredUsageSince(ctx context.Context, arg SumMeteredUsageSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumMeteredUsageSince, arg.ProviderID, arg.CreatedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const summarizeInferenceUsage7Day = `-- name: SummarizeInferenceUsage7Day :many
SELECT date_trunc('day', created_at)::date AS day,
       model,
       count(*)::bigint            AS calls,
       sum(input_tokens)::bigint   AS input_tokens,
       sum(output_tokens)::bigint  AS output_tokens
FROM inference_usage
WHERE owner_id = $1 AND created_at >= now() - interval '7 days'
GROUP BY day, model
ORDER BY day DESC, model
`

type SummarizeInferenceUsage7DayRow struct {
	Day          pgtype.Date
	Model        string
	Calls        int64
	InputTokens  int64
	OutputTokens int64
}

// Aggregate the last 7 days by day × model (call count + token totals). Newest → oldest.
func (q *Queries) SummarizeInferenceUsage7Day(ctx context.Context, ownerID pgtype.UUID) ([]SummarizeInferenceUsage7DayRow, error) {
	rows, err := q.db.Query(ctx, summarizeInferenceUsage7Day, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummarizeInferenceUsage7DayRow
	for rows.Next() {
		var i SummarizeInferenceUsage7DayRow
		if err := rows.Scan(
			&i.Day,
			&i.Model,
			&i.Calls,
			&i.InputTokens,
			&i.OutputTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
