package paritymanifest

import fp "github.com/atmaxmoj/standmeet/internal/infra/facadeparity"

// governance (access-requests / ip-bans / domains / capabilities / bookings).
func governanceEntries() []Entry {
	return []Entry{
		// access_requests / ip_bans / domains are no longer in this table — they've moved into
		// the outbound convergence point (internal/routes/dispatcher). For an op in the
		// convergence point, parity is answered by structure: the MCP face is generated by
		// walking the convergence point, the admin face can only pull a capability via Face,
		// and pulling one registers it; at boot, Conform() reconciles Reach against the
		// registrations. Writing another row in the ledger would be a redundant declaration.
		//
		// This table now holds only "what hasn't moved yet". It shrinks as the migration
		// proceeds, and gets deleted as a whole package once the move is done.
		// booking's **policy** is no longer in this table — it's the sandboxed booker
		// capability's own config, declared in the booker's manifest (Config) and read/written
		// through the generic capability_config port. host no longer knows what "booking
		// policy" is, and the two faces no longer each keep their own implementation.
		{
			// Served by the **sandboxed booker** via OwnerTools: a completed booking is its own
			// data. The host's admin REST route for this has been retired — it only existed
			// because the sandbox couldn't get back the id of its own record (the reach-back
			// vocabulary had no "query and return an id"); once capstore.query_records was
			// added, that gap closed.
			Op:     read("bookings.list", fp.Only("the capability's own records", FacadeMCP)),
			MCP:    []string{"bookings.list"},
			Plugin: true,
		},
		{
			// Served by the **sandboxed booker** via manifest.OwnerTools, not by ownercore: the
			// policy evaluation + slot enumeration belong to the capability, and the host no
			// longer keeps a second copy of either.
			Op:     act("calendar.list_slots", fp.Only("agent-facing booking helper; owner drives it via MCP", FacadeMCP)),
			MCP:    []string{"calendar.list_slots"},
			Plugin: true,
		},
		{
			// Same as list_slots — served by the **sandboxed booker** via manifest.OwnerTools:
			// deleting the calendar event and deleting its own record are both the booker's
			// job. host used to re-implement both (uc_booking_cancel*.go and ownercore's
			// cap_calendar); those two copies are now deleted.
			Op:     act("calendar.cancel_booking", fp.Only("owner cancels via MCP; admin has the bookings list, not per-booking cancel", FacadeMCP)),
			MCP:    []string{"calendar.cancel_booking"},
			Plugin: true,
		},
	}
}

// observability + marketplace.
func observabilityEntries() []Entry {
	return []Entry{}
}

// custom pages —— all moved into the outbound convergence point (dispatcher.CustomPages). The
// product decision "writes are MCP-only" now lives in each op's Reach, no longer a row in this
// table.
func customPageEntries() []Entry {
	return []Entry{}
}
