package paritymanifest_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/atmaxmoj/standmeet/internal/infra/paritymanifest"
)

// remainingOps —— **how many rows this hand-written cross-check table currently has left.**
//
// This number can only shrink; growing it turns the test RED.
//
// Why: the only reason this table exists is that there used to be no outbound convergence point
// — MCP and admin each wrote their own face by hand, neither a projection of the other, so the
// only way to reconcile them was a manual ledger after the fact. Once the convergence point
// takes over an op, its parity becomes a property of the structure (the MCP face is generated by
// walking the convergence point, the admin face can only pull a capability via Face and pulling
// one registers it, and Conform() reconciles Reach against the registrations at boot); leaving
// another row in the ledger is just a redundant declaration.
//
// So every step of the migration deletes a row here, down to 0, at which point **the whole
// package, along with this test, gets deleted together**. The number growing means someone added
// something to the hand-written ledger instead of moving the capability into the convergence
// point — that's moving backward.
const remainingOps = 86

func TestManifestOnlyShrinks(t *testing.T) {
	t.Parallel()

	require.LessOrEqualf(t, len(paritymanifest.Manifest()), remainingOps,
		"the hand-written parity ledger grew. Declare new capability in the outbound "+
			"convergence point (internal/routes/dispatcher) instead — parity for anything "+
			"declared there is a property of the structure, so it needs no row here.")
}

// TestManifestIsGoneWhenEmpty —— the moment the ledger empties, this package should disappear,
// not linger as an empty shell still being imported. At 0 this test goes red, and the red is
// itself the delete instruction.
func TestManifestIsGoneWhenEmpty(t *testing.T) {
	t.Parallel()

	require.NotEmptyf(t, paritymanifest.Manifest(),
		"the ledger is empty — every capability now lives in the outbound convergence "+
			"point. Delete the whole internal/infra/paritymanifest package (and its last "+
			"references in ownercore); parity is answered by the dispatcher's structure alone.")
}
