-- 2026-08-22 · F-C-56：上传来的连接器在列表里没有名字。
--
-- schema.sql 只在**全新的 pg 卷**上跑一次，所以已经在跑的实例要走这里的 ALTER
-- （[[schema-lives-in-the-volume-not-the-image]]）。可重入、非破坏性。
--
-- 卡名一直渲的是 `category`，而**没有绑品类契约的连接器 category 是空串** —— GitHub 那种
-- 落不到 calendar/mail 上的厂商只有「暴露成 agent 工具」这一条路，于是它在
-- `CONNECTORS YOU UPLOADED` 里就是一行没有名字的框；两条并排时 owner 分不出哪条是哪个厂商，
-- 也就不知道该给哪一条填凭据。
--
-- 名字不是新数据：产品在摄入那一刻就解析并显示过 `info.title`（`CONNECTOR CANDIDATE ·
-- GitHub v3 REST API`），只是没留下来。整份 spec 也一直存着，但那是 12.9 MB —— 每次列表
-- 都重解析一遍不是办法，所以写入时取一次。
--
-- 存量行留空串：它们的名字还是按老规矩从 category 来，不假装知道一个没记过的事实。

-- `IF EXISTS` on the TABLE, added 2026-09-11 — without it a **fresh install cannot boot.**
--
-- Migrations replay from an empty ledger on a new volume, but `schema.sql` is always CURRENT.
-- `2026-09-11-block-vocabulary.sql` renamed this table to `block_connections`, so on a fresh
-- volume schema.sql creates the new name, this line then runs against a table that was never
-- there, and `Migrate` returns fatal. The column guard did not help: it guards the column, and
-- what was missing was the relation.
--
-- On an instance that predates the rename this still does exactly what it always did. On one
-- created after it, it is a no-op — `block_connections` already has `title`, from schema.sql.
--
-- The general rule this is an instance of: **a migration naming a table that a later migration
-- renames must tolerate the table being absent**, because fresh installs replay it against the
-- renamed schema.
ALTER TABLE IF EXISTS owner_connectors ADD COLUMN IF NOT EXISTS title text NOT NULL DEFAULT '';
