// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: custom_pages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingBuild = `-- name: ClaimPendingBuild :one
SELECT id, page_id, status, source_files, output_path,
       error_message, created_at, built_at
FROM custom_page_builds
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT 1
FOR UPDATE SKIP LOCKED
`

// Concurrency-safe via FOR UPDATE SKIP LOCKED; the usecase calls SetBuilding immediately after claiming.
func (q *Queries) ClaimPendingBuild(ctx context.Context) (CustomPageBuild, error) {
	row := q.db.QueryRow(ctx, claimPendingBuild)
	var i CustomPageBuild
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Status,
		&i.SourceFiles,
		&i.OutputPath,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.BuiltAt,
	)
	return i, err
}

const createCustomPage = `-- name: CreateCustomPage :one
INSERT INTO custom_pages (owner_id, slug, title)
VALUES ($1, $2, $3)
RETURNING id, owner_id, slug, title, status,
          live_build_id, staging_build_id, previous_live_build_id,
          allow_byoai, store_writable, created_at, updated_at
`

type CreateCustomPageParams struct {
	OwnerID pgtype.UUID
	Slug    string
	Title   string
}

func (q *Queries) CreateCustomPage(ctx context.Context, arg CreateCustomPageParams) (CustomPage, error) {
	row := q.db.QueryRow(ctx, createCustomPage, arg.OwnerID, arg.Slug, arg.Title)
	var i CustomPage
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.LiveBuildID,
		&i.StagingBuildID,
		&i.PreviousLiveBuildID,
		&i.AllowByoai,
		&i.StoreWritable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCustomPageBuild = `-- name: CreateCustomPageBuild :one
INSERT INTO custom_page_builds (page_id, source_files)
VALUES ($1, $2)
RETURNING id, page_id, status, source_files, output_path,
          error_message, created_at, built_at
`

type CreateCustomPageBuildParams struct {
	PageID      pgtype.UUID
	SourceFiles []byte
}

func (q *Queries) CreateCustomPageBuild(ctx context.Context, arg CreateCustomPageBuildParams) (CustomPageBuild, error) {
	row := q.db.QueryRow(ctx, createCustomPageBuild, arg.PageID, arg.SourceFiles)
	var i CustomPageBuild
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Status,
		&i.SourceFiles,
		&i.OutputPath,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.BuiltAt,
	)
	return i, err
}

const getCustomPageBuild = `-- name: GetCustomPageBuild :one
SELECT id, page_id, status, source_files, output_path,
       error_message, created_at, built_at
FROM custom_page_builds
WHERE id = $1
`

func (q *Queries) GetCustomPageBuild(ctx context.Context, id pgtype.UUID) (CustomPageBuild, error) {
	row := q.db.QueryRow(ctx, getCustomPageBuild, id)
	var i CustomPageBuild
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Status,
		&i.SourceFiles,
		&i.OutputPath,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.BuiltAt,
	)
	return i, err
}

const getCustomPageByID = `-- name: GetCustomPageByID :one
SELECT id, owner_id, slug, title, status,
       live_build_id, staging_build_id, previous_live_build_id,
       allow_byoai, store_writable, created_at, updated_at
FROM custom_pages
WHERE id = $1 AND status != 'deleted'
`

func (q *Queries) GetCustomPageByID(ctx context.Context, id pgtype.UUID) (CustomPage, error) {
	row := q.db.QueryRow(ctx, getCustomPageByID, id)
	var i CustomPage
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.LiveBuildID,
		&i.StagingBuildID,
		&i.PreviousLiveBuildID,
		&i.AllowByoai,
		&i.StoreWritable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomPageBySlug = `-- name: GetCustomPageBySlug :one
SELECT id, owner_id, slug, title, status,
       live_build_id, staging_build_id, previous_live_build_id,
       allow_byoai, store_writable, created_at, updated_at
FROM custom_pages
WHERE owner_id = $1 AND slug = $2 AND status != 'deleted'
`

type GetCustomPageBySlugParams struct {
	OwnerID pgtype.UUID
	Slug    string
}

func (q *Queries) GetCustomPageBySlug(ctx context.Context, arg GetCustomPageBySlugParams) (CustomPage, error) {
	row := q.db.QueryRow(ctx, getCustomPageBySlug, arg.OwnerID, arg.Slug)
	var i CustomPage
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.LiveBuildID,
		&i.StagingBuildID,
		&i.PreviousLiveBuildID,
		&i.AllowByoai,
		&i.StoreWritable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestBuiltCustomPageBuild = `-- name: GetLatestBuiltCustomPageBuild :one
SELECT id, page_id, status, source_files, output_path,
       error_message, created_at, built_at
FROM custom_page_builds
WHERE page_id = $1 AND status = 'built'
ORDER BY created_at DESC
LIMIT 1
`

// The one the preview should show: this page's **most recent successful build**.
//
// Not GetLatestCustomPageBuild: that one doesn't filter status, so pending / building / failed could
// come back, and those have no output -- the owner would see a blank and think the page they wrote
// is broken.
// Nor staging_build_id: that requires the agent to remember an extra promote_to_staging call, and
// forgetting it shows nothing -- but the owner wants to "see what it just did".
func (q *Queries) GetLatestBuiltCustomPageBuild(ctx context.Context, pageID pgtype.UUID) (CustomPageBuild, error) {
	row := q.db.QueryRow(ctx, getLatestBuiltCustomPageBuild, pageID)
	var i CustomPageBuild
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Status,
		&i.SourceFiles,
		&i.OutputPath,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.BuiltAt,
	)
	return i, err
}

const getLatestCustomPageBuild = `-- name: GetLatestCustomPageBuild :one
SELECT id, page_id, status, source_files, output_path,
       error_message, created_at, built_at
FROM custom_page_builds
WHERE page_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestCustomPageBuild(ctx context.Context, pageID pgtype.UUID) (CustomPageBuild, error) {
	row := q.db.QueryRow(ctx, getLatestCustomPageBuild, pageID)
	var i CustomPageBuild
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Status,
		&i.SourceFiles,
		&i.OutputPath,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.BuiltAt,
	)
	return i, err
}

const listCustomPagesByOwner = `-- name: ListCustomPagesByOwner :many
SELECT cp.id, cp.owner_id, cp.slug, cp.title, cp.status,
       cp.live_build_id, cp.staging_build_id, cp.previous_live_build_id,
       cp.allow_byoai, cp.store_writable, cp.created_at, cp.updated_at,
       COALESCE(
           ARRAY(
               SELECT ac.code::text FROM access_codes ac
               WHERE ac.custom_page_id = cp.id AND ac.status = 'active'
               ORDER BY ac.created_at
           ),
           ARRAY[]::text[]
       )::text[] AS bound_codes
FROM custom_pages cp
WHERE cp.owner_id = $1 AND cp.status != 'deleted'
ORDER BY cp.created_at DESC
`

type ListCustomPagesByOwnerRow struct {
	ID                  pgtype.UUID
	OwnerID             pgtype.UUID
	Slug                string
	Title               string
	Status              string
	LiveBuildID         pgtype.UUID
	StagingBuildID      pgtype.UUID
	PreviousLiveBuildID pgtype.UUID
	AllowByoai          bool
	StoreWritable       bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	BoundCodes          []string
}

// Includes allow_byoai, plus **which codes open this page** (the other end of the binding).
// Code->page is at most one; page->code has no such limit, so this is an array, not a single value.
// Empty array = no code points at it, it can only be opened anonymously.
func (q *Queries) ListCustomPagesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]ListCustomPagesByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listCustomPagesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomPagesByOwnerRow
	for rows.Next() {
		var i ListCustomPagesByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Slug,
			&i.Title,
			&i.Status,
			&i.LiveBuildID,
			&i.StagingBuildID,
			&i.PreviousLiveBuildID,
			&i.AllowByoai,
			&i.StoreWritable,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BoundCodes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollbackCustomPageLive = `-- name: RollbackCustomPageLive :one
UPDATE custom_pages
SET live_build_id          = previous_live_build_id,
    previous_live_build_id = NULL,
    updated_at             = now()
WHERE id = $1
RETURNING id, owner_id, slug, title, status,
          live_build_id, staging_build_id, previous_live_build_id,
          allow_byoai, store_writable, created_at, updated_at
`

// Promote previous_live_build_id back to live, clearing previous. When previous was already NULL
// -> live is set to NULL too (the page goes offline, the next visitor gets a 404).
func (q *Queries) RollbackCustomPageLive(ctx context.Context, id pgtype.UUID) (CustomPage, error) {
	row := q.db.QueryRow(ctx, rollbackCustomPageLive, id)
	var i CustomPage
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.LiveBuildID,
		&i.StagingBuildID,
		&i.PreviousLiveBuildID,
		&i.AllowByoai,
		&i.StoreWritable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCustomPageBuildBuilding = `-- name: SetCustomPageBuildBuilding :one
UPDATE custom_page_builds
SET status = 'building'
WHERE id = $1
RETURNING id, page_id, status, source_files, output_path,
          error_message, created_at, built_at
`

func (q *Queries) SetCustomPageBuildBuilding(ctx context.Context, id pgtype.UUID) (CustomPageBuild, error) {
	row := q.db.QueryRow(ctx, setCustomPageBuildBuilding, id)
	var i CustomPageBuild
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Status,
		&i.SourceFiles,
		&i.OutputPath,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.BuiltAt,
	)
	return i, err
}

const setCustomPageBuildBuilt = `-- name: SetCustomPageBuildBuilt :one
UPDATE custom_page_builds
SET status      = 'built',
    output_path = $2,
    built_at    = now()
WHERE id = $1
RETURNING id, page_id, status, source_files, output_path,
          error_message, created_at, built_at
`

type SetCustomPageBuildBuiltParams struct {
	ID         pgtype.UUID
	OutputPath string
}

func (q *Queries) SetCustomPageBuildBuilt(ctx context.Context, arg SetCustomPageBuildBuiltParams) (CustomPageBuild, error) {
	row := q.db.QueryRow(ctx, setCustomPageBuildBuilt, arg.ID, arg.OutputPath)
	var i CustomPageBuild
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Status,
		&i.SourceFiles,
		&i.OutputPath,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.BuiltAt,
	)
	return i, err
}

const setCustomPageBuildFailed = `-- name: SetCustomPageBuildFailed :one
UPDATE custom_page_builds
SET status        = 'failed',
    error_message = $2,
    built_at      = now()
WHERE id = $1
RETURNING id, page_id, status, source_files, output_path,
          error_message, created_at, built_at
`

type SetCustomPageBuildFailedParams struct {
	ID           pgtype.UUID
	ErrorMessage string
}

func (q *Queries) SetCustomPageBuildFailed(ctx context.Context, arg SetCustomPageBuildFailedParams) (CustomPageBuild, error) {
	row := q.db.QueryRow(ctx, setCustomPageBuildFailed, arg.ID, arg.ErrorMessage)
	var i CustomPageBuild
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Status,
		&i.SourceFiles,
		&i.OutputPath,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.BuiltAt,
	)
	return i, err
}

const setCustomPageByoai = `-- name: SetCustomPageByoai :one
UPDATE custom_pages
SET allow_byoai = $3, updated_at = now()
WHERE owner_id = $1 AND slug = $2 AND status != 'deleted'
RETURNING id, owner_id, slug, title, status,
          live_build_id, staging_build_id, previous_live_build_id,
          allow_byoai, store_writable, created_at, updated_at
`

type SetCustomPageByoaiParams struct {
	OwnerID    pgtype.UUID
	Slug       string
	AllowByoai bool
}

// Whether this page lets a reader use their own key **when no one presents a grant**. Void once a
// code arrives (I-4).
func (q *Queries) SetCustomPageByoai(ctx context.Context, arg SetCustomPageByoaiParams) (CustomPage, error) {
	row := q.db.QueryRow(ctx, setCustomPageByoai, arg.OwnerID, arg.Slug, arg.AllowByoai)
	var i CustomPage
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.LiveBuildID,
		&i.StagingBuildID,
		&i.PreviousLiveBuildID,
		&i.AllowByoai,
		&i.StoreWritable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCustomPageLive = `-- name: SetCustomPageLive :one
UPDATE custom_pages
SET previous_live_build_id = live_build_id,
    live_build_id          = $2,
    updated_at             = now()
WHERE id = $1
RETURNING id, owner_id, slug, title, status,
          live_build_id, staging_build_id, previous_live_build_id,
          allow_byoai, store_writable, created_at, updated_at
`

type SetCustomPageLiveParams struct {
	ID          pgtype.UUID
	LiveBuildID pgtype.UUID
}

// Move the current live_build_id into previous_live_build_id (to support rollback), then set the new live.
func (q *Queries) SetCustomPageLive(ctx context.Context, arg SetCustomPageLiveParams) (CustomPage, error) {
	row := q.db.QueryRow(ctx, setCustomPageLive, arg.ID, arg.LiveBuildID)
	var i CustomPage
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.LiveBuildID,
		&i.StagingBuildID,
		&i.PreviousLiveBuildID,
		&i.AllowByoai,
		&i.StoreWritable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCustomPageStaging = `-- name: SetCustomPageStaging :one
UPDATE custom_pages
SET staging_build_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, owner_id, slug, title, status,
          live_build_id, staging_build_id, previous_live_build_id,
          allow_byoai, store_writable, created_at, updated_at
`

type SetCustomPageStagingParams struct {
	ID             pgtype.UUID
	StagingBuildID pgtype.UUID
}

func (q *Queries) SetCustomPageStaging(ctx context.Context, arg SetCustomPageStagingParams) (CustomPage, error) {
	row := q.db.QueryRow(ctx, setCustomPageStaging, arg.ID, arg.StagingBuildID)
	var i CustomPage
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.LiveBuildID,
		&i.StagingBuildID,
		&i.PreviousLiveBuildID,
		&i.AllowByoai,
		&i.StoreWritable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPageStoreWritable = `-- name: SetPageStoreWritable :exec
UPDATE custom_pages SET store_writable = $3, updated_at = now()
WHERE owner_id = $1 AND slug = $2 AND status != 'deleted'
`

type SetPageStoreWritableParams struct {
	OwnerID       pgtype.UUID
	Slug          string
	StoreWritable bool
}

// Owner toggles whether this page's store accepts visitor writes. Owner-scoped by (owner_id, slug).
func (q *Queries) SetPageStoreWritable(ctx context.Context, arg SetPageStoreWritableParams) error {
	_, err := q.db.Exec(ctx, setPageStoreWritable, arg.OwnerID, arg.Slug, arg.StoreWritable)
	return err
}

const softDeleteCustomPage = `-- name: SoftDeleteCustomPage :exec
UPDATE custom_pages
SET status = 'deleted', updated_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteCustomPage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCustomPage, id)
	return err
}
