// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: handle_aliases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addHandleAlias = `-- name: AddHandleAlias :exec
INSERT INTO handle_aliases (handle, owner_id)
VALUES ($1, $2)
ON CONFLICT (handle) DO NOTHING
`

type AddHandleAliasParams struct {
	Handle  string
	OwnerID pgtype.UUID
}

// owner 改 handle 时把旧 handle 写进 alias 表。冲突（旧 handle 之前已经
// alias 过 / 其它 owner 占用）忽略——alias 唯一即可。
func (q *Queries) AddHandleAlias(ctx context.Context, arg AddHandleAliasParams) error {
	_, err := q.db.Exec(ctx, addHandleAlias, arg.Handle, arg.OwnerID)
	return err
}

const getOwnerByHandleAlias = `-- name: GetOwnerByHandleAlias :one
SELECT o.id, o.email, o.handle, o.full_name, o.location,
       o.byoai_enabled, o.byoai_providers, o.byoai_public_blurb, o.created_at
FROM owners o
JOIN handle_aliases a ON a.owner_id = o.id
WHERE a.handle = $1
`

type GetOwnerByHandleAliasRow struct {
	ID               pgtype.UUID
	Email            string
	Handle           string
	FullName         string
	Location         string
	ByoaiEnabled     bool
	ByoaiProviders   []byte
	ByoaiPublicBlurb string
	CreatedAt        pgtype.Timestamptz
}

// handle 不在 owners.handle 上时走这里：owner 改名后旧 handle 入 alias 表。
func (q *Queries) GetOwnerByHandleAlias(ctx context.Context, handle string) (GetOwnerByHandleAliasRow, error) {
	row := q.db.QueryRow(ctx, getOwnerByHandleAlias, handle)
	var i GetOwnerByHandleAliasRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.CreatedAt,
	)
	return i, err
}

const updateOwnerHandle = `-- name: UpdateOwnerHandle :one
UPDATE owners
SET handle = $2
WHERE id = $1
RETURNING id, email, handle, full_name, location,
          byoai_enabled, byoai_providers, byoai_public_blurb, created_at
`

type UpdateOwnerHandleParams struct {
	ID     pgtype.UUID
	Handle string
}

type UpdateOwnerHandleRow struct {
	ID               pgtype.UUID
	Email            string
	Handle           string
	FullName         string
	Location         string
	ByoaiEnabled     bool
	ByoaiProviders   []byte
	ByoaiPublicBlurb string
	CreatedAt        pgtype.Timestamptz
}

// 把 owners.handle 设成新值，返回更新后的 row 给 GetByID 形状的回调用。
func (q *Queries) UpdateOwnerHandle(ctx context.Context, arg UpdateOwnerHandleParams) (UpdateOwnerHandleRow, error) {
	row := q.db.QueryRow(ctx, updateOwnerHandle, arg.ID, arg.Handle)
	var i UpdateOwnerHandleRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.CreatedAt,
	)
	return i, err
}
