// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: owner_keypairs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOwnerKeypair = `-- name: CreateOwnerKeypair :one
INSERT INTO owner_keypairs (owner_id, key_id, public_key_pem, label)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, key_id, public_key_pem, label, last_used_at, created_at
`

type CreateOwnerKeypairParams struct {
	OwnerID      pgtype.UUID
	KeyID        string
	PublicKeyPem string
	Label        string
}

func (q *Queries) CreateOwnerKeypair(ctx context.Context, arg CreateOwnerKeypairParams) (OwnerKeypair, error) {
	row := q.db.QueryRow(ctx, createOwnerKeypair,
		arg.OwnerID,
		arg.KeyID,
		arg.PublicKeyPem,
		arg.Label,
	)
	var i OwnerKeypair
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.KeyID,
		&i.PublicKeyPem,
		&i.Label,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOwnerKeypair = `-- name: DeleteOwnerKeypair :exec
DELETE FROM owner_keypairs WHERE key_id = $1 AND owner_id = $2
`

type DeleteOwnerKeypairParams struct {
	KeyID   string
	OwnerID pgtype.UUID
}

func (q *Queries) DeleteOwnerKeypair(ctx context.Context, arg DeleteOwnerKeypairParams) error {
	_, err := q.db.Exec(ctx, deleteOwnerKeypair, arg.KeyID, arg.OwnerID)
	return err
}

const getOwnerKeypairByKeyID = `-- name: GetOwnerKeypairByKeyID :one
SELECT id, owner_id, key_id, public_key_pem, label, last_used_at, created_at FROM owner_keypairs WHERE key_id = $1
`

func (q *Queries) GetOwnerKeypairByKeyID(ctx context.Context, keyID string) (OwnerKeypair, error) {
	row := q.db.QueryRow(ctx, getOwnerKeypairByKeyID, keyID)
	var i OwnerKeypair
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.KeyID,
		&i.PublicKeyPem,
		&i.Label,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listOwnerKeypairs = `-- name: ListOwnerKeypairs :many
SELECT id, key_id, label, last_used_at, created_at FROM owner_keypairs
WHERE owner_id = $1
ORDER BY created_at DESC
`

type ListOwnerKeypairsRow struct {
	ID         pgtype.UUID
	KeyID      string
	Label      string
	LastUsedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListOwnerKeypairs(ctx context.Context, ownerID pgtype.UUID) ([]ListOwnerKeypairsRow, error) {
	rows, err := q.db.Query(ctx, listOwnerKeypairs, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnerKeypairsRow
	for rows.Next() {
		var i ListOwnerKeypairsRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyID,
			&i.Label,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchOwnerKeypair = `-- name: TouchOwnerKeypair :exec
UPDATE owner_keypairs SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchOwnerKeypair(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchOwnerKeypair, id)
	return err
}
