// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: owners.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearOwnerPendingEmail = `-- name: ClearOwnerPendingEmail :one
UPDATE owners
SET pending_email = NULL, pending_email_token_hash = '', pending_email_expires_at = NULL
WHERE id = $1
RETURNING id, email, password_hash, recovery_hash, pending_email, pending_email_token_hash, pending_email_expires_at, handle, full_name, location, public_url, byoai_enabled, byoai_providers, byoai_public_blurb, password_reset_hash, password_reset_at, profile_timezone, custom_css, last_vault_import_at, last_vault_import_new, last_vault_import_updated, last_vault_import_skipped, last_vault_import_deleted, created_at
`

// The owner changes their mind. :one + RETURNING is what tells us whether a row was actually
// cleared (:exec throws the row count away).
func (q *Queries) ClearOwnerPendingEmail(ctx context.Context, id pgtype.UUID) (Owner, error) {
	row := q.db.QueryRow(ctx, clearOwnerPendingEmail, id)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.RecoveryHash,
		&i.PendingEmail,
		&i.PendingEmailTokenHash,
		&i.PendingEmailExpiresAt,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.PublicUrl,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.PasswordResetHash,
		&i.PasswordResetAt,
		&i.ProfileTimezone,
		&i.CustomCss,
		&i.LastVaultImportAt,
		&i.LastVaultImportNew,
		&i.LastVaultImportUpdated,
		&i.LastVaultImportSkipped,
		&i.LastVaultImportDeleted,
		&i.CreatedAt,
	)
	return i, err
}

const clearOwnerRecoveryHash = `-- name: ClearOwnerRecoveryHash :exec
UPDATE owners SET recovery_hash = '' WHERE id = $1
`

// #100: invalidate after a successful recovery (single use).
func (q *Queries) ClearOwnerRecoveryHash(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearOwnerRecoveryHash, id)
	return err
}

const clearPasswordResetToken = `-- name: ClearPasswordResetToken :exec
UPDATE owners SET password_reset_hash = ''::bytea, password_reset_at = NULL WHERE id = $1
`

// Clear after a successful reset, making the token single-use.
func (q *Queries) ClearPasswordResetToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearPasswordResetToken, id)
	return err
}

const confirmOwnerPendingEmail = `-- name: ConfirmOwnerPendingEmail :one
UPDATE owners
SET email = pending_email,
    pending_email = NULL,
    pending_email_token_hash = '',
    pending_email_expires_at = NULL
WHERE pending_email_token_hash = $1
  AND pending_email_token_hash <> ''
  AND pending_email IS NOT NULL
  AND pending_email_expires_at > now()
RETURNING id, email, password_hash, recovery_hash, pending_email, pending_email_token_hash, pending_email_expires_at, handle, full_name, location, public_url, byoai_enabled, byoai_providers, byoai_public_blurb, password_reset_hash, password_reset_at, profile_timezone, custom_css, last_vault_import_at, last_vault_import_new, last_vault_import_updated, last_vault_import_skipped, last_vault_import_deleted, created_at
`

// Single-use + not-expired, all decided in this one statement: 0 rows = wrong token / expired /
// already used. After switching, clear all three columns -- a replayable confirmation link is like
// hanging the identity on an old email.
func (q *Queries) ConfirmOwnerPendingEmail(ctx context.Context, pendingEmailTokenHash string) (Owner, error) {
	row := q.db.QueryRow(ctx, confirmOwnerPendingEmail, pendingEmailTokenHash)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.RecoveryHash,
		&i.PendingEmail,
		&i.PendingEmailTokenHash,
		&i.PendingEmailExpiresAt,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.PublicUrl,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.PasswordResetHash,
		&i.PasswordResetAt,
		&i.ProfileTimezone,
		&i.CustomCss,
		&i.LastVaultImportAt,
		&i.LastVaultImportNew,
		&i.LastVaultImportUpdated,
		&i.LastVaultImportSkipped,
		&i.LastVaultImportDeleted,
		&i.CreatedAt,
	)
	return i, err
}

const countOwners = `-- name: CountOwners :one
SELECT COUNT(*) FROM owners
`

func (q *Queries) CountOwners(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOwner = `-- name: CreateOwner :one
INSERT INTO owners (email, password_hash, handle, full_name, public_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, recovery_hash, pending_email, pending_email_token_hash, pending_email_expires_at, handle, full_name, location, public_url, byoai_enabled, byoai_providers, byoai_public_blurb, password_reset_hash, password_reset_at, profile_timezone, custom_css, last_vault_import_at, last_vault_import_new, last_vault_import_updated, last_vault_import_skipped, last_vault_import_deleted, created_at
`

type CreateOwnerParams struct {
	Email        string
	PasswordHash string
	Handle       string
	FullName     string
	PublicUrl    string
}

func (q *Queries) CreateOwner(ctx context.Context, arg CreateOwnerParams) (Owner, error) {
	row := q.db.QueryRow(ctx, createOwner,
		arg.Email,
		arg.PasswordHash,
		arg.Handle,
		arg.FullName,
		arg.PublicUrl,
	)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.RecoveryHash,
		&i.PendingEmail,
		&i.PendingEmailTokenHash,
		&i.PendingEmailExpiresAt,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.PublicUrl,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.PasswordResetHash,
		&i.PasswordResetAt,
		&i.ProfileTimezone,
		&i.CustomCss,
		&i.LastVaultImportAt,
		&i.LastVaultImportNew,
		&i.LastVaultImportUpdated,
		&i.LastVaultImportSkipped,
		&i.LastVaultImportDeleted,
		&i.CreatedAt,
	)
	return i, err
}

const getFirstOwnerHandle = `-- name: GetFirstOwnerHandle :one
SELECT handle FROM owners ORDER BY created_at ASC LIMIT 1
`

// v1 single-owner instance: returns the handle of the earliest-created owner; the app root path uses it to redirect.
func (q *Queries) GetFirstOwnerHandle(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getFirstOwnerHandle)
	var handle string
	err := row.Scan(&handle)
	return handle, err
}

const getFirstOwnerResetToken = `-- name: GetFirstOwnerResetToken :one
SELECT id, password_reset_hash, password_reset_at FROM owners
ORDER BY created_at ASC LIMIT 1
`

type GetFirstOwnerResetTokenRow struct {
	ID                pgtype.UUID
	PasswordResetHash []byte
	PasswordResetAt   pgtype.Timestamptz
}

// single-owner self-host: the reset flow recovers via the sole owner. Returns owner_id + hash + at
// for the usecase to compare + check TTL. Empty table -> ErrNoRows, the caller maps it to unauthorized.
func (q *Queries) GetFirstOwnerResetToken(ctx context.Context) (GetFirstOwnerResetTokenRow, error) {
	row := q.db.QueryRow(ctx, getFirstOwnerResetToken)
	var i GetFirstOwnerResetTokenRow
	err := row.Scan(&i.ID, &i.PasswordResetHash, &i.PasswordResetAt)
	return i, err
}

const getOwnerByEmail = `-- name: GetOwnerByEmail :one
SELECT id, email, password_hash, recovery_hash, pending_email, pending_email_token_hash, pending_email_expires_at, handle, full_name, location, public_url, byoai_enabled, byoai_providers, byoai_public_blurb, password_reset_hash, password_reset_at, profile_timezone, custom_css, last_vault_import_at, last_vault_import_new, last_vault_import_updated, last_vault_import_skipped, last_vault_import_deleted, created_at FROM owners WHERE email = $1
`

func (q *Queries) GetOwnerByEmail(ctx context.Context, email string) (Owner, error) {
	row := q.db.QueryRow(ctx, getOwnerByEmail, email)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.RecoveryHash,
		&i.PendingEmail,
		&i.PendingEmailTokenHash,
		&i.PendingEmailExpiresAt,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.PublicUrl,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.PasswordResetHash,
		&i.PasswordResetAt,
		&i.ProfileTimezone,
		&i.CustomCss,
		&i.LastVaultImportAt,
		&i.LastVaultImportNew,
		&i.LastVaultImportUpdated,
		&i.LastVaultImportSkipped,
		&i.LastVaultImportDeleted,
		&i.CreatedAt,
	)
	return i, err
}

const getOwnerByHandle = `-- name: GetOwnerByHandle :one
SELECT id, email, password_hash, recovery_hash, pending_email, pending_email_token_hash, pending_email_expires_at, handle, full_name, location, public_url, byoai_enabled, byoai_providers, byoai_public_blurb, password_reset_hash, password_reset_at, profile_timezone, custom_css, last_vault_import_at, last_vault_import_new, last_vault_import_updated, last_vault_import_skipped, last_vault_import_deleted, created_at FROM owners WHERE handle = $1
`

func (q *Queries) GetOwnerByHandle(ctx context.Context, handle string) (Owner, error) {
	row := q.db.QueryRow(ctx, getOwnerByHandle, handle)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.RecoveryHash,
		&i.PendingEmail,
		&i.PendingEmailTokenHash,
		&i.PendingEmailExpiresAt,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.PublicUrl,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.PasswordResetHash,
		&i.PasswordResetAt,
		&i.ProfileTimezone,
		&i.CustomCss,
		&i.LastVaultImportAt,
		&i.LastVaultImportNew,
		&i.LastVaultImportUpdated,
		&i.LastVaultImportSkipped,
		&i.LastVaultImportDeleted,
		&i.CreatedAt,
	)
	return i, err
}

const getOwnerByID = `-- name: GetOwnerByID :one
SELECT id, email, password_hash, recovery_hash, pending_email, pending_email_token_hash, pending_email_expires_at, handle, full_name, location, public_url, byoai_enabled, byoai_providers, byoai_public_blurb, password_reset_hash, password_reset_at, profile_timezone, custom_css, last_vault_import_at, last_vault_import_new, last_vault_import_updated, last_vault_import_skipped, last_vault_import_deleted, created_at FROM owners WHERE id = $1
`

func (q *Queries) GetOwnerByID(ctx context.Context, id pgtype.UUID) (Owner, error) {
	row := q.db.QueryRow(ctx, getOwnerByID, id)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.RecoveryHash,
		&i.PendingEmail,
		&i.PendingEmailTokenHash,
		&i.PendingEmailExpiresAt,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.PublicUrl,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.PasswordResetHash,
		&i.PasswordResetAt,
		&i.ProfileTimezone,
		&i.CustomCss,
		&i.LastVaultImportAt,
		&i.LastVaultImportNew,
		&i.LastVaultImportUpdated,
		&i.LastVaultImportSkipped,
		&i.LastVaultImportDeleted,
		&i.CreatedAt,
	)
	return i, err
}

const getOwnerByPendingToken = `-- name: GetOwnerByPendingToken :one
SELECT id, email, password_hash, recovery_hash, pending_email, pending_email_token_hash, pending_email_expires_at, handle, full_name, location, public_url, byoai_enabled, byoai_providers, byoai_public_blurb, password_reset_hash, password_reset_at, profile_timezone, custom_css, last_vault_import_at, last_vault_import_new, last_vault_import_updated, last_vault_import_skipped, last_vault_import_deleted, created_at FROM owners
WHERE pending_email_token_hash = $1 AND pending_email_token_hash <> ''
`

// Only to distinguish "expired" from "invalid outright" -- neither switches the identity, but what
// we tell the owner differs, and what they should do next depends on that distinction.
func (q *Queries) GetOwnerByPendingToken(ctx context.Context, pendingEmailTokenHash string) (Owner, error) {
	row := q.db.QueryRow(ctx, getOwnerByPendingToken, pendingEmailTokenHash)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.RecoveryHash,
		&i.PendingEmail,
		&i.PendingEmailTokenHash,
		&i.PendingEmailExpiresAt,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.PublicUrl,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.PasswordResetHash,
		&i.PasswordResetAt,
		&i.ProfileTimezone,
		&i.CustomCss,
		&i.LastVaultImportAt,
		&i.LastVaultImportNew,
		&i.LastVaultImportUpdated,
		&i.LastVaultImportSkipped,
		&i.LastVaultImportDeleted,
		&i.CreatedAt,
	)
	return i, err
}

const getOwnerCSS = `-- name: GetOwnerCSS :one
SELECT custom_css FROM owners WHERE id = $1
`

// The owner's custom CSS (the safe, already sanitized+scoped version).
func (q *Queries) GetOwnerCSS(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getOwnerCSS, id)
	var custom_css string
	err := row.Scan(&custom_css)
	return custom_css, err
}

const getOwnerPasswordHash = `-- name: GetOwnerPasswordHash :one
SELECT password_hash FROM owners WHERE id = $1
`

func (q *Queries) GetOwnerPasswordHash(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getOwnerPasswordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const recordVaultImport = `-- name: RecordVaultImport :execrows
UPDATE owners
SET last_vault_import_at = now(),
    last_vault_import_new = $2,
    last_vault_import_updated = $3,
    last_vault_import_skipped = $4,
    last_vault_import_deleted = $5
WHERE id = $1
`

type RecordVaultImportParams struct {
	ID                     pgtype.UUID
	LastVaultImportNew     int32
	LastVaultImportUpdated int32
	LastVaultImportSkipped int32
	LastVaultImportDeleted int32
}

// UX-62: record the "last vault import" -- the import is the operation that defines this product's
// ground truth, and before this "did it happen" had no landing spot in the DB, so that on-screen
// count vanished on refresh.
// :execrows rather than :exec -- hitting 0 rows must be reportable ([[write-with-no-receipt]]).
func (q *Queries) RecordVaultImport(ctx context.Context, arg RecordVaultImportParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordVaultImport,
		arg.ID,
		arg.LastVaultImportNew,
		arg.LastVaultImportUpdated,
		arg.LastVaultImportSkipped,
		arg.LastVaultImportDeleted,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setOwnerCSS = `-- name: SetOwnerCSS :exec
UPDATE owners SET custom_css = $2 WHERE id = $1
`

type SetOwnerCSSParams struct {
	ID        pgtype.UUID
	CustomCss string
}

// Store the owner's CSS (what the caller passes in should already be the sanitized+scoped safe version).
func (q *Queries) SetOwnerCSS(ctx context.Context, arg SetOwnerCSSParams) error {
	_, err := q.db.Exec(ctx, setOwnerCSS, arg.ID, arg.CustomCss)
	return err
}

const setOwnerPendingEmail = `-- name: SetOwnerPendingEmail :one
UPDATE owners
SET pending_email = $2, pending_email_token_hash = $3, pending_email_expires_at = $4
WHERE id = $1
RETURNING id, email, password_hash, recovery_hash, pending_email, pending_email_token_hash, pending_email_expires_at, handle, full_name, location, public_url, byoai_enabled, byoai_providers, byoai_public_blurb, password_reset_hash, password_reset_at, profile_timezone, custom_css, last_vault_import_at, last_vault_import_new, last_vault_import_updated, last_vault_import_skipped, last_vault_import_deleted, created_at
`

type SetOwnerPendingEmailParams struct {
	ID                    pgtype.UUID
	PendingEmail          *string
	PendingEmailTokenHash string
	PendingEmailExpiresAt pgtype.Timestamptz
}

// An email change pending confirmation. The identity **does not move** -- it only switches when the
// link in the email is clicked.
// A second request simply overwrites: if both worked, the owner thinks they changed to the latter,
// while one click on an old tab would send the identity to the former.
func (q *Queries) SetOwnerPendingEmail(ctx context.Context, arg SetOwnerPendingEmailParams) (Owner, error) {
	row := q.db.QueryRow(ctx, setOwnerPendingEmail,
		arg.ID,
		arg.PendingEmail,
		arg.PendingEmailTokenHash,
		arg.PendingEmailExpiresAt,
	)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.RecoveryHash,
		&i.PendingEmail,
		&i.PendingEmailTokenHash,
		&i.PendingEmailExpiresAt,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.PublicUrl,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.PasswordResetHash,
		&i.PasswordResetAt,
		&i.ProfileTimezone,
		&i.CustomCss,
		&i.LastVaultImportAt,
		&i.LastVaultImportNew,
		&i.LastVaultImportUpdated,
		&i.LastVaultImportSkipped,
		&i.LastVaultImportDeleted,
		&i.CreatedAt,
	)
	return i, err
}

const setOwnerRecoveryHash = `-- name: SetOwnerRecoveryHash :exec
UPDATE owners SET recovery_hash = $2 WHERE id = $1
`

type SetOwnerRecoveryHashParams struct {
	ID           pgtype.UUID
	RecoveryHash string
}

// #100: store/rotate the hash of the recovery phrase (the plaintext goes only into the email).
func (q *Queries) SetOwnerRecoveryHash(ctx context.Context, arg SetOwnerRecoveryHashParams) error {
	_, err := q.db.Exec(ctx, setOwnerRecoveryHash, arg.ID, arg.RecoveryHash)
	return err
}

const setPasswordResetToken = `-- name: SetPasswordResetToken :exec
UPDATE owners SET password_reset_hash = $2, password_reset_at = NOW() WHERE id = $1
`

type SetPasswordResetTokenParams struct {
	ID                pgtype.UUID
	PasswordResetHash []byte
}

// Emergency reset token: write the hash + current time. Each owner may have only one reset token at
// a time; the old one is overwritten by the new ("re-run the command" is also valid UX).
func (q *Queries) SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, setPasswordResetToken, arg.ID, arg.PasswordResetHash)
	return err
}

const updateOwnerBYOAI = `-- name: UpdateOwnerBYOAI :one
UPDATE owners
SET byoai_enabled = $2,
    byoai_providers = $3,
    byoai_public_blurb = $4
WHERE id = $1
RETURNING id, email, password_hash, recovery_hash, pending_email, pending_email_token_hash, pending_email_expires_at, handle, full_name, location, public_url, byoai_enabled, byoai_providers, byoai_public_blurb, password_reset_hash, password_reset_at, profile_timezone, custom_css, last_vault_import_at, last_vault_import_new, last_vault_import_updated, last_vault_import_skipped, last_vault_import_deleted, created_at
`

type UpdateOwnerBYOAIParams struct {
	ID               pgtype.UUID
	ByoaiEnabled     bool
	ByoaiProviders   []byte
	ByoaiPublicBlurb string
}

func (q *Queries) UpdateOwnerBYOAI(ctx context.Context, arg UpdateOwnerBYOAIParams) (Owner, error) {
	row := q.db.QueryRow(ctx, updateOwnerBYOAI,
		arg.ID,
		arg.ByoaiEnabled,
		arg.ByoaiProviders,
		arg.ByoaiPublicBlurb,
	)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.RecoveryHash,
		&i.PendingEmail,
		&i.PendingEmailTokenHash,
		&i.PendingEmailExpiresAt,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.PublicUrl,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.PasswordResetHash,
		&i.PasswordResetAt,
		&i.ProfileTimezone,
		&i.CustomCss,
		&i.LastVaultImportAt,
		&i.LastVaultImportNew,
		&i.LastVaultImportUpdated,
		&i.LastVaultImportSkipped,
		&i.LastVaultImportDeleted,
		&i.CreatedAt,
	)
	return i, err
}

const updateOwnerEmail = `-- name: UpdateOwnerEmail :one
UPDATE owners
SET email = $2
WHERE id = $1
RETURNING id, email, password_hash, recovery_hash, pending_email, pending_email_token_hash, pending_email_expires_at, handle, full_name, location, public_url, byoai_enabled, byoai_providers, byoai_public_blurb, password_reset_hash, password_reset_at, profile_timezone, custom_css, last_vault_import_at, last_vault_import_new, last_vault_import_updated, last_vault_import_skipped, last_vault_import_deleted, created_at
`

type UpdateOwnerEmailParams struct {
	ID    pgtype.UUID
	Email string
}

func (q *Queries) UpdateOwnerEmail(ctx context.Context, arg UpdateOwnerEmailParams) (Owner, error) {
	row := q.db.QueryRow(ctx, updateOwnerEmail, arg.ID, arg.Email)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.RecoveryHash,
		&i.PendingEmail,
		&i.PendingEmailTokenHash,
		&i.PendingEmailExpiresAt,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.PublicUrl,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.PasswordResetHash,
		&i.PasswordResetAt,
		&i.ProfileTimezone,
		&i.CustomCss,
		&i.LastVaultImportAt,
		&i.LastVaultImportNew,
		&i.LastVaultImportUpdated,
		&i.LastVaultImportSkipped,
		&i.LastVaultImportDeleted,
		&i.CreatedAt,
	)
	return i, err
}

const updateOwnerFullName = `-- name: UpdateOwnerFullName :one
UPDATE owners
SET full_name = $2
WHERE id = $1
RETURNING id, email, password_hash, recovery_hash, pending_email, pending_email_token_hash, pending_email_expires_at, handle, full_name, location, public_url, byoai_enabled, byoai_providers, byoai_public_blurb, password_reset_hash, password_reset_at, profile_timezone, custom_css, last_vault_import_at, last_vault_import_new, last_vault_import_updated, last_vault_import_skipped, last_vault_import_deleted, created_at
`

type UpdateOwnerFullNameParams struct {
	ID       pgtype.UUID
	FullName string
}

func (q *Queries) UpdateOwnerFullName(ctx context.Context, arg UpdateOwnerFullNameParams) (Owner, error) {
	row := q.db.QueryRow(ctx, updateOwnerFullName, arg.ID, arg.FullName)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.RecoveryHash,
		&i.PendingEmail,
		&i.PendingEmailTokenHash,
		&i.PendingEmailExpiresAt,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.PublicUrl,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.PasswordResetHash,
		&i.PasswordResetAt,
		&i.ProfileTimezone,
		&i.CustomCss,
		&i.LastVaultImportAt,
		&i.LastVaultImportNew,
		&i.LastVaultImportUpdated,
		&i.LastVaultImportSkipped,
		&i.LastVaultImportDeleted,
		&i.CreatedAt,
	)
	return i, err
}

const updateOwnerPasswordHash = `-- name: UpdateOwnerPasswordHash :one
UPDATE owners
SET password_hash = $2
WHERE id = $1
RETURNING id, email, password_hash, recovery_hash, pending_email, pending_email_token_hash, pending_email_expires_at, handle, full_name, location, public_url, byoai_enabled, byoai_providers, byoai_public_blurb, password_reset_hash, password_reset_at, profile_timezone, custom_css, last_vault_import_at, last_vault_import_new, last_vault_import_updated, last_vault_import_skipped, last_vault_import_deleted, created_at
`

type UpdateOwnerPasswordHashParams struct {
	ID           pgtype.UUID
	PasswordHash string
}

func (q *Queries) UpdateOwnerPasswordHash(ctx context.Context, arg UpdateOwnerPasswordHashParams) (Owner, error) {
	row := q.db.QueryRow(ctx, updateOwnerPasswordHash, arg.ID, arg.PasswordHash)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.RecoveryHash,
		&i.PendingEmail,
		&i.PendingEmailTokenHash,
		&i.PendingEmailExpiresAt,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.PublicUrl,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.PasswordResetHash,
		&i.PasswordResetAt,
		&i.ProfileTimezone,
		&i.CustomCss,
		&i.LastVaultImportAt,
		&i.LastVaultImportNew,
		&i.LastVaultImportUpdated,
		&i.LastVaultImportSkipped,
		&i.LastVaultImportDeleted,
		&i.CreatedAt,
	)
	return i, err
}

const updateOwnerProfileTimezone = `-- name: UpdateOwnerProfileTimezone :one
UPDATE owners
SET profile_timezone = $2
WHERE id = $1
RETURNING id, email, password_hash, recovery_hash, pending_email, pending_email_token_hash, pending_email_expires_at, handle, full_name, location, public_url, byoai_enabled, byoai_providers, byoai_public_blurb, password_reset_hash, password_reset_at, profile_timezone, custom_css, last_vault_import_at, last_vault_import_new, last_vault_import_updated, last_vault_import_skipped, last_vault_import_deleted, created_at
`

type UpdateOwnerProfileTimezoneParams struct {
	ID              pgtype.UUID
	ProfileTimezone string
}

func (q *Queries) UpdateOwnerProfileTimezone(ctx context.Context, arg UpdateOwnerProfileTimezoneParams) (Owner, error) {
	row := q.db.QueryRow(ctx, updateOwnerProfileTimezone, arg.ID, arg.ProfileTimezone)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.RecoveryHash,
		&i.PendingEmail,
		&i.PendingEmailTokenHash,
		&i.PendingEmailExpiresAt,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.PublicUrl,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.PasswordResetHash,
		&i.PasswordResetAt,
		&i.ProfileTimezone,
		&i.CustomCss,
		&i.LastVaultImportAt,
		&i.LastVaultImportNew,
		&i.LastVaultImportUpdated,
		&i.LastVaultImportSkipped,
		&i.LastVaultImportDeleted,
		&i.CreatedAt,
	)
	return i, err
}

const updateOwnerPublicURL = `-- name: UpdateOwnerPublicURL :one

UPDATE owners
SET public_url = $2
WHERE id = $1
RETURNING id, email, password_hash, recovery_hash, pending_email, pending_email_token_hash, pending_email_expires_at, handle, full_name, location, public_url, byoai_enabled, byoai_providers, byoai_public_blurb, password_reset_hash, password_reset_at, profile_timezone, custom_css, last_vault_import_at, last_vault_import_new, last_vault_import_updated, last_vault_import_skipped, last_vault_import_deleted, created_at
`

type UpdateOwnerPublicURLParams struct {
	ID        pgtype.UUID
	PublicUrl string
}

// UpdateOwnerAIProvider was deleted with the four ai_* columns: an owner holds a *book* of
// providers now (owner_providers.sql), one of them marked default. Writing "the owner's provider"
// is writing one row of that book.
func (q *Queries) UpdateOwnerPublicURL(ctx context.Context, arg UpdateOwnerPublicURLParams) (Owner, error) {
	row := q.db.QueryRow(ctx, updateOwnerPublicURL, arg.ID, arg.PublicUrl)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.RecoveryHash,
		&i.PendingEmail,
		&i.PendingEmailTokenHash,
		&i.PendingEmailExpiresAt,
		&i.Handle,
		&i.FullName,
		&i.Location,
		&i.PublicUrl,
		&i.ByoaiEnabled,
		&i.ByoaiProviders,
		&i.ByoaiPublicBlurb,
		&i.PasswordResetHash,
		&i.PasswordResetAt,
		&i.ProfileTimezone,
		&i.CustomCss,
		&i.LastVaultImportAt,
		&i.LastVaultImportNew,
		&i.LastVaultImportUpdated,
		&i.LastVaultImportSkipped,
		&i.LastVaultImportDeleted,
		&i.CreatedAt,
	)
	return i, err
}
