// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: prompts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPrompt = `-- name: CreatePrompt :one

INSERT INTO prompts (owner_id, name, description, body)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, name, body, description, is_builtin, created_at, updated_at
`

type CreatePromptParams struct {
	OwnerID     pgtype.UUID
	Name        string
	Description string
	Body        string
}

// prompts -- owner-scoped persona library. Semantics in schema.sql + [[iam-role-pivot-plan]].
//
// public (is_builtin=true) is seeded by the SeedPublicRole upsert; ones the owner adds themselves
// = false. Deleting a builtin is blocked at the repo layer (domain.ErrPromptBuiltinImmutable).
func (q *Queries) CreatePrompt(ctx context.Context, arg CreatePromptParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, createPrompt,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Body,
	)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Body,
		&i.Description,
		&i.IsBuiltin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePrompt = `-- name: DeletePrompt :exec
DELETE FROM prompts WHERE id = $1 AND owner_id = $2 AND is_builtin = false
`

type DeletePromptParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

// Deletes non-builtin only; builtin is never allowed to be deleted (blocked by the repo layer above).
func (q *Queries) DeletePrompt(ctx context.Context, arg DeletePromptParams) error {
	_, err := q.db.Exec(ctx, deletePrompt, arg.ID, arg.OwnerID)
	return err
}

const getPromptByID = `-- name: GetPromptByID :one
SELECT id, owner_id, name, body, description, is_builtin, created_at, updated_at FROM prompts WHERE id = $1 AND owner_id = $2
`

type GetPromptByIDParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetPromptByID(ctx context.Context, arg GetPromptByIDParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, getPromptByID, arg.ID, arg.OwnerID)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Body,
		&i.Description,
		&i.IsBuiltin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromptByName = `-- name: GetPromptByName :one
SELECT id, owner_id, name, body, description, is_builtin, created_at, updated_at FROM prompts WHERE owner_id = $1 AND name = $2
`

type GetPromptByNameParams struct {
	OwnerID pgtype.UUID
	Name    string
}

func (q *Queries) GetPromptByName(ctx context.Context, arg GetPromptByNameParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, getPromptByName, arg.OwnerID, arg.Name)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Body,
		&i.Description,
		&i.IsBuiltin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPromptsByOwner = `-- name: ListPromptsByOwner :many
SELECT id, owner_id, name, body, description, is_builtin, created_at, updated_at FROM prompts WHERE owner_id = $1 ORDER BY is_builtin DESC, name ASC
`

func (q *Queries) ListPromptsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Prompt, error) {
	rows, err := q.db.Query(ctx, listPromptsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prompt
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Body,
			&i.Description,
			&i.IsBuiltin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrompt = `-- name: UpdatePrompt :one
UPDATE prompts
SET name = $3, description = $4, body = $5, updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, name, body, description, is_builtin, created_at, updated_at
`

type UpdatePromptParams struct {
	ID          pgtype.UUID
	OwnerID     pgtype.UUID
	Name        string
	Description string
	Body        string
}

// Builtin (public) can also update body / description (the owner tweaks the public copy);
// the repo layer rejects builtin rename + delete.
func (q *Queries) UpdatePrompt(ctx context.Context, arg UpdatePromptParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, updatePrompt,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Body,
	)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Body,
		&i.Description,
		&i.IsBuiltin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBuiltinPrompt = `-- name: UpsertBuiltinPrompt :one
INSERT INTO prompts (owner_id, name, description, body, is_builtin)
VALUES ($1, $2, $3, $4, true)
ON CONFLICT (owner_id, name) DO UPDATE SET
    description = EXCLUDED.description,
    body        = EXCLUDED.body,
    updated_at  = now()
RETURNING id, owner_id, name, body, description, is_builtin, created_at, updated_at
`

type UpsertBuiltinPromptParams struct {
	OwnerID     pgtype.UUID
	Name        string
	Description string
	Body        string
}

// Seed builtin prompt: idempotent by (owner_id, name).
// description / body are overwritten with EXCLUDED, so a future seed adjustment lands on re-run.
func (q *Queries) UpsertBuiltinPrompt(ctx context.Context, arg UpsertBuiltinPromptParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, upsertBuiltinPrompt,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Body,
	)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Body,
		&i.Description,
		&i.IsBuiltin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
