# Generated by Django 6.0.2 on 2026-02-28 00:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentEntryModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=500, unique=True)),
                ("content", models.JSONField(default=dict)),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "content_type",
                    models.CharField(default="application/json", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "content_entries",
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="InviteCodeModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=100, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("max_uses", models.PositiveIntegerField(blank=True, null=True)),
                ("use_count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "invite_codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PathPermissionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny")], max_length=10
                    ),
                ),
                ("path_pattern", models.CharField(max_length=500)),
                ("order", models.IntegerField(default=0)),
                (
                    "invite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="persistence.invitecodemodel",
                    ),
                ),
            ],
            options={
                "db_table": "path_permissions",
                "ordering": ["order"],
            },
        ),
    ]
