# Generated by Django 6.0.2 on 2026-02-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitecodemodel",
            name="prompt",
            field=models.TextField(blank=True, default=""),
        ),
    ]
