# Generated by Django 6.0.2 on 2026-02-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0004_add_role_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolemodel",
            name="prompt",
            field=models.TextField(blank=True, default=""),
        ),
    ]
