// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: app_state.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAppState = `-- name: DeleteAppState :exec
DELETE FROM mcp_app_state
WHERE member_id = $1 AND mcp_id = $2 AND state_key = $3
`

type DeleteAppStateParams struct {
	MemberID pgtype.UUID
	McpID    string
	StateKey string
}

func (q *Queries) DeleteAppState(ctx context.Context, arg DeleteAppStateParams) error {
	_, err := q.db.Exec(ctx, deleteAppState, arg.MemberID, arg.McpID, arg.StateKey)
	return err
}

const getAppStateByMCP = `-- name: GetAppStateByMCP :many
SELECT state_key, value FROM mcp_app_state
WHERE member_id = $1 AND mcp_id = $2
ORDER BY state_key
`

type GetAppStateByMCPParams struct {
	MemberID pgtype.UUID
	McpID    string
}

type GetAppStateByMCPRow struct {
	StateKey string
	Value    []byte
}

func (q *Queries) GetAppStateByMCP(ctx context.Context, arg GetAppStateByMCPParams) ([]GetAppStateByMCPRow, error) {
	rows, err := q.db.Query(ctx, getAppStateByMCP, arg.MemberID, arg.McpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAppStateByMCPRow
	for rows.Next() {
		var i GetAppStateByMCPRow
		if err := rows.Scan(&i.StateKey, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAppState = `-- name: UpsertAppState :exec

INSERT INTO mcp_app_state (owner_id, member_id, mcp_id, state_key, value)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (member_id, mcp_id, state_key) DO UPDATE SET
    value      = EXCLUDED.value,
    updated_at = now()
`

type UpsertAppStateParams struct {
	OwnerID  pgtype.UUID
	MemberID pgtype.UUID
	McpID    string
	StateKey string
	Value    []byte
}

// mcp_app_state —— MCP App state across refreshes. scope = (member, mcp_id); mcp_id is derived by the
// backend from the tool. get the whole cell, upsert one key, delete one key.
func (q *Queries) UpsertAppState(ctx context.Context, arg UpsertAppStateParams) error {
	_, err := q.db.Exec(ctx, upsertAppState,
		arg.OwnerID,
		arg.MemberID,
		arg.McpID,
		arg.StateKey,
		arg.Value,
	)
	return err
}
