// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: chat_reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChatReport = `-- name: GetChatReport :one
SELECT id, owner_id, conversation_id, html, created_at FROM chat_reports WHERE id = $1
`

func (q *Queries) GetChatReport(ctx context.Context, id pgtype.UUID) (ChatReport, error) {
	row := q.db.QueryRow(ctx, getChatReport, id)
	var i ChatReport
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConversationID,
		&i.Html,
		&i.CreatedAt,
	)
	return i, err
}

const upsertChatReport = `-- name: UpsertChatReport :one
INSERT INTO chat_reports (owner_id, conversation_id, html)
VALUES ($1, $2, $3)
ON CONFLICT (conversation_id) DO UPDATE SET html = EXCLUDED.html
RETURNING id, owner_id, conversation_id, html, created_at
`

type UpsertChatReportParams struct {
	OwnerID        pgtype.UUID
	ConversationID pgtype.UUID
	Html           string
}

// #129 one per conversation: if the conversation already has a report → rewrite html (revise), returning the same row (report_id stable).
func (q *Queries) UpsertChatReport(ctx context.Context, arg UpsertChatReportParams) (ChatReport, error) {
	row := q.db.QueryRow(ctx, upsertChatReport, arg.OwnerID, arg.ConversationID, arg.Html)
	var i ChatReport
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConversationID,
		&i.Html,
		&i.CreatedAt,
	)
	return i, err
}
