// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: conversation_ghosts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ghostWaypointTelemetry = `-- name: GhostWaypointTelemetry :many
SELECT
    target_waypoint,
    COUNT(*)::bigint            AS shown,
    COUNT(accepted_at)::bigint  AS accepted
FROM conversation_ghosts
WHERE owner_id = $1 AND source = 'policy' AND target_waypoint IS NOT NULL
GROUP BY target_waypoint
ORDER BY target_waypoint ASC
`

type GhostWaypointTelemetryRow struct {
	TargetWaypoint *string
	Shown          int64
	Accepted       int64
}

// ghost-steering telemetry: per-waypoint funnel (shown vs accepted) over the owner's policy ghosts.
// accepted = accepted_at IS NOT NULL. Only source='policy' rows carry a target_waypoint.
func (q *Queries) GhostWaypointTelemetry(ctx context.Context, ownerID pgtype.UUID) ([]GhostWaypointTelemetryRow, error) {
	rows, err := q.db.Query(ctx, ghostWaypointTelemetry, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GhostWaypointTelemetryRow
	for rows.Next() {
		var i GhostWaypointTelemetryRow
		if err := rows.Scan(&i.TargetWaypoint, &i.Shown, &i.Accepted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGhostsByConversation = `-- name: ListGhostsByConversation :many
SELECT id, owner_id, conversation_id, turn_index, ghost_text, source, target_waypoint, follows_from, shown_at, accepted_at FROM conversation_ghosts
WHERE conversation_id = $1 AND owner_id = $2
ORDER BY shown_at ASC
`

type ListGhostsByConversationParams struct {
	ConversationID pgtype.UUID
	OwnerID        pgtype.UUID
}

func (q *Queries) ListGhostsByConversation(ctx context.Context, arg ListGhostsByConversationParams) ([]ConversationGhost, error) {
	rows, err := q.db.Query(ctx, listGhostsByConversation, arg.ConversationID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationGhost
	for rows.Next() {
		var i ConversationGhost
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ConversationID,
			&i.TurnIndex,
			&i.GhostText,
			&i.Source,
			&i.TargetWaypoint,
			&i.FollowsFrom,
			&i.ShownAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGhostAccepted = `-- name: MarkGhostAccepted :one
UPDATE conversation_ghosts
SET accepted_at = now()
WHERE id = $1 AND conversation_id = $2 AND owner_id = $3
RETURNING id, owner_id, conversation_id, turn_index, ghost_text, source, target_waypoint, follows_from, shown_at, accepted_at
`

type MarkGhostAcceptedParams struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	OwnerID        pgtype.UUID
}

func (q *Queries) MarkGhostAccepted(ctx context.Context, arg MarkGhostAcceptedParams) (ConversationGhost, error) {
	row := q.db.QueryRow(ctx, markGhostAccepted, arg.ID, arg.ConversationID, arg.OwnerID)
	var i ConversationGhost
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConversationID,
		&i.TurnIndex,
		&i.GhostText,
		&i.Source,
		&i.TargetWaypoint,
		&i.FollowsFrom,
		&i.ShownAt,
		&i.AcceptedAt,
	)
	return i, err
}

const recordPolicyGhost = `-- name: RecordPolicyGhost :one
INSERT INTO conversation_ghosts (
    owner_id, conversation_id, turn_index, ghost_text, source, target_waypoint, follows_from
)
VALUES ($1, $2, $3, $4, 'policy', $5, $6)
RETURNING id, owner_id, conversation_id, turn_index, ghost_text, source, target_waypoint, follows_from, shown_at, accepted_at
`

type RecordPolicyGhostParams struct {
	OwnerID        pgtype.UUID
	ConversationID pgtype.UUID
	TurnIndex      int32
	GhostText      string
	TargetWaypoint *string
	FollowsFrom    *string
}

// ghost-steering P3: policy 出的 ghost，带 heading tag(target_waypoint) + coherence hook(follows_from)。
func (q *Queries) RecordPolicyGhost(ctx context.Context, arg RecordPolicyGhostParams) (ConversationGhost, error) {
	row := q.db.QueryRow(ctx, recordPolicyGhost,
		arg.OwnerID,
		arg.ConversationID,
		arg.TurnIndex,
		arg.GhostText,
		arg.TargetWaypoint,
		arg.FollowsFrom,
	)
	var i ConversationGhost
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConversationID,
		&i.TurnIndex,
		&i.GhostText,
		&i.Source,
		&i.TargetWaypoint,
		&i.FollowsFrom,
		&i.ShownAt,
		&i.AcceptedAt,
	)
	return i, err
}

const recordShownGhost = `-- name: RecordShownGhost :one
INSERT INTO conversation_ghosts (
    owner_id, conversation_id, turn_index, ghost_text, source
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, conversation_id, turn_index, ghost_text, source, target_waypoint, follows_from, shown_at, accepted_at
`

type RecordShownGhostParams struct {
	OwnerID        pgtype.UUID
	ConversationID pgtype.UUID
	TurnIndex      int32
	GhostText      string
	Source         string
}

func (q *Queries) RecordShownGhost(ctx context.Context, arg RecordShownGhostParams) (ConversationGhost, error) {
	row := q.db.QueryRow(ctx, recordShownGhost,
		arg.OwnerID,
		arg.ConversationID,
		arg.TurnIndex,
		arg.GhostText,
		arg.Source,
	)
	var i ConversationGhost
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConversationID,
		&i.TurnIndex,
		&i.GhostText,
		&i.Source,
		&i.TargetWaypoint,
		&i.FollowsFrom,
		&i.ShownAt,
		&i.AcceptedAt,
	)
	return i, err
}
