// chat_report.go —— I.3: an HTML report generated by the
// summarize_conversation tool call at the end (or midway) of a visitor
// chat. Each call stores a new row (allowing the same conversation to
// regenerate multiple times); the conversation is never marked ended, so
// it can keep going.

package entity

import (
	"errors"
	"time"
)

// ErrReportNotFound —— returned as 404 when GET /report/{id} finds nothing
// (wrong id / deleted by cascade).
var ErrReportNotFound = errors.New("chat report not found")

// ChatReport —— one HTML report row. HTML is the full body output
// directly by the AI; the frontend renders it in a sandboxed iframe.
type ChatReport struct {
	CreatedAt      time.Time
	ID             string
	OwnerID        string
	ConversationID string
	HTML           string
}
