// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: banned_ips.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const banIP = `-- name: BanIP :one
INSERT INTO banned_ips (owner_id, ip, reason, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (owner_id, ip) DO UPDATE
SET reason = EXCLUDED.reason,
    expires_at = EXCLUDED.expires_at,
    created_at = now()
RETURNING id, owner_id, ip, reason, expires_at, created_at
`

type BanIPParams struct {
	OwnerID   pgtype.UUID
	Ip        string
	Reason    string
	ExpiresAt pgtype.Timestamptz
}

// 封一个 IP。重复封同一 (owner, ip) 覆盖 reason/expires_at 并刷新 created_at
// (等于「重新封」)。
func (q *Queries) BanIP(ctx context.Context, arg BanIPParams) (BannedIp, error) {
	row := q.db.QueryRow(ctx, banIP,
		arg.OwnerID,
		arg.Ip,
		arg.Reason,
		arg.ExpiresAt,
	)
	var i BannedIp
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Ip,
		&i.Reason,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const isIPBanned = `-- name: IsIPBanned :one
SELECT EXISTS (
    SELECT 1 FROM banned_ips
    WHERE owner_id = $1 AND ip = $2
      AND (expires_at IS NULL OR expires_at > now())
) AS banned
`

type IsIPBannedParams struct {
	OwnerID pgtype.UUID
	Ip      string
}

// enforcement 查询：该 owner 是否封了这个 IP 且未过期。expires_at IS NULL =
// 永久。返回布尔。
func (q *Queries) IsIPBanned(ctx context.Context, arg IsIPBannedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isIPBanned, arg.OwnerID, arg.Ip)
	var banned bool
	err := row.Scan(&banned)
	return banned, err
}

const isIPBannedAnywhere = `-- name: IsIPBannedAnywhere :one
SELECT EXISTS (
    SELECT 1 FROM banned_ips
    WHERE ip = $1 AND (expires_at IS NULL OR expires_at > now())
) AS banned
`

// 公开面 enforcement 用：这个 IP 在本实例上是否被任何 owner 封了且未过期。
// v1 单 owner，等价于「sole owner 封没封」，但不需 middleware 解析 owner。
// 多租户起再换成 host→owner 作用域。
func (q *Queries) IsIPBannedAnywhere(ctx context.Context, ip string) (bool, error) {
	row := q.db.QueryRow(ctx, isIPBannedAnywhere, ip)
	var banned bool
	err := row.Scan(&banned)
	return banned, err
}

const listBannedIPs = `-- name: ListBannedIPs :many
SELECT id, owner_id, ip, reason, expires_at, created_at FROM banned_ips
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBannedIPs(ctx context.Context, ownerID pgtype.UUID) ([]BannedIp, error) {
	rows, err := q.db.Query(ctx, listBannedIPs, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BannedIp
	for rows.Next() {
		var i BannedIp
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Ip,
			&i.Reason,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unbanIPByID = `-- name: UnbanIPByID :exec
DELETE FROM banned_ips
WHERE id = $1 AND owner_id = $2
`

type UnbanIPByIDParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) UnbanIPByID(ctx context.Context, arg UnbanIPByIDParams) error {
	_, err := q.db.Exec(ctx, unbanIPByID, arg.ID, arg.OwnerID)
	return err
}
