// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: skills.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (
    owner_id, name, description, prompt, scripts, metadata,
    allowed_tools, is_builtin, version, license, source
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, owner_id, name, description, prompt, scripts, metadata, allowed_tools, is_builtin, enabled, version, license, source, created_at, updated_at
`

type CreateSkillParams struct {
	OwnerID      pgtype.UUID
	Name         string
	Description  string
	Prompt       string
	Scripts      []byte
	Metadata     []byte
	AllowedTools []string
	IsBuiltin    bool
	Version      string
	License      string
	Source       string
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Prompt,
		arg.Scripts,
		arg.Metadata,
		arg.AllowedTools,
		arg.IsBuiltin,
		arg.Version,
		arg.License,
		arg.Source,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Prompt,
		&i.Scripts,
		&i.Metadata,
		&i.AllowedTools,
		&i.IsBuiltin,
		&i.Enabled,
		&i.Version,
		&i.License,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSkill = `-- name: DeleteSkill :exec
DELETE FROM skills WHERE id = $1 AND owner_id = $2 AND is_builtin = false
`

type DeleteSkillParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) DeleteSkill(ctx context.Context, arg DeleteSkillParams) error {
	_, err := q.db.Exec(ctx, deleteSkill, arg.ID, arg.OwnerID)
	return err
}

const getSkillByID = `-- name: GetSkillByID :one
SELECT id, owner_id, name, description, prompt, scripts, metadata, allowed_tools, is_builtin, enabled, version, license, source, created_at, updated_at FROM skills WHERE id = $1 AND owner_id = $2
`

type GetSkillByIDParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetSkillByID(ctx context.Context, arg GetSkillByIDParams) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkillByID, arg.ID, arg.OwnerID)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Prompt,
		&i.Scripts,
		&i.Metadata,
		&i.AllowedTools,
		&i.IsBuiltin,
		&i.Enabled,
		&i.Version,
		&i.License,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSkillsByOwner = `-- name: ListSkillsByOwner :many
SELECT id, owner_id, name, description, prompt, scripts, metadata, allowed_tools, is_builtin, enabled, version, license, source, created_at, updated_at FROM skills WHERE owner_id = $1 ORDER BY is_builtin DESC, name ASC
`

func (q *Queries) ListSkillsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkillsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Prompt,
			&i.Scripts,
			&i.Metadata,
			&i.AllowedTools,
			&i.IsBuiltin,
			&i.Enabled,
			&i.Version,
			&i.License,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSkillEnabled = `-- name: SetSkillEnabled :one
UPDATE skills
SET enabled = $3, updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, name, description, prompt, scripts, metadata, allowed_tools, is_builtin, enabled, version, license, source, created_at, updated_at
`

type SetSkillEnabledParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
	Enabled bool
}

// #48-2: owner 全局开/关一个 skill(builtin 也可开关)。
func (q *Queries) SetSkillEnabled(ctx context.Context, arg SetSkillEnabledParams) (Skill, error) {
	row := q.db.QueryRow(ctx, setSkillEnabled, arg.ID, arg.OwnerID, arg.Enabled)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Prompt,
		&i.Scripts,
		&i.Metadata,
		&i.AllowedTools,
		&i.IsBuiltin,
		&i.Enabled,
		&i.Version,
		&i.License,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSkill = `-- name: UpdateSkill :one
UPDATE skills
SET name = $3, description = $4, prompt = $5, allowed_tools = $6, updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, name, description, prompt, scripts, metadata, allowed_tools, is_builtin, enabled, version, license, source, created_at, updated_at
`

type UpdateSkillParams struct {
	ID           pgtype.UUID
	OwnerID      pgtype.UUID
	Name         string
	Description  string
	Prompt       string
	AllowedTools []string
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, updateSkill,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Prompt,
		arg.AllowedTools,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Prompt,
		&i.Scripts,
		&i.Metadata,
		&i.AllowedTools,
		&i.IsBuiltin,
		&i.Enabled,
		&i.Version,
		&i.License,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBuiltinSkill = `-- name: UpsertBuiltinSkill :one
INSERT INTO skills (
    owner_id, name, description, prompt, is_builtin, source
)
VALUES ($1, $2, $3, $4, true, 'builtin')
ON CONFLICT (owner_id, name) DO UPDATE SET
    description = EXCLUDED.description,
    prompt = EXCLUDED.prompt,
    updated_at = now()
RETURNING id, owner_id, name, description, prompt, scripts, metadata, allowed_tools, is_builtin, enabled, version, license, source, created_at, updated_at
`

type UpsertBuiltinSkillParams struct {
	OwnerID     pgtype.UUID
	Name        string
	Description string
	Prompt      string
}

// Seed built-in skills: idempotent by (owner_id, name). Overwrite prompt /
// description / metadata 字段以便 future seed 调整后 re-run 生效。
func (q *Queries) UpsertBuiltinSkill(ctx context.Context, arg UpsertBuiltinSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, upsertBuiltinSkill,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Prompt,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Prompt,
		&i.Scripts,
		&i.Metadata,
		&i.AllowedTools,
		&i.IsBuiltin,
		&i.Enabled,
		&i.Version,
		&i.License,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
