// public-url-edit.spec.ts —— the owner edits the public URL in the /admin/account ·
// site-address block; /me immediately reflects the new value; the next application QR
// issued uses the new URL.
//
// User story:
//   The owner initially deploys at http://localhost:38127, then later attaches their
//   own domain, https://alice.dev. They open admin · account · site address, click
//   "change" on the public URL row, enter the new URL, and save. /me returns the new
//   value; after
//   the frontend sessionStore mutates, the display row refreshes to the new one.
//   Subsequent PDF QR codes generated by application.commit also point at the new URL.

import { test, expect } from '@/fixtures/test';

import { gotoAdminSection } from '@/fixtures/navigate';
import type { Page } from '@playwright/test';

import { claim } from '@/fixtures/admin';
import { resetInstance, findSetupToken } from '@/fixtures/instance';

const OWNER = {
  email: 'alice@example.com',
  password: 'correct-horse-battery-staple',
  handle: 'alice',
  fullName: 'Alice Anderson',
  // The claim helper defaults to http://localhost:38127; spelled out explicitly here for the assertion.
  initialPublicURL: 'http://localhost:38127',
};

const NEW_PUBLIC_URL = 'https://alice.dev';

test.use({ ownerCredentials: { email: OWNER.email, password: OWNER.password } });
test.describe('owner edits public URL post-claim', () => {
  test.beforeAll(async ({ playwright }) => {
    resetInstance();
    const request = await playwright.request.newContext();
    await claim(request, findSetupToken(), {
      email: OWNER.email, password: OWNER.password,
      handle: OWNER.handle, fullName: OWNER.fullName,
      publicUrl: OWNER.initialPublicURL,
    });
    await request.dispose();
  });

  test('change public URL via site block; display row shows new value',
    async ({ adminPage: page }) => {
      await gotoAdminSection(page, 'account');
      await expect(page.getByTestId('public-url-display')).toBeVisible();
      // The initial value is whatever was entered at claim time.
      await expect(page.getByTestId('public-url-display'))
        .toContainText(OWNER.initialPublicURL);

      await openEditor(page);
      await fillNewURL(page, NEW_PUBLIC_URL);
      await saveAndExpectDisplay(page, NEW_PUBLIC_URL);
    });

  test('invalid URL is rejected with inline hint',
    async ({ adminPage: page }) => {
      await gotoAdminSection(page, 'account');
      await openEditor(page);
      await page.getByTestId('public-url-input').fill('not-a-url');
      // the hint shows "must start with http(s)"; the save button is disabled
      await expect(page.getByTestId('public-url-hint'))
        .toContainText(/http/);
      await expect(page.getByTestId('public-url-save-btn')).toBeDisabled();
    });
});

async function openEditor(page: Page): Promise<void> {
  await page.getByTestId('public-url-change-btn').click();
  await expect(page.getByTestId('public-url-editor')).toBeVisible();
}

async function fillNewURL(page: Page, url: string): Promise<void> {
  await page.getByTestId('public-url-input').fill(url);
  await expect(page.getByTestId('public-url-save-btn')).toBeEnabled();
}

async function saveAndExpectDisplay(page: Page, url: string): Promise<void> {
  await page.getByTestId('public-url-save-btn').click();
  // editor closes → display row reappears with new URL.
  await expect(page.getByTestId('public-url-display'))
    .toBeVisible({ timeout: 5_000 });
  await expect(page.getByTestId('public-url-display')).toContainText(url);
}
