// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: applications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countApplications = `-- name: CountApplications :one
SELECT COUNT(*)::int FROM applications WHERE owner_id = $1
`

// How many applications the owner has in all, search or not: the header counts what was
// committed, and "no matches" is an empty page with a non-zero total.
func (q *Queries) CountApplications(ctx context.Context, ownerID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countApplications, ownerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (id, owner_id, access_code_id, job_snapshot, resume_content)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, access_code_id, job_snapshot, resume_content,
          status, submitted_at, created_at
`

type CreateApplicationParams struct {
	ID            pgtype.UUID
	OwnerID       pgtype.UUID
	AccessCodeID  pgtype.UUID
	JobSnapshot   []byte
	ResumeContent []byte
}

// id is caller-supplied so the final PDF (which embeds the application id in its print URL) can be
// rendered BEFORE this irreversible commit — a render failure then persists nothing (retryable),
// instead of stranding a committed application with no PDF.
func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.ID,
		arg.OwnerID,
		arg.AccessCodeID,
		arg.JobSnapshot,
		arg.ResumeContent,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AccessCodeID,
		&i.JobSnapshot,
		&i.ResumeContent,
		&i.Status,
		&i.SubmittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getApplication = `-- name: GetApplication :one
SELECT id, owner_id, access_code_id, job_snapshot, resume_content,
       status, submitted_at, created_at
FROM applications
WHERE id = $1 AND owner_id = $2
`

type GetApplicationParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetApplication(ctx context.Context, arg GetApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, getApplication, arg.ID, arg.OwnerID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AccessCodeID,
		&i.JobSnapshot,
		&i.ResumeContent,
		&i.Status,
		&i.SubmittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getApplicationByAccessCode = `-- name: GetApplicationByAccessCode :one
SELECT id, owner_id, access_code_id, job_snapshot, resume_content,
       status, submitted_at, created_at
FROM applications
WHERE access_code_id = $1 AND owner_id = $2
`

type GetApplicationByAccessCodeParams struct {
	AccessCodeID pgtype.UUID
	OwnerID      pgtype.UUID
}

// Look up the application bound to a session's access code. owner-scoped (defense in depth;
// access_code_id is already globally unique). The visitor-side resume tool uses it to lock "which one" to this code.
func (q *Queries) GetApplicationByAccessCode(ctx context.Context, arg GetApplicationByAccessCodeParams) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByAccessCode, arg.AccessCodeID, arg.OwnerID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AccessCodeID,
		&i.JobSnapshot,
		&i.ResumeContent,
		&i.Status,
		&i.SubmittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listApplicationsPage = `-- name: ListApplicationsPage :many
SELECT a.id, a.owner_id, a.access_code_id, a.job_snapshot, a.resume_content, a.status, a.submitted_at, a.created_at
FROM applications a
WHERE a.owner_id = $1
  AND ($2::text = ''
    OR (a.job_snapshot->>'company') ILIKE '%' || $2 || '%'
    OR (a.job_snapshot->>'title') ILIKE '%' || $2 || '%'
    OR a.status ILIKE '%' || $2 || '%')
  AND ($3::timestamptz IS NULL
    OR (a.created_at, a.id) < ($3, $4::uuid))
ORDER BY a.created_at DESC, a.id DESC
LIMIT $5
`

type ListApplicationsPageParams struct {
	OwnerID pgtype.UUID
	Q       string
	AfterAt pgtype.Timestamptz
	AfterID pgtype.UUID
	Lim     int32
}

type ListApplicationsPageRow struct {
	Application Application
}

// One page of the owner's applications, newest first (docs/design/paging.md). q: case-insensitive
// substring of the company, the role or the status (the recruiter calls; the owner types the
// company). The page's total comes from CountApplications, not a column here: a search that
// matches nothing returns no rows to carry it.
func (q *Queries) ListApplicationsPage(ctx context.Context, arg ListApplicationsPageParams) ([]ListApplicationsPageRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsPage,
		arg.OwnerID,
		arg.Q,
		arg.AfterAt,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsPageRow
	for rows.Next() {
		var i ListApplicationsPageRow
		if err := rows.Scan(
			&i.Application.ID,
			&i.Application.OwnerID,
			&i.Application.AccessCodeID,
			&i.Application.JobSnapshot,
			&i.Application.ResumeContent,
			&i.Application.Status,
			&i.Application.SubmittedAt,
			&i.Application.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
