// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: resume_masters.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultResumeMaster = `-- name: ClearDefaultResumeMaster :exec
UPDATE resume_masters SET is_default = false WHERE owner_id = $1 AND is_default
`

// Step one of "make X the default" (same transaction as SetDefaultResumeMaster): the partial unique
// index allows one default per owner, and it is checked row by row, so the old one goes first.
func (q *Queries) ClearDefaultResumeMaster(ctx context.Context, ownerID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultResumeMaster, ownerID)
	return err
}

const countResumeMasters = `-- name: CountResumeMasters :one
SELECT COUNT(*)::int FROM resume_masters WHERE owner_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountResumeMasters(ctx context.Context, ownerID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countResumeMasters, ownerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createResumeMaster = `-- name: CreateResumeMaster :one

INSERT INTO resume_masters (owner_id, name, resume_content, from_company)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, name, resume_content, is_default, from_company, created_at, updated_at, deleted_at
`

type CreateResumeMasterParams struct {
	OwnerID       pgtype.UUID
	Name          string
	ResumeContent []byte
	FromCompany   string
}

// resume_masters —— named, persistent résumés (docs/design/resume-masters.md). A deleted master waits
// in the trash (deleted_at set) for 90 days: every read below except the trash's own filters it.
func (q *Queries) CreateResumeMaster(ctx context.Context, arg CreateResumeMasterParams) (ResumeMaster, error) {
	row := q.db.QueryRow(ctx, createResumeMaster,
		arg.OwnerID,
		arg.Name,
		arg.ResumeContent,
		arg.FromCompany,
	)
	var i ResumeMaster
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.ResumeContent,
		&i.IsDefault,
		&i.FromCompany,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteResumeMaster = `-- name: DeleteResumeMaster :execrows
UPDATE resume_masters SET deleted_at = now(), is_default = false
WHERE id = $1 AND owner_id = $2 AND deleted_at IS NULL
`

type DeleteResumeMasterParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

// Into the trash: a trashed master is never the default (the index counts live masters only).
func (q *Queries) DeleteResumeMaster(ctx context.Context, arg DeleteResumeMasterParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteResumeMaster, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDefaultResumeMaster = `-- name: GetDefaultResumeMaster :one
SELECT id, owner_id, name, resume_content, is_default, from_company, created_at, updated_at, deleted_at FROM resume_masters WHERE owner_id = $1 AND is_default AND deleted_at IS NULL
`

func (q *Queries) GetDefaultResumeMaster(ctx context.Context, ownerID pgtype.UUID) (ResumeMaster, error) {
	row := q.db.QueryRow(ctx, getDefaultResumeMaster, ownerID)
	var i ResumeMaster
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.ResumeContent,
		&i.IsDefault,
		&i.FromCompany,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getResumeMaster = `-- name: GetResumeMaster :one
SELECT id, owner_id, name, resume_content, is_default, from_company, created_at, updated_at, deleted_at FROM resume_masters WHERE id = $1 AND owner_id = $2 AND deleted_at IS NULL
`

type GetResumeMasterParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetResumeMaster(ctx context.Context, arg GetResumeMasterParams) (ResumeMaster, error) {
	row := q.db.QueryRow(ctx, getResumeMaster, arg.ID, arg.OwnerID)
	var i ResumeMaster
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.ResumeContent,
		&i.IsDefault,
		&i.FromCompany,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listResumeMastersPage = `-- name: ListResumeMastersPage :many
SELECT id, owner_id, name, resume_content, is_default, from_company, created_at, updated_at, deleted_at FROM resume_masters
WHERE owner_id = $1 AND deleted_at IS NULL
  AND ($2::timestamptz IS NULL
    OR (created_at, id) < ($2, $3::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListResumeMastersPageParams struct {
	OwnerID pgtype.UUID
	AfterAt pgtype.Timestamptz
	AfterID pgtype.UUID
	Lim     int32
}

// One page of the owner's masters, newest first (docs/design/paging.md).
func (q *Queries) ListResumeMastersPage(ctx context.Context, arg ListResumeMastersPageParams) ([]ResumeMaster, error) {
	rows, err := q.db.Query(ctx, listResumeMastersPage,
		arg.OwnerID,
		arg.AfterAt,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResumeMaster
	for rows.Next() {
		var i ResumeMaster
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.ResumeContent,
			&i.IsDefault,
			&i.FromCompany,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedResumeMasters = `-- name: ListTrashedResumeMasters :many
SELECT id, name, deleted_at::timestamptz AS deleted_at FROM resume_masters
WHERE owner_id = $1 AND deleted_at IS NOT NULL
ORDER BY deleted_at DESC, id DESC
`

type ListTrashedResumeMastersRow struct {
	ID        pgtype.UUID
	Name      string
	DeletedAt pgtype.Timestamptz
}

// The trash: newest delete first. Small by nature (a handful of masters per owner, 90 days).
func (q *Queries) ListTrashedResumeMasters(ctx context.Context, ownerID pgtype.UUID) ([]ListTrashedResumeMastersRow, error) {
	rows, err := q.db.Query(ctx, listTrashedResumeMasters, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrashedResumeMastersRow
	for rows.Next() {
		var i ListTrashedResumeMastersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.DeletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeTrashedResumeMasters = `-- name: PurgeTrashedResumeMasters :execrows
DELETE FROM resume_masters WHERE deleted_at < $1::timestamptz
`

func (q *Queries) PurgeTrashedResumeMasters(ctx context.Context, before pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgeTrashedResumeMasters, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreResumeMaster = `-- name: RestoreResumeMaster :execrows
UPDATE resume_masters SET deleted_at = NULL, updated_at = now()
WHERE id = $1 AND owner_id = $2 AND deleted_at IS NOT NULL
`

type RestoreResumeMasterParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) RestoreResumeMaster(ctx context.Context, arg RestoreResumeMasterParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreResumeMaster, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setDefaultResumeMaster = `-- name: SetDefaultResumeMaster :execrows
UPDATE resume_masters SET is_default = true WHERE id = $1 AND owner_id = $2 AND deleted_at IS NULL
`

type SetDefaultResumeMasterParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) SetDefaultResumeMaster(ctx context.Context, arg SetDefaultResumeMasterParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDefaultResumeMaster, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateResumeMaster = `-- name: UpdateResumeMaster :one
UPDATE resume_masters
SET name           = COALESCE($1, name),
    resume_content = COALESCE($2, resume_content),
    from_company   = COALESCE($3, from_company),
    updated_at     = now()
WHERE id = $4 AND owner_id = $5 AND deleted_at IS NULL
RETURNING id, owner_id, name, resume_content, is_default, from_company, created_at, updated_at, deleted_at
`

type UpdateResumeMasterParams struct {
	Name          *string
	ResumeContent []byte
	FromCompany   *string
	ID            pgtype.UUID
	OwnerID       pgtype.UUID
}

// A partial update: a NULL argument keeps the column (rename alone must not blank the content).
func (q *Queries) UpdateResumeMaster(ctx context.Context, arg UpdateResumeMasterParams) (ResumeMaster, error) {
	row := q.db.QueryRow(ctx, updateResumeMaster,
		arg.Name,
		arg.ResumeContent,
		arg.FromCompany,
		arg.ID,
		arg.OwnerID,
	)
	var i ResumeMaster
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.ResumeContent,
		&i.IsDefault,
		&i.FromCompany,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
