// Package pgstore — shared DB store primitives: pgx pool alias, minimal DBTX interface,
// uuid conversion, owner-id parse error prefix, boundary encrypt/decrypt. Each domain
// module's repo uses it plus its own <domain>/db (sqlc) persistence layer.
// (Corresponds to the domain-less "pgxpool" shared infra in the structure design: keeps
// only the one real infra primitive — the connection — and no domain DAO.)
package pgstore

import (
	"context"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Pool — pgx pool alias (makes it easy to swap in a mock).
type Pool = pgxpool.Pool

// DBTX — minimal query interface (satisfied by both pgxpool.Pool / pgx.Tx); its shape
// matches the DBTX generated by each domain's sqlc package, so instances are interchangeable.
// The infra layer holds only this one DB primitive, with no dependency on any domain's
// generated DAO.
type DBTX interface {
	Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
}

// ErrParseOwnerIDPrefix — the uniform wrap prefix for an owner_id string parse failure.
const ErrParseOwnerIDPrefix = "parse owner id: %w"

const (
	uuidStringLen = 36
	uuidDash1     = 8
	uuidDash2     = 13
	uuidDash3     = 18
	uuidDash4     = 23
)

// ParseUUID — RFC 4122 string → pgtype.UUID. Returns an error on invalid input.
func ParseUUID(s string) (pgtype.UUID, error) {
	var u pgtype.UUID
	if err := u.Scan(s); err != nil {
		return pgtype.UUID{}, fmt.Errorf("scan uuid: %w", err)
	}
	return u, nil
}

// IsUUID — whether s is a valid RFC 4122 uuid string (a slug is never mistaken for true).
func IsUUID(s string) bool {
	var u pgtype.UUID
	return u.Scan(s) == nil
}

// FormatUUID — pgtype.UUID → RFC 4122 string. Invalid → "".
func FormatUUID(u pgtype.UUID) string {
	if !u.Valid {
		return ""
	}
	src := u.Bytes[:]
	buf := make([]byte, uuidStringLen)
	hex.Encode(buf[0:uuidDash1], src[0:4])
	buf[uuidDash1] = '-'
	hex.Encode(buf[uuidDash1+1:uuidDash2], src[4:6])
	buf[uuidDash2] = '-'
	hex.Encode(buf[uuidDash2+1:uuidDash3], src[6:8])
	buf[uuidDash3] = '-'
	hex.Encode(buf[uuidDash3+1:uuidDash4], src[8:10])
	buf[uuidDash4] = '-'
	hex.Encode(buf[uuidDash4+1:uuidStringLen], src[10:16])
	return strings.ToLower(string(buf))
}

// This used to hold a MaybeEncrypt / DecryptOrEmpty pair of generic helpers — **zero
// callers**, unused since the day they were built. Removing them isn't just cleanup:
// DecryptOrEmpty left an open seam hanging off internal/infra, a base anyone can import,
// and that base is exactly the place that should never carry an open seam.

// OptTime — pgtype.Timestamptz → *time.Time (invalid → nil).
func OptTime(t pgtype.Timestamptz) *time.Time {
	if !t.Valid {
		return nil
	}
	tt := t.Time
	return &tt
}

// ToTimestamptz — *time.Time → pgtype.Timestamptz (nil → invalid).
func ToTimestamptz(t *time.Time) pgtype.Timestamptz {
	if t == nil {
		return pgtype.Timestamptz{Valid: false}
	}
	return pgtype.Timestamptz{Time: *t, Valid: true}
}

// uniqueViolationSQLState — the SQLSTATE for a Postgres unique_violation.
const uniqueViolationSQLState = "23505"

// UniqueViolation — whether err is a unique constraint violation; if so, returns the
// constraint name + true.
func UniqueViolation(err error) (string, bool) {
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) && pgErr.Code == uniqueViolationSQLState {
		return pgErr.ConstraintName, true
	}
	return "", false
}

// NilSafeStrings — nil slice → non-nil empty slice (guards null at the JSON/DB boundary).
func NilSafeStrings(s []string) []string {
	if s == nil {
		return []string{}
	}
	return s
}

// UUIDStrings — []pgtype.UUID → []string (FormatUUID applied to each).
func UUIDStrings(us []pgtype.UUID) []string {
	out := make([]string, 0, len(us))
	for _, u := range us {
		out = append(out, FormatUUID(u))
	}
	return out
}

// ParseOptionalUUID — nil/empty string → zero-value UUID (no error); otherwise parses.
// The generic helper the repo layer uses to convert a nullable foreign key to pgtype.UUID.
func ParseOptionalUUID(s *string) (pgtype.UUID, error) {
	if s == nil || *s == "" {
		return pgtype.UUID{}, nil
	}
	return ParseUUID(*s)
}

// ParseUUIDArray — a batch of id strings → []pgtype.UUID; returns an error on the
// first failure.
func ParseUUIDArray(ids []string) ([]pgtype.UUID, error) {
	out := make([]pgtype.UUID, 0, len(ids))
	for _, id := range ids {
		u, err := ParseUUID(id)
		if err != nil {
			return nil, err
		}
		out = append(out, u)
	}
	return out, nil
}

// FormatUUIDList — []pgtype.UUID → []string.
func FormatUUIDList(uu []pgtype.UUID) []string {
	out := make([]string, 0, len(uu))
	for _, u := range uu {
		out = append(out, FormatUUID(u))
	}
	return out
}

// OptUUIDStr — nullable UUID → *string (invalid → nil). The generic helper the repo
// layer uses to convert a nullable foreign key to a frontend-omittable field.
func OptUUIDStr(u pgtype.UUID) *string {
	if !u.Valid {
		return nil
	}
	s := FormatUUID(u)
	return &s
}

// UUIDStrOrEmpty — nullable uuid → string, NULL → empty string.
// Used on domain fields where "unset = empty string" (the nullable-foreign-key class:
// NULL and "the row it pointed to got deleted" are the same thing).
func UUIDStrOrEmpty(u pgtype.UUID) string {
	if !u.Valid {
		return ""
	}
	return FormatUUID(u)
}

// UUIDOrNull — string → nullable uuid. Empty (or invalid) = NULL, not an error: what the
// caller handed over is the fact "pointing at nobody," and that's exactly what a nullable
// foreign key accepts.
func UUIDOrNull(s string) pgtype.UUID {
	if s == "" {
		return pgtype.UUID{}
	}
	u, err := ParseUUID(s)
	if err != nil {
		return pgtype.UUID{}
	}
	return u
}

// — pgx pool connection management (migrated in from the retired internal/postgres/conn.go) —

const (
	poolMaxConns       = 20
	poolMinConns       = 2
	poolMaxConnLife    = 30 * time.Minute
	poolMaxConnIdle    = 5 * time.Minute
	connectPingTimeout = 5 * time.Second
	pingTimeout        = 2 * time.Second
)

// Connect establishes the pool. connStr usually comes from config.DatabaseURL. The
// caller is responsible for pool.Close() on exit.
func Connect(ctx context.Context, connStr string) (*Pool, error) {
	cfg, err := pgxpool.ParseConfig(connStr)
	if err != nil {
		return nil, fmt.Errorf("parse pg dsn: %w", err)
	}
	cfg.MaxConns = poolMaxConns
	cfg.MinConns = poolMinConns
	cfg.MaxConnLifetime = poolMaxConnLife
	cfg.MaxConnIdleTime = poolMaxConnIdle
	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("connect pg: %w", err)
	}
	// fail-fast: verify the connection once, so the server doesn't come "up" while
	// actually unable to reach the DB.
	pingCtx, cancel := context.WithTimeout(ctx, connectPingTimeout)
	defer cancel()
	if pingErr := pool.Ping(pingCtx); pingErr != nil {
		pool.Close()
		return nil, fmt.Errorf("ping pg: %w", pingErr)
	}
	return pool, nil
}

// Ping checks via the shortest path that the pool is still alive; used by healthz.
func Ping(ctx context.Context, pool *Pool) error {
	pingCtx, cancel := context.WithTimeout(ctx, pingTimeout)
	defer cancel()
	if err := pool.Ping(pingCtx); err != nil {
		return fmt.Errorf("pg ping: %w", err)
	}
	return nil
}
