// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: block_connections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearBlockTokens = `-- name: ClearBlockTokens :exec
UPDATE block_connections
SET token_enc = '\x'::bytea, token_expires_at = NULL,
    connected_at = NULL, active = false, updated_at = now()
WHERE owner_id = $1 AND block_id = $2
`

type ClearBlockTokensParams struct {
	OwnerID pgtype.UUID
	BlockID string
}

// soft disconnect: wipe token + connected + active, keep credentials (one-click reconnect without re-entering).
func (q *Queries) ClearBlockTokens(ctx context.Context, arg ClearBlockTokensParams) error {
	_, err := q.db.Exec(ctx, clearBlockTokens, arg.OwnerID, arg.BlockID)
	return err
}

const deleteBlockConnection = `-- name: DeleteBlockConnection :exec
DELETE FROM block_connections
WHERE owner_id = $1 AND block_id = $2
`

type DeleteBlockConnectionParams struct {
	OwnerID pgtype.UUID
	BlockID string
}

func (q *Queries) DeleteBlockConnection(ctx context.Context, arg DeleteBlockConnectionParams) error {
	_, err := q.db.Exec(ctx, deleteBlockConnection, arg.OwnerID, arg.BlockID)
	return err
}

const deleteUploadedBlock = `-- name: DeleteUploadedBlock :exec
DELETE FROM block_connections
WHERE owner_id = $1 AND block_id = $2
`

type DeleteUploadedBlockParams struct {
	OwnerID pgtype.UUID
	BlockID string
}

// Delete an owner-authored block (row delete). The seam it supplied goes empty (the seam store reads
// nothing → every consumer re-gates).
func (q *Queries) DeleteUploadedBlock(ctx context.Context, arg DeleteUploadedBlockParams) error {
	_, err := q.db.Exec(ctx, deleteUploadedBlock, arg.OwnerID, arg.BlockID)
	return err
}

const getBlockConnection = `-- name: GetBlockConnection :one
SELECT id, owner_id, block_id, seam, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, spec, binding, auth_scheme, protocol, expose_as_agent_tools, title, created_at, updated_at FROM block_connections
WHERE owner_id = $1 AND block_id = $2
`

type GetBlockConnectionParams struct {
	OwnerID pgtype.UUID
	BlockID string
}

func (q *Queries) GetBlockConnection(ctx context.Context, arg GetBlockConnectionParams) (BlockConnection, error) {
	row := q.db.QueryRow(ctx, getBlockConnection, arg.OwnerID, arg.BlockID)
	var i BlockConnection
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.BlockID,
		&i.Seam,
		&i.Kind,
		&i.CredentialsEnc,
		&i.TokenEnc,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.ConnectedAt,
		&i.Active,
		&i.Spec,
		&i.Binding,
		&i.AuthScheme,
		&i.Protocol,
		&i.ExposeAsAgentTools,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBlockManifest = `-- name: GetBlockManifest :one
SELECT seam, kind, spec, binding, auth_scheme, protocol, expose_as_agent_tools
FROM block_connections
WHERE owner_id = $1 AND block_id = $2
`

type GetBlockManifestParams struct {
	OwnerID pgtype.UUID
	BlockID string
}

type GetBlockManifestRow struct {
	Seam               string
	Kind               string
	Spec               []byte
	Binding            []byte
	AuthScheme         string
	Protocol           string
	ExposeAsAgentTools bool
}

// Fetch a block's stored manifest fields (uploaded blocks have spec/binding; protocol blocks have protocol).
func (q *Queries) GetBlockManifest(ctx context.Context, arg GetBlockManifestParams) (GetBlockManifestRow, error) {
	row := q.db.QueryRow(ctx, getBlockManifest, arg.OwnerID, arg.BlockID)
	var i GetBlockManifestRow
	err := row.Scan(
		&i.Seam,
		&i.Kind,
		&i.Spec,
		&i.Binding,
		&i.AuthScheme,
		&i.Protocol,
		&i.ExposeAsAgentTools,
	)
	return i, err
}

const insertUploadedBlock = `-- name: InsertUploadedBlock :one
INSERT INTO block_connections (
    owner_id, block_id, seam, kind, spec, binding, auth_scheme, protocol,
    expose_as_agent_tools, title
)
VALUES (
    $1, $2, $3,
    $4, $5::bytea, $6::bytea,
    $7, $8, $9,
    $10
)
RETURNING id, owner_id, block_id, seam, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, spec, binding, auth_scheme, protocol, expose_as_agent_tools, title, created_at, updated_at
`

type InsertUploadedBlockParams struct {
	OwnerID            pgtype.UUID
	BlockID            string
	Seam               string
	Kind               string
	Spec               []byte
	Binding            []byte
	AuthScheme         string
	Protocol           string
	ExposeAsAgentTools bool
	Title              string
}

// Upload an openapi block (owner pastes spec + JSONata binding in the UI): create the row and store the manifest
// (spec/binding/auth_scheme), not connected on first write. seam/kind are set by the binding.
func (q *Queries) InsertUploadedBlock(ctx context.Context, arg InsertUploadedBlockParams) (BlockConnection, error) {
	row := q.db.QueryRow(ctx, insertUploadedBlock,
		arg.OwnerID,
		arg.BlockID,
		arg.Seam,
		arg.Kind,
		arg.Spec,
		arg.Binding,
		arg.AuthScheme,
		arg.Protocol,
		arg.ExposeAsAgentTools,
		arg.Title,
	)
	var i BlockConnection
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.BlockID,
		&i.Seam,
		&i.Kind,
		&i.CredentialsEnc,
		&i.TokenEnc,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.ConnectedAt,
		&i.Active,
		&i.Spec,
		&i.Binding,
		&i.AuthScheme,
		&i.Protocol,
		&i.ExposeAsAgentTools,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBlockConnectionsByOwner = `-- name: ListBlockConnectionsByOwner :many
SELECT id, owner_id, block_id, seam, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, spec, binding, auth_scheme, protocol, expose_as_agent_tools, title, created_at, updated_at FROM block_connections
WHERE owner_id = $1
ORDER BY seam, block_id
`

func (q *Queries) ListBlockConnectionsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]BlockConnection, error) {
	rows, err := q.db.Query(ctx, listBlockConnectionsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlockConnection
	for rows.Next() {
		var i BlockConnection
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.BlockID,
			&i.Seam,
			&i.Kind,
			&i.CredentialsEnc,
			&i.TokenEnc,
			&i.TokenExpiresAt,
			&i.Scopes,
			&i.ConnectedAt,
			&i.Active,
			&i.Spec,
			&i.Binding,
			&i.AuthScheme,
			&i.Protocol,
			&i.ExposeAsAgentTools,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlockConnectionsBySeam = `-- name: ListBlockConnectionsBySeam :many
SELECT id, owner_id, block_id, seam, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, spec, binding, auth_scheme, protocol, expose_as_agent_tools, title, created_at, updated_at FROM block_connections
WHERE owner_id = $1 AND seam = $2
ORDER BY block_id
`

type ListBlockConnectionsBySeamParams struct {
	OwnerID pgtype.UUID
	Seam    string
}

func (q *Queries) ListBlockConnectionsBySeam(ctx context.Context, arg ListBlockConnectionsBySeamParams) ([]BlockConnection, error) {
	rows, err := q.db.Query(ctx, listBlockConnectionsBySeam, arg.OwnerID, arg.Seam)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlockConnection
	for rows.Next() {
		var i BlockConnection
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.BlockID,
			&i.Seam,
			&i.Kind,
			&i.CredentialsEnc,
			&i.TokenEnc,
			&i.TokenExpiresAt,
			&i.Scopes,
			&i.ConnectedAt,
			&i.Active,
			&i.Spec,
			&i.Binding,
			&i.AuthScheme,
			&i.Protocol,
			&i.ExposeAsAgentTools,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadedBlocks = `-- name: ListUploadedBlocks :many
SELECT DISTINCT ON (block_id)
    block_id, seam, kind, spec, binding, auth_scheme, protocol, expose_as_agent_tools
FROM block_connections
WHERE length(spec) > 0 OR kind = 'protocol'
ORDER BY block_id, updated_at DESC
`

type ListUploadedBlocksRow struct {
	BlockID            string
	Seam               string
	Kind               string
	Spec               []byte
	Binding            []byte
	AuthScheme         string
	Protocol           string
	ExposeAsAgentTools bool
}

// Reload on boot: all owner-authored blocks (openapi with a spec + kind=protocol blocks), across owners
// (v1 single owner; the supplier table keys by block_id). A built-in has an empty spec and kind!=protocol,
// so it is excluded.
func (q *Queries) ListUploadedBlocks(ctx context.Context) ([]ListUploadedBlocksRow, error) {
	rows, err := q.db.Query(ctx, listUploadedBlocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUploadedBlocksRow
	for rows.Next() {
		var i ListUploadedBlocksRow
		if err := rows.Scan(
			&i.BlockID,
			&i.Seam,
			&i.Kind,
			&i.Spec,
			&i.Binding,
			&i.AuthScheme,
			&i.Protocol,
			&i.ExposeAsAgentTools,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBlockConnected = `-- name: MarkBlockConnected :execrows
UPDATE block_connections
SET connected_at = COALESCE(connected_at, now()), updated_at = now()
WHERE owner_id = $1 AND block_id = $2
`

type MarkBlockConnectedParams struct {
	OwnerID pgtype.UUID
	BlockID string
}

// A protocol block verified (no oauth dance) → mark connected.
// **:execrows, not :exec** —— this row is created by the "store credentials" step. When the owner does not have
// it yet, this UPDATE matches 0 rows without erroring and the caller still returns connected:true —— a lie, and
// one that every fresh install hits. The row count is the only receipt this write has; the caller must read it.
func (q *Queries) MarkBlockConnected(ctx context.Context, arg MarkBlockConnectedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markBlockConnected, arg.OwnerID, arg.BlockID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setActiveSupplier = `-- name: SetActiveSupplier :many
UPDATE block_connections
SET active = (block_id = $1::text), updated_at = now()
WHERE owner_id = $2 AND seam = $3
RETURNING block_id
`

type SetActiveSupplierParams struct {
	BlockID string
	OwnerID pgtype.UUID
	Seam    string
}

// Only one supplier per seam at a time: set the target active, set the rest of the seam inactive.
// **RETURNING is the receipt.** The row count proves nothing here: the update spans the whole seam, and when the
// target row is not among them the rest are all set inactive while the count stays > 0 —— the result of "activate" is
// that **this seam has no supplier at all**. So the receipt must be the names: the caller checks whether the target
// block_id is in the returned set.
func (q *Queries) SetActiveSupplier(ctx context.Context, arg SetActiveSupplierParams) ([]string, error) {
	rows, err := q.db.Query(ctx, setActiveSupplier, arg.BlockID, arg.OwnerID, arg.Seam)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var block_id string
		if err := rows.Scan(&block_id); err != nil {
			return nil, err
		}
		items = append(items, block_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlockTokens = `-- name: UpdateBlockTokens :one
UPDATE block_connections
SET token_enc = $1::bytea,
    token_expires_at = $2::timestamptz,
    scopes = $3::jsonb,
    connected_at = COALESCE(connected_at, now()),
    updated_at = now()
WHERE owner_id = $4 AND block_id = $5
RETURNING id, owner_id, block_id, seam, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, spec, binding, auth_scheme, protocol, expose_as_agent_tools, title, created_at, updated_at
`

type UpdateBlockTokensParams struct {
	TokenEnc       []byte
	TokenExpiresAt pgtype.Timestamptz
	Scopes         []byte
	OwnerID        pgtype.UUID
	BlockID        string
}

// OAuth gets its first token, or the refresh path gets a new access_token. First token obtained → connected.
func (q *Queries) UpdateBlockTokens(ctx context.Context, arg UpdateBlockTokensParams) (BlockConnection, error) {
	row := q.db.QueryRow(ctx, updateBlockTokens,
		arg.TokenEnc,
		arg.TokenExpiresAt,
		arg.Scopes,
		arg.OwnerID,
		arg.BlockID,
	)
	var i BlockConnection
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.BlockID,
		&i.Seam,
		&i.Kind,
		&i.CredentialsEnc,
		&i.TokenEnc,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.ConnectedAt,
		&i.Active,
		&i.Spec,
		&i.Binding,
		&i.AuthScheme,
		&i.Protocol,
		&i.ExposeAsAgentTools,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUploadedBlock = `-- name: UpdateUploadedBlock :exec
UPDATE block_connections
SET spec = $1::bytea, binding = $2::bytea,
    seam = $3, auth_scheme = $4,
    expose_as_agent_tools = $5,
    title = $6,
    connected_at = NULL, updated_at = now()
WHERE owner_id = $7 AND block_id = $8
`

type UpdateUploadedBlockParams struct {
	Spec               []byte
	Binding            []byte
	Seam               string
	AuthScheme         string
	ExposeAsAgentTools bool
	Title              string
	OwnerID            pgtype.UUID
	BlockID            string
}

// Edit the spec/binding/auth_scheme of an existing uploaded block (owner edits the spec in the UI → reassemble +
// re-derive the credentials form). After changing the auth type the credentials must be re-entered, so clear
// connected_at (reconnect). The seam may change with it.
func (q *Queries) UpdateUploadedBlock(ctx context.Context, arg UpdateUploadedBlockParams) error {
	_, err := q.db.Exec(ctx, updateUploadedBlock,
		arg.Spec,
		arg.Binding,
		arg.Seam,
		arg.AuthScheme,
		arg.ExposeAsAgentTools,
		arg.Title,
		arg.OwnerID,
		arg.BlockID,
	)
	return err
}

const upsertBlockCredentials = `-- name: UpsertBlockCredentials :one

INSERT INTO block_connections (
    owner_id, block_id, seam, kind, credentials_enc
)
VALUES (
    $1, $2, $3,
    $4, $5::bytea
)
ON CONFLICT (owner_id, block_id) DO UPDATE
SET credentials_enc = EXCLUDED.credentials_enc,
    seam = EXCLUDED.seam,
    kind = EXCLUDED.kind,
    connected_at = CASE
        WHEN $6::boolean THEN NULL
        ELSE block_connections.connected_at
    END,
    updated_at = now()
RETURNING id, owner_id, block_id, seam, kind, credentials_enc, token_enc, token_expires_at, scopes, connected_at, active, spec, binding, auth_scheme, protocol, expose_as_agent_tools, title, created_at, updated_at
`

type UpsertBlockCredentialsParams struct {
	OwnerID        pgtype.UUID
	BlockID        string
	Seam           string
	Kind           string
	CredentialsEnc []byte
	ResetConnected bool
}

// block_connections.sql —— read/write of one block's connection to whatever is outside:
// credentials, tokens, whether it is connected, and which supplier is live for a seam.
//
// One table for any kind of block and any seam. The block's DEFINITION is not here — a
// built-in's is `blocks/<id>/manifest.yaml`, an owner-installed one's is `installed_blocks`.
// Store/overwrite one block's credentials (owner-supplied app creds / apiKey / smtp config).
// seam/kind are set on first write.
//
// connected_at is decided by `reset_connected`, **not cleared unconditionally** (F-C-30):
// §3 D-5 requires "changing identity/credentials must re-verify" —— that rule should fire only when something
// **changed**. But the first thing the panel's Connect does is POST /credentials, so "connected" is lost before
// authorization even starts; the owner only has to reopen the card and re-save once (without touching a single
// value) and a perfectly good connection shows as "not connected" while the token is still alive.
// The caller compares the merged credentials against the original: pass true only when they truly changed.
func (q *Queries) UpsertBlockCredentials(ctx context.Context, arg UpsertBlockCredentialsParams) (BlockConnection, error) {
	row := q.db.QueryRow(ctx, upsertBlockCredentials,
		arg.OwnerID,
		arg.BlockID,
		arg.Seam,
		arg.Kind,
		arg.CredentialsEnc,
		arg.ResetConnected,
	)
	var i BlockConnection
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.BlockID,
		&i.Seam,
		&i.Kind,
		&i.CredentialsEnc,
		&i.TokenEnc,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.ConnectedAt,
		&i.Active,
		&i.Spec,
		&i.Binding,
		&i.AuthScheme,
		&i.Protocol,
		&i.ExposeAsAgentTools,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
